// Animation-only GLB patch. Every source node, mesh and geometry byte stays intact.
import fs from 'node:fs';import zlib from 'node:zlib';import crypto from 'node:crypto';import path from 'node:path';
import * as T from '../robot_integrated_v22/vendor/three.mjs';
import {MeshoptDecoder} from '../robot_integrated_v22/meshopt/package/meshopt_decoder.mjs';
import {Rig} from '../../../otonom/hat/robot-integrated-v25/rig.js';
import {compileOrder} from '../../../otonom/hat/robot-integrated-v25/workflow-v16.js';
await MeshoptDecoder.ready;
const A='otonom/hat3d/robot-integrated-v28/',input=process.argv[2]||'otonom/hat3d/robot-integrated-v27/hat3_robot_v27.glb.gz';
let raw=fs.readFileSync(input);if(raw[0]===31&&raw[1]===139)raw=zlib.gunzipSync(raw);
const jl=raw.readUInt32LE(12),g=JSON.parse(raw.subarray(20,20+jl)),bin=raw.subarray(28+jl,28+jl+raw.readUInt32LE(20+jl)),original=structuredClone(g);
const pad=x=>(x+3)&~3,sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const chunks=[bin],accCache=new Map();let offset=bin.length;
function acc(values,size){const a=new Float32Array(values),b=Buffer.from(a.buffer),key=size+':'+sha(b);if(accCache.has(key))return accCache.get(key);if(offset%4){chunks.push(Buffer.alloc(pad(offset)-offset));offset=pad(offset);}const vi=g.bufferViews.length;g.bufferViews.push({buffer:0,byteOffset:offset,byteLength:b.length});chunks.push(b);offset+=b.length;const id=g.accessors.length,min=Array(size).fill(Infinity),max=Array(size).fill(-Infinity);for(let i=0;i<a.length;i++){min[i%size]=Math.min(min[i%size],a[i]);max[i%size]=Math.max(max[i%size],a[i]);}g.accessors.push({bufferView:vi,componentType:5126,count:a.length/size,type:size===1?'SCALAR':'VEC'+size,min,max});accCache.set(key,id);return id;}
const decoded=new Map();function values(id){const a=original.accessors[id],v=original.bufferViews[a.bufferView];let b;if(decoded.has(a.bufferView))b=decoded.get(a.bufferView);else{if(v.extensions?.EXT_meshopt_compression){const e=v.extensions.EXT_meshopt_compression;b=Buffer.alloc(e.count*e.byteStride);MeshoptDecoder.decodeGltfBuffer(b,e.count,e.byteStride,bin.subarray(e.byteOffset,e.byteOffset+e.byteLength),e.mode,e.filter);}else b=bin.subarray(v.byteOffset||0,(v.byteOffset||0)+v.byteLength);decoded.set(a.bufferView,b);}const size={SCALAR:1,VEC3:3,VEC4:4}[a.type];if(a.componentType!==5126)throw Error('Animation must be float');const out=[];for(let i=0;i<a.count;i++)for(let k=0;k<size;k++)out.push(b.readFloatLE((a.byteOffset||0)+i*(v.byteStride||size*4)+k*4));return out;}
const oldManifest=JSON.parse(fs.readFileSync('otonom/hat3d/robot-integrated-v27/manifest.json')),base=JSON.parse(fs.readFileSync(A+'order_v28.json')),oldBase=JSON.parse(fs.readFileSync('otonom/hat3d/robot-integrated-v25/order_v25.json')),config=JSON.parse(fs.readFileSync('otonom/hat3d/robot-integrated-v25/workflow_v25.json')),plan=JSON.parse(fs.readFileSync(A+'turn_plan.json'));
const data=JSON.parse(fs.readFileSync('otonom/hat3d/robot-integrated-v25/rig.json')),rig=new Rig(data,{mountForward:.1,railForward:.5}),bodyNames=new Map(Object.entries(data.body_nodes).map(([b,n])=>['UR10E_'+n,b]));
const M=x=>new T.Matrix4().set(...x),C=new T.Matrix4().makeRotationX(-Math.PI/2),trs=m=>{const p=new T.Vector3(),q=new T.Quaternion(),s=new T.Vector3();m.decompose(p,q,s);return {p:p.toArray(),q:q.toArray()};};
function chain(k,rail){const fixed=oldManifest.services.chain.fixed_world,r=.15,length=2.05+Math.PI*r,b=(fixed[0]+rail+2.05)/2,s=(k+.5)*length/80,L=b-fixed[0];if(s<L)return {p:[fixed[0]+s,fixed[1],fixed[2]],a:0};if(s<L+Math.PI*r){const a=(s-L)/r;return {p:[b+r*Math.sin(a),fixed[1]+r*(1-Math.cos(a)),fixed[2]],a};}return {p:[b-(s-L-Math.PI*r),fixed[1]+2*r,fixed[2]],a:Math.PI};}
const summaries=[],checks=[];
for(const recipe of config.recipes){const record=compileOrder(base,recipe),oldRecord=compileOrder(oldBase,recipe),frames=record.trajectory,anim=g.animations.find(x=>x.name==='siparis_birlesik_'+recipe.id);if(!anim)throw Error('Missing order');
 const oldBegin=oldRecord.trajectory.find(f=>f.stage==='Kutu · duvardan uzak koridora çek').time_s,newBegin=frames.find(f=>f.stage==='Kutu · açık dönüş için yataktan uzaklaştır').time_s;
 // The old begin stage starts one frame after the preserved lift pose.
 const oldAnchor=oldBegin-(oldBase.trajectory[plan.begin_index].time_s-plan.old_begin_s),newEnd=oldAnchor+(plan.new_end_s-plan.old_begin_s),oldEnd=oldAnchor+(plan.old_end_s-plan.old_begin_s),shift=newEnd-oldEnd;
 const remap=t=>t<=oldAnchor?t:t>=oldEnd?t+shift:oldAnchor+(t-oldAnchor)*(newEnd-oldAnchor)/(oldEnd-oldAnchor);
 const times=acc(frames.map(f=>f.time_s),1),matrices=frames.map(f=>rig.matrices(f.state.q,f.state.rail,f.state.jaw)),timeMap=new Map(),samplers=[],channels=[];
 for(const ch of anim.channels){const n=g.nodes[ch.target.node],name=n.name,sm=anim.samplers[ch.sampler];let vals=null,size=ch.target.path==='rotation'?4:3;
  if(bodyNames.has(name)){const b=bodyNames.get(name),out=[],previous=[];for(const w of matrices){const v=trs(M(w[b]));let q=v.q;if(previous.length&&q.reduce((s,x,i)=>s+x*previous[i],0)<0)q=q.map(x=>-x);out.push(...(ch.target.path==='translation'?v.p:q));previous.splice(0,4,...q);}vals=out;}
  else if(/^ROBOT25_ZINCIR_LINK_\d+$/.test(name)){const k=+name.split('_').at(-1);vals=frames.flatMap(f=>{const p=chain(k,f.state.rail);return ch.target.path==='translation'?p.p:[0,0,Math.sin(p.a/2),Math.cos(p.a/2)];});}
  else if(name==='ROBOT25_PRODUCT_Box'&&ch.target.path!=='scale'){vals=frames.flatMap(f=>{const pos=f.carrying==='Box'&&f.product?f.product:f.placed.Box||[4.6591115,1.0051,-.2060135];if(ch.target.path==='translation')return pos;let yaw=0;if(f.carrying==='Box'){const m=C.clone().multiply(M(rig.tcp(f.state.q,f.state.rail,f.state.jaw)));yaw=Math.atan2(m.elements[8],m.elements[10]);}return [0,Math.sin(yaw/2),0,Math.cos(yaw/2)];});}
  let sample;if(vals){sample={input:times,output:acc(vals,size),interpolation:sm.interpolation||'LINEAR'};}else{if(!timeMap.has(sm.input))timeMap.set(sm.input,acc(values(sm.input).map(remap),1));sample={...sm,input:timeMap.get(sm.input)};}
  channels.push({...ch,sampler:samplers.length});samplers.push(sample);
 }
 anim.samplers=samplers;anim.channels=channels;anim.extras={...anim.extras,box_turn_version:28,ideal_grasp:true,modified_turn_collision_checked:true,full_order_collision_certified:false};
 const stages=frames.filter((f,i)=>!i||f.stage!==frames[i-1].stage).map(f=>({t:f.time_s,ad:f.stage,not_:'Kayıtlı robot hareketi · ideal tutuş.'}));
 const old=oldManifest.orders.find(x=>x.recipe===recipe.id);summaries.push({...old,sure:frames.at(-1).time_s,stages,adim:[...record.events.filter(e=>e.time_s!==null).map(e=>({t:e.time_s,ad:e.name,not_:'Makine/robot eşgüdüm kaydı.'})),...stages].sort((a,b)=>a.t-b.t),gate:record.gate,robot_frames:frames.length});
 checks.push({recipe:recipe.id,old_anchor_s:oldAnchor,new_anchor_s:oldAnchor,new_end_s:newEnd,shift_s:shift,frames:frames.length,machine_cycle_before_box_unchanged:true});
}
if(offset%4)chunks.push(Buffer.alloc(pad(offset)-offset));const outBin=Buffer.concat(chunks);g.buffers[0].byteLength=outBin.length;g.asset.generator='AUTOKITCH v28 fixed-rail open-side box turn';g.scenes[g.scene||0].extras.boxTurn={version:28,source_sha256:sha(raw)};
const j0=Buffer.from(JSON.stringify(g)),jb=Buffer.concat([j0,Buffer.alloc(pad(j0.length)-j0.length,32)]),h=Buffer.alloc(20),bh=Buffer.alloc(8);h.writeUInt32LE(0x46546c67,0);h.writeUInt32LE(2,4);h.writeUInt32LE(28+jb.length+outBin.length,8);h.writeUInt32LE(jb.length,12);h.writeUInt32LE(0x4e4f534a,16);bh.writeUInt32LE(outBin.length,0);bh.writeUInt32LE(0x004e4942,4);const out=Buffer.concat([h,jb,bh,outBin]),zip=zlib.gzipSync(out,{level:9});
fs.writeFileSync('_local/codex_robot_v28/combined_meshopt.glb',out);fs.writeFileSync(A+'hat3_robot_v28.glb.gz',zip);if(process.argv[3]){fs.mkdirSync(path.dirname(process.argv[3]),{recursive:true});fs.writeFileSync(process.argv[3],out);}
const report={version:28,geometry_binary_prefix_unchanged:outBin.subarray(0,bin.length).equals(bin),nodes_unchanged:JSON.stringify(g.nodes)===JSON.stringify(original.nodes),meshes_unchanged:JSON.stringify(g.meshes)===JSON.stringify(original.meshes),native_machine_6_clips_unchanged:JSON.stringify(g.animations.slice(0,6))===JSON.stringify(original.animations.slice(0,6)),integrated_clips:checks,raw_web_sha256:sha(out),raw_web_bytes:out.length,gzip_sha256:sha(zip),gzip_bytes:zip.length,source_sha256:sha(raw)};
report.passed=report.geometry_binary_prefix_unchanged&&report.nodes_unchanged&&report.meshes_unchanged&&report.native_machine_6_clips_unchanged;
if(!report.passed)throw Error('Original scene changed');
fs.writeFileSync(A+'manifest.json',JSON.stringify({...oldManifest,version:28,orders:summaries,raw_web_sha256:report.raw_web_sha256,raw_web_bytes:out.length,gzip_bytes:zip.length,box_turn:plan},null,2));fs.writeFileSync(A+'build_audit.json',JSON.stringify(report,null,2));fs.writeFileSync(A+'workflow_v28.json',JSON.stringify(config,null,2));console.log(JSON.stringify(report));
