import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {TransformControls} from 'three/addons/controls/TransformControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {MeshBVH} from 'three-mesh-bvh';
import {Rig,flat,mul,inv,I} from './rig.js';
import {installScenario} from './scenario.js';
import {layout,installQR} from './qr-layout.js';
import {replaced,removeFrontStops,cableChannel,mountAdapter,boxSupportParts,boxPickupWindow,stationShift} from './scene-adjust.js';
const $=id=>document.getElementById(id),view=$('view'),status=$('status');
const ASSET='../hat3d/robot-main-v1/',KEY='autokitch-main-ur10e-v4-poses';
document.querySelectorAll('button,input,select').forEach(e=>e.disabled=true);
const C=new T.Matrix4().makeRotationX(-Math.PI/2),CI=C.clone().invert();
const matrix=a=>new T.Matrix4().set(...a),rows=m=>[0,1,2,3].flatMap(i=>[0,1,2,3].map(j=>m.elements[4*j+i]));
const scene=new T.Scene();scene.background=new T.Color('#a3adb7');
const camera=new T.PerspectiveCamera(40,1,.015,50);camera.position.set(6,4,7);
const renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.setSize(view.clientWidth,view.clientHeight);view.appendChild(renderer.domElement);
scene.add(new T.HemisphereLight(0xffffff,0x424955,2));const light=new T.DirectionalLight(0xffffff,3);light.position.set(2,6,4);scene.add(light);
const orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(3,1,0);orbit.enableDamping=true;
const target=new T.Object3D();scene.add(target);const gizmo=new TransformControls(camera,renderer.domElement);gizmo.setSize(.8);scene.add(gizmo.getHelper());
gizmo.addEventListener('dragging-changed',e=>{orbit.enabled=!e.value;if(e.value)remember();});
const marker=new T.Mesh(new T.SphereGeometry(.012,12,8),new T.MeshBasicMaterial({color:0xffcb55}));target.add(marker);target.add(new T.AxesHelper(.12));
let rig,robot,machine,bodies={},shapes=[],machineMeshes=[],state={q:[-Math.PI/2,-2,2.2,0,-Math.PI/2,0],rail:2.65,jaw:10},poses={},slot='Başlangıç',history=[],sync=false,collisionTimer=0,lastHits=[],ready=false;
const drawers=new Map(),doorMeshes=[],gates=[];let doorsHidden=false,qrOpen=false,qrTrays={};
let contactProduct=null,contactGroup=[],allowGraspContact=false,stateObserver=null,supportContact=null;
const clone=x=>JSON.parse(JSON.stringify(x));
function remember(){history.push({state:clone(state),slot,poses:clone(poses),drawerState:Object.fromEntries([...drawers].map(([k,d])=>[k,d.open])),qrOpen,qrTrays:clone(qrTrays)});if(history.length>60)history.shift();$('undo').disabled=false;}
function bodyWorld(body){return C.clone().multiply(matrix(rig.matrices(state.q,state.rail,state.jaw)[body]));}
function draw(updateTarget=true){stateObserver?.(state);const w=rig.matrices(state.q,state.rail,state.jaw);for(const [body,obj] of Object.entries(bodies)){if(!w[body])continue;obj.matrix.copy(matrix(w[body]));obj.matrixAutoUpdate=false;}robot.updateMatrixWorld(true);const tcp=rig.tcp(state.q,state.rail,state.jaw);if(updateTarget){sync=true;C.clone().multiply(matrix(tcp)).decompose(target.position,target.quaternion,target.scale);sync=false;}
 document.querySelectorAll('#joints input').forEach((el,i)=>{el.value=state.q[i]*180/Math.PI;$('jval'+i).textContent=(state.q[i]*180/Math.PI).toFixed(1)+'°';});$('rail').value=state.rail;$('rail-value').textContent=(state.rail*1000).toFixed(0)+' mm';$('jaw').value=state.jaw;$('jaw-value').textContent=state.jaw.toFixed(1)+'°';
 status.classList.remove('bad');status.textContent=`UR10e · ${slot}\nUç: ${(tcp[3]*1000).toFixed(0)} / ${(tcp[11]*1000).toFixed(0)} / ${(-tcp[7]*1000).toFixed(0)} mm (makine X/Y/Z)`;scheduleCollision();}
function scheduleCollision(){clearTimeout(collisionTimer);$('hits').textContent='Çakışma denetleniyor…';collisionTimer=setTimeout(checkCollision,180);}
function visible(obj){let p=obj;while(p){if(!p.visible)return false;p=p.parent;}return true;}
function removeDegenerate(g){if(g.userData.degenerateChecked)return;const p=g.attributes.position,idx=g.index,keep=[],tri=new T.Triangle();let removed=0;for(let j=0;j<(idx?idx.count:p.count);j+=3){const ids=[0,1,2].map(k=>idx?idx.getX(j+k):j+k);[tri.a,tri.b,tri.c].forEach((v,k)=>v.fromBufferAttribute(p,ids[k]));if(tri.getArea()>1e-12)keep.push(...ids);else removed++;}if(removed)g.setIndex(keep);g.userData.degenerateChecked=true;g.userData.degenerateRemoved=removed;}
function productIntersects(a,b){if(!a.geometry.boundsTree)a.geometry.boundsTree=new MeshBVH(a.geometry);if(!b.geometry.boundsTree)b.geometry.boundsTree=new MeshBVH(b.geometry);return b.geometry.boundsTree.intersectsGeometry(a.geometry,b.matrixWorld.clone().invert().multiply(a.matrixWorld));}
function checkCollision(){if(!ready)return [];scene.updateMatrixWorld(true);const world=rig.matrices(state.q,state.rail,state.jaw);const meshBoxes=new Map(machineMeshes.map(m=>[m,m.geometry.boundingBox.clone().applyMatrix4(m.matrixWorld)]));const hits=[];const robotShapes=shapes.map(s=>{s.world=C.clone().multiply(matrix(world[s.body]));s.box.copy(s.localBox).applyMatrix4(s.world);return s;});
 for(const a of robotShapes){for(const mesh of machineMeshes){if(contactGroup.includes(mesh)&&allowGraspContact&&a.body.includes('/Gripper/'))continue;if(!visible(mesh)&&!doorMeshes.includes(mesh))continue;const mb=meshBoxes.get(mesh);if(!a.box.intersectsBox(mb))continue;if(!mesh.geometry.boundsTree)mesh.geometry.boundsTree=new MeshBVH(mesh.geometry,{maxLeafTris:12});const relative=a.world.clone().invert().multiply(mesh.matrixWorld);if(a.bvh.intersectsGeometry(mesh.geometry,relative)){hits.push(a.body.split('/').pop()+' ↔ '+mesh.name);if(hits.length>=12)break;}}if(hits.length>=12)break;}
 if(contactProduct&&visible(contactProduct)){const a=contactProduct;if(!a.geometry.boundsTree)a.geometry.boundsTree=new MeshBVH(a.geometry);const box=a.geometry.boundingBox.clone().applyMatrix4(a.matrixWorld);for(const b of machineMeshes){if(contactGroup.includes(b)||!visible(b))continue;if(b.name===supportContact)continue;if(!box.intersectsBox(meshBoxes.get(b)))continue;if(productIntersects(a,b)){hits.push('Ürün ↔ '+b.name);if(hits.length>=12)break;}}}
 for(let i=0;i<robotShapes.length&&hits.length<12;i++)for(let j=i+1;j<robotShapes.length&&hits.length<12;j++){const a=robotShapes[i],b=robotShapes[j];if(a.body===b.body||rig.adjacent.has([a.body,b.body].sort().join('|'))||a.body.includes('/Gripper/')&&b.body.includes('/Gripper/'))continue;if(!a.box.intersectsBox(b.box))continue;if(a.bvh.intersectsGeometry(b.geometry,a.world.clone().invert().multiply(b.world)))hits.push(a.body.split('/').pop()+' ↔ '+b.body.split('/').pop());}
 lastHits=[...new Set(hits)];$('hits').textContent=lastHits.length?lastHits.join('\n'):'Yüzey kesişimi saptanmadı. Hareket/fizik onayı değildir.';if(lastHits.length){status.classList.add('bad');if(!status.textContent.endsWith('\nÇAKIŞMA UYARISI'))status.textContent+='\nÇAKIŞMA UYARISI';}return lastHits;}
gizmo.addEventListener('objectChange',()=>{if(sync||!ready)return;target.updateMatrixWorld(true);const m=rows(CI.clone().multiply(target.matrixWorld)),sol=rig.solve(m,state.rail,state.jaw,state.q);if(sol.valid){state.q=sol.q;draw(false);}else{status.classList.add('bad');status.textContent=`Hedefe erişilemiyor · ${(sol.position*1000).toFixed(1)} mm / ${sol.angle.toFixed(1)}°\nSon geçerli robot pozu korunuyor.`;}});
function setDrawer(key,value){const d=drawers.get(key);if(!d)return;d.open=value;for(const o of d.objects){o.position.copy(o.userData.initialPosition);o.position.z+=value*(o.name.includes('CEKMECE_ARA')?.5:1);}if($('drawer').value===key){$('drawer-open').value=value;$('drawer-value').textContent=(value*1000).toFixed(0)+' mm';}scheduleCollision();}
function setQRTrays(values={}){qrTrays={...values};$('qr-slide').value=values[$('qr-shelf').value]||0;for(const o of machineMeshes){const m=o.name.match(/^QR_V4_tray_(\d\d)$/);if(m){o.position.copy(o.userData.initialPosition);o.position.z-=values[m[1]]||0;}}scheduleCollision();}
function setQR(open){qrOpen=!!open;setQRTrays({...qrTrays,[$('qr-shelf').value]:open?.3:0});}
function loadPose(mode){remember();slot=$('item').value+'_'+mode;const p=poses[slot];state={q:[...p.q],rail:p.rail,jaw:p.jaw};for(const key of drawers.keys())setDrawer(key,0);if(mode==='pick'){const key={Dough:'CEK_K1_lahm_1',Cola:'CEK_K5_ic1_1',Dessert:'CEK_K6_tatli_1'}[$('item').value];if(key)setDrawer(key,.7);}setQR(mode==='place'&&$('item').value!=='Dough');draw();}
function savePose(){checkCollision();target.updateMatrixWorld(true);const actual=rig.tcp(state.q,state.rail,state.jaw),request=rows(CI.clone().multiply(target.matrixWorld));const e=rig.error(state.q,state.rail,state.jaw,request);if(Math.hypot(...e.slice(0,3))>.002||Math.hypot(...e.slice(3))/.35>.5*Math.PI/180){status.textContent='Erişilemeyen hedef kaydedilmedi.';status.classList.add('bad');return false;}poses[slot]={...poses[slot],...clone(state),tcp:[actual[3],actual[7],actual[11]],rotation:[actual.slice(0,3),actual.slice(4,7),actual.slice(8,11)],browser_surface_hits:[...lastHits],saved_in_editor:true};localStorage.setItem(KEY,JSON.stringify(poses));status.textContent=slot+' kaydedildi'+(lastHits.length?' · çakışma uyarısıyla':'');return true;}
function validate(p){return p&&Object.keys(poses).every(k=>p[k]&&p[k].q?.length===6&&p[k].q.every(Number.isFinite)&&p[k].q.every(x=>Math.abs(x)<=2*Math.PI)&&Number.isFinite(p[k].rail)&&p[k].rail>=rig.data.rail_min&&p[k].rail<=rig.data.rail_max&&Number.isFinite(p[k].jaw)&&p[k].jaw>=0&&p[k].jaw<=45);}
const labels=['Taban','Omuz','Dirsek','Bilek 1','Bilek 2','Bilek 3'];$('joints').innerHTML=labels.map((n,i)=>`<label>${n}<output id="jval${i}"></output></label><input type="range" aria-label="${n}" min="-360" max="360" step=".1" data-j="${i}">`).join('');
for(const input of document.querySelectorAll('#joints input')){input.disabled=true;input.addEventListener('pointerdown',remember);input.addEventListener('input',()=>{state.q[+input.dataset.j]=+input.value*Math.PI/180;draw();});}
for(const input of document.querySelectorAll('input[type=range]'))input.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(e.key)&&!e.repeat)remember();});
$('drawer-open').addEventListener('pointerdown',remember);
for(const k of ['rail','jaw']){$(k).addEventListener('pointerdown',remember);$(k).oninput=()=>{state[k]=+$(k).value;draw();};}
$('tcp').onclick=()=>{gizmo.attach(target);$('tcp').classList.add('active');};$('move').onclick=()=>{gizmo.setMode('translate');gizmo.attach(target);};$('rotate').onclick=()=>{gizmo.setMode('rotate');gizmo.attach(target);};$('orbit').onclick=()=>{gizmo.detach();$('tcp').classList.remove('active');};
$('undo').onclick=()=>{const h=history.pop();if(!h)return;state=h.state;slot=h.slot;poses=h.poses;for(const [k,v] of Object.entries(h.drawerState||{}))setDrawer(k,v);setQRTrays(h.qrTrays||{});draw();$('undo').disabled=!history.length;};$('home').onclick=()=>{remember();state={q:[-Math.PI/2,-2,2.2,0,-Math.PI/2,0],rail:2.65,jaw:10};slot='Başlangıç';for(const k of drawers.keys())setDrawer(k,0);setQR(false);draw();};
$('pick').onclick=()=>loadPose('pick');$('place').onclick=()=>loadPose('place');$('save').onclick=()=>{if(!poses[slot]){status.textContent='Önce bir alma/bırakma pozu seç.';return;}savePose();};
$('focus').onclick=()=>{const p=target.position.clone();orbit.target.copy(p);camera.position.copy(p).add(new T.Vector3(1,.65,1));};$('all').onclick=()=>{orbit.target.set(3,1,0);camera.position.set(6,4,7);};
$('drawer').onchange=()=>{const d=drawers.get($('drawer').value);$('drawer-open').value=d?.open||0;$('drawer-value').textContent=((d?.open||0)*1000).toFixed(0)+' mm';};$('drawer-open').oninput=()=>setDrawer($('drawer').value,+$('drawer-open').value);
$('qr-shelf').onchange=()=>{$('qr-slide').value=qrTrays[$('qr-shelf').value]||0;};$('qr-slide').oninput=()=>setQRTrays({...qrTrays,[$('qr-shelf').value]:+$('qr-slide').value});
$('doors').onclick=()=>{doorsHidden=!doorsHidden;for(const o of doorMeshes)o.visible=!doorsHidden;scheduleCollision();};$('qr').onclick=()=>setQR(!qrOpen);
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({schema:'autokitch-main-ur10e-v1',machine_base:rig.data.machine_base_commit,tip_sha256:rig.data.tip_sha256,poses},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='UR10e-montaj-pozlari.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),500);};
$('import').onclick=()=>$('file').click();$('file').onchange=async()=>{try{const data=JSON.parse(await $('file').files[0].text());if(data.schema!=='autokitch-main-ur10e-v1'||data.tip_sha256!==rig.data.tip_sha256||!validate(data.poses))throw Error('Uyumsuz veya bozuk poz dosyası');remember();poses=data.poses;localStorage.setItem(KEY,JSON.stringify(poses));status.textContent='Poz dosyası açıldı. Bir alma/bırakma pozu seç.';}catch(e){status.textContent=e.message;status.classList.add('bad');}};
window.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();$('undo').click();return;}if(e.target.matches('input,select'))return;if(e.key.toLowerCase()==='w')$('move').click();else if(e.key.toLowerCase()==='e')$('rotate').click();else if(e.key==='Escape')$('orbit').click();});
const ray=new T.Raycaster(),mouse=new T.Vector2();let down=null;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>4||gizmo.dragging)return;const rect=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(mouse,camera);const hit=ray.intersectObject(robot,true)[0];if(hit){$('tcp').click();status.textContent='Robot seçildi · uç gizmosu açık. Eklem açıları sağ panelden kontrol edilir.';}});
new ResizeObserver(()=>{camera.aspect=view.clientWidth/view.clientHeight;camera.updateProjectionMatrix();renderer.setSize(view.clientWidth,view.clientHeight);}).observe(view);
async function init(){const loader=new GLTFLoader(),assembly=await fetch(ASSET+'assembly.json').then(r=>r.json());const [data,defaults,collision,ref,mg,rg]=await Promise.all([fetch(ASSET+'rig.json').then(r=>r.json()),fetch(ASSET+'poses.json').then(r=>r.json()),fetch(ASSET+'collision.json').then(r=>r.json()),fetch(ASSET+'fk_reference.json').then(r=>r.json()),loader.loadAsync(ASSET+assembly.machine_model),loader.loadAsync(ASSET+assembly.robot_model)]);rig=new Rig(data,{mountForward:assembly.mount_forward_m||0});poses=defaults;try{const saved=JSON.parse(localStorage.getItem(KEY));if(validate(saved))poses=saved;}catch{}machine=mg.scene;scene.add(machine);robot=rg.scene;robot.rotation.x=-Math.PI/2;scene.add(robot);
 for(const [body,name] of Object.entries(data.body_nodes)){const obj=robot.getObjectByName(name);if(obj)bodies[body]=obj;}
 machine.updateMatrixWorld(true);machine.traverse(o=>{if(!o.isMesh)return;if(replaced(o.name)){o.visible=false;return;}removeFrontStops(T,o.geometry,o.matrixWorld,o.name);boxPickupWindow(T,o.geometry,o.matrixWorld,o.name);if(o.name.endsWith('__ACICI'))o.position.y+=.03;o.position.z+=stationShift(o.name);removeDegenerate(o.geometry);if(o.name==='ROBOT_1'||o.name==='ROBOT_1_KOL'){o.visible=false;return;}o.geometry.computeBoundingBox();o.userData.initialPosition=o.position.clone();o.userData.initialMatrix=o.matrix.clone();machineMeshes.push(o);if(o.name.includes('on_seffaf')&&!o.name.includes('CEK_')&&!o.name.startsWith('QR_'))doorMeshes.push(o);if(o.name.includes('GOZ_20_KAPAK')||o.name.includes('GOZ_21_KAPAK'))gates.push(o);const d=o.name.match(/^(CEK_K\d+_[^_]+_\d+)__/);if(d&&o.name.includes('CEKMECE')){if(!drawers.has(d[1]))drawers.set(d[1],{objects:[],open:0});drawers.get(d[1]).objects.push(o);}});
 $('drawer').innerHTML=[...drawers.keys()].map(k=>`<option value="${k}">${k}</option>`).join('');$('drawer').dispatchEvent(new Event('change'));
 shapes=collision.map(s=>{const geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.Float32BufferAttribute(s.vertices.flat(),3));geometry.setIndex(s.faces.flat());removeDegenerate(geometry);geometry.computeBoundingBox();return {...s,geometry,bvh:new MeshBVH(geometry),box:new T.Box3(),localBox:geometry.boundingBox.clone()};});
 const adapterGeom=new T.BoxGeometry(...mountAdapter.max.map((v,i)=>v-mountAdapter.min[i]));adapterGeom.translate(...mountAdapter.min.map((v,i)=>(v+mountAdapter.max[i])/2));adapterGeom.computeBoundingBox();const adapterMesh=new T.Mesh(adapterGeom,new T.MeshStandardMaterial({color:0x5fc5d1,metalness:.45,roughness:.5}));adapterMesh.name=mountAdapter.name;bodies['/World/RailSystem/Carriage'].add(adapterMesh);shapes.push({body:'/World/RailSystem/Carriage',geometry:adapterGeom,bvh:new MeshBVH(adapterGeom),box:new T.Box3(),localBox:adapterGeom.boundingBox.clone()});
 const regressions=ref.map(r=>{const actual=rig.tcp(r.q,r.rail,r.jaw),e=Math.hypot(actual[3]-r.tcp[0],actual[7]-r.tcp[1]+(assembly.mount_forward_m||0),actual[11]-r.tcp[2]);let rot=0;for(let i=0;i<3;i++)for(let j=0;j<3;j++)rot=Math.max(rot,Math.abs(actual[4*i+j]-r.rotation[i][j]));return {key:r.key,position_error_m:e,rotation_element_error:rot,passed:e<1e-8&&rot<1e-8};});if(regressions.some(r=>!r.passed))throw Error('USD ↔ tarayıcı eklem doğrulaması geçmedi');
 $('qr-shelf').innerHTML=Array.from({length:3},(_,r)=>Array.from({length:4},(_,c)=>'<option value="'+r+c+'">'+(r+1)+'. sıra · '+(c+1)+'. göz</option>').join('')).join('');const reach=await fetch(ASSET+'qr_reach.json').then(r=>r.json());$('qr-reach').textContent=reach.all_clear?'12/12 raf · üç ürün için 36 giriş/çıkış denetimi geçti.':'Raf erişiminde açıklar var.';try{const record=await fetch(ASSET+assembly.scenario_record).then(r=>r.json());state=clone(record.trajectory[0].state);}catch{}
 installQR(T,scene,machineMeshes);for(const m of machineMeshes.filter(m=>m.name.startsWith('QR_V4_')))m.userData.initialPosition=m.position.clone();const cg=new T.BoxGeometry(...cableChannel.max.map((v,i)=>v-cableChannel.min[i]));cg.computeBoundingBox();const cm=new T.Mesh(cg,new T.MeshStandardMaterial({color:0x60717e,metalness:.45,roughness:.6}));cm.name=cableChannel.name;cm.position.set(...cableChannel.min.map((v,i)=>(v+cableChannel.max[i])/2));scene.add(cm);machineMeshes.push(cm);for(const s of shapes)s.geometry.boundsTree=s.bvh;ready=true;document.querySelectorAll('button,input,select').forEach(e=>e.disabled=false);$('undo').disabled=true;$('loading').remove();draw();gizmo.attach(target);window.ROBOT_MAIN={rig,regressions,get state(){return clone(state);},get poses(){return clone(poses);},setState:s=>{state=clone(s);draw();},loadPose,savePose,checkCollision,get hits(){return [...lastHits];},get bodyCount(){return Object.keys(bodies).length;},get machineMeshCount(){return machineMeshes.length;}};
 installScenario({T,scene,machineMeshes,rig,poses,setSlot:key=>{slot=key;},observe:fn=>{stateObserver=fn;},record:assembly.scenario_record,setDrawer,setQR,setQRTrays,gizmo,target,orbit,readState:()=>clone(state),writeState:s=>{state=clone(s);slot='Pide siparişi';draw();},checkCollision,contact:(m,allowed,support=null)=>{supportContact=support;contactGroup=Array.isArray(m)?m:m?[m]:[];contactProduct=contactGroup[0]||null;allowGraspContact=allowed;}});
 console.info('ROBOT_MAIN_READY',JSON.stringify({bodies:Object.keys(bodies).length,machine_meshes:machineMeshes.length,regressions}));}
init().catch(e=>{console.error(e);$('loading').textContent='Yükleme hatası: '+e.message;status.textContent='Robot kontrolü başlatılamadı.';});
renderer.setAnimationLoop(()=>{orbit.update();renderer.render(scene,camera);});
