import {compileOrder,frameAt,planDemand,validateMotionContract} from './workflow-v16.js';
import {scenarioOrders,defaultDemand} from './demand-v16.js';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {TransformControls} from 'three/addons/controls/TransformControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {Rig} from './rig.js';
document.querySelectorAll('button,input,select').forEach(e=>e.disabled=true);const $=id=>document.getElementById(id),A='../hat3d/robot-main-v1/',scene=new T.Scene();scene.background=new T.Color(0xdce3e8);
const camera=new T.PerspectiveCamera(40,1,.02,30),renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(1);$('view').appendChild(renderer.domElement);const orbit=new OrbitControls(camera,renderer.domElement);camera.position.set(3,5,8.5);orbit.target.set(3.1,.9,.3);orbit.update();scene.add(new T.HemisphereLight(0xffffff,0x6b7680,3));const light=new T.DirectionalLight(0xffffff,2);light.position.set(3,6,4);scene.add(light);const C=new T.Matrix4().makeRotationX(-Math.PI/2),CI=C.clone().invert();
let baseRecord,workflowConfig;let clipStart=0,clipEnd=null,railRecord,playing=false,playTime=0,lastTime=0,rigRail,railCable,railMarker,railOrders=new T.Group(),sources,rig,robot,bodies={},data,reach,high,poses,state,qr=new T.Group(),orders=new T.Group(),stock=new T.Group(),trayMeshes=[],pickGroups={},current=null,stage='QR bırakma pozu';scene.add(qr,orders,stock,railOrders);
const target=new T.Object3D();scene.add(target);const gizmo=new TransformControls(camera,renderer.domElement);scene.add(gizmo.getHelper());gizmo.addEventListener('dragging-changed',e=>orbit.enabled=!e.value);gizmo.addEventListener('objectChange',()=>{if(!rig)return;target.updateMatrixWorld();const m=CI.clone().multiply(target.matrixWorld),r=[0,1,2,3].flatMap(i=>[0,1,2,3].map(j=>m.elements[j*4+i])),s=rig.solve(r,state.rail,state.jaw,state.q);if(s.valid){state.q=s.q;draw(false);$('status').textContent='Elle düzenlenen poz · erişim geçerli; çakışma yeniden denetlenmedi.';}else $('status').textContent='Bu hedefe erişilemiyor; son robot pozu korundu.';});
const mat=c=>new T.MeshStandardMaterial({color:c,metalness:.15,roughness:.8});
function geometry(p){const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(p.positions,3));g.setIndex(p.indices);g.computeVertexNormals();return g;}
function rect(min,max,color,parent=scene){const m=new T.Mesh(new T.BoxGeometry(...max.map((v,i)=>v-min[i])),mat(color));m.position.set(...min.map((v,i)=>(v+max[i])/2));if(parent===qr&&color!==0xadc5ce){m.material.transparent=true;m.material.opacity=.18;m.material.depthWrite=false;}parent.add(m);return m;}
function draw(sync=true){$('jaw').value=state.jaw;const w=rig.matrices(state.q,state.rail,state.jaw);for(const [body,o] of Object.entries(bodies)){o.matrix.set(...w[body]);o.matrixAutoUpdate=false;}robot.updateMatrixWorld(true);if(sync){C.clone().multiply(new T.Matrix4().set(...rig.tcp(state.q,state.rail,state.jaw))).decompose(target.position,target.quaternion,target.scale);}render();}
function render(){renderer.render(scene,camera);}orbit.addEventListener('change',render);gizmo.addEventListener('change',render);
function buildBay(f){qr.clear();orders.clear();for(const p of reach.parts){rect(p.min,p.max,p.color,qr);}const column=+$('column').value;for(const row of reach.results){for(const task of row.tasks||[]){if(!task.product)continue;const group=new T.Group();group.name=row.floor_mm===Math.round(f*1000)&&row.column===column?task.key:'stock_'+row.floor_mm+'_'+row.column+'_'+task.key;const m=task.key==='Box'?new T.Mesh(new T.BoxGeometry(.32,.045,.32),mat(0xc4a26a)):new T.Mesh(new T.CylinderGeometry(task.key==='Cola'?.033:.0475,task.key==='Cola'?.033:.0475,task.key==='Cola'?.115:.060,20),mat(task.key==='Cola'?0xb84744:0xd4b99a));if(group.name.startsWith('stock_')||['Dessert','Cola','Box'].indexOf(task.key)>['Dessert','Cola','Box'].indexOf($('product').value)){m.material.transparent=true;m.material.opacity=.22;m.material.depthWrite=false;}group.add(m);group.position.set(...task.product);orders.add(group);}}render();}
function select(){playing=false;lastTime=0;railOrders.visible=false;qr.visible=true;orders.visible=true;if($('product').value==='Dough'){$('drawer').value=0;$('drawer').dispatchEvent(new Event('input'));current={source:true,key:'Dough',sequence:sources.results.find(r=>r.key==='Dough_place').path};const p=poses.Dough_place;state={q:p.q,rail:p.rail,jaw:p.jaw};draw();$('status').textContent='Hamur · mevcut tabla merkezi · kaynak dizilimi korunuyor';return;}$('drawer').value=0;$('drawer').dispatchEvent(new Event('input'));const row=reach.results.find(r=>r.column===+$('column').value&&r.floor_mm===+$('height').value);if(!row){$('status').textContent='Bu gözün denetimi henüz tamamlanmadı; son robot pozu korunuyor.';return;}const task=row.tasks.find(t=>t.key===$('product').value);current=task;buildBay(row.floor_mm/1000);$('result').textContent=row.passed?'Üç ürün için giriş/bırakma kontrolü geçti.':'Bu yükseklik tüm sipariş için geçmedi: '+row.tasks.filter(t=>!t.passed).map(t=>t.key).join(', ');$('path').value=0;if(task?.passed){state=structuredClone(task.state);draw();$('status').textContent=row.floor_mm+' mm sabit raf · '+task.key+' · kayıtlı bırakma pozu';}else $('status').textContent='Bu ürün için doğrulanmış poz yok; önceki robot pozu korunuyor.';}
$('path-mode').onchange=()=>{$('path').dispatchEvent(new Event('input'));};$('column').onchange=select;$('height').onchange=select;$('product').onchange=select;$('path').oninput=()=>{if(!current?.sequence)return;if(current.source){const i=Math.round(+$('path').value*(current.sequence.length-1)/100),f=current.sequence[i];state=structuredClone(f.state);for(const m of trayMeshes){m.position.copy(m.userData.closed);const d=m.name.match(/^(CEK_K\d+_[^_]+_\d+)__/);if(d&&m.name.includes('CEKMECE'))m.position.z+=(f.drawers[d[1]]||0)*(m.name.includes('CEKMECE_ARA')?.5:1);}for(const [k,g]of Object.entries(pickGroups)){g.position.copy(g.userData.closed);g.position.z=g.userData.closedZ+(f.drawers[{Dough:'CEK_K1_lahm_1',Cola:'CEK_K5_ic1_1',Dessert:'CEK_K6_tatli_1'}[k]]||0);if(f.placed?.[k]&&k===current.key)g.position.set(...f.placed[k]);if(f.carrying===k){const m=rig.tcp(state.q,state.rail,state.jaw);g.position.set(m[3]+f.offset[0],m[11]+f.offset[1],-m[7]+f.offset[2]);}}draw();$('status').textContent=f.stage+' · yerel yol '+i+'/'+(current.sequence.length-1);return;}const path=$('path-mode').value==='exit'?current.exit:current.sequence;if(!path)return;const i=Math.round(+$('path').value*(path.length-1)/100),frame=path[i];state=structuredClone(frame.state);const g=orders.children.find(g=>g.name===current.key);if(g)g.position.set(...frame.product);draw();$('status').textContent=current.key+' · örneklenmiş giriş/çıkış '+i+'/'+(path.length-1)+' · ideal tutuş';};
$('cabinet').onclick=()=>{const x=(reach.columns_x[0]+reach.columns_x.at(-1)+reach.config.width)/2;camera.position.set(x+1.2,2.4,reach.config.front-4.6);orbit.target.set(x,.9,reach.config.front+.15);orbit.update();render();};$('all').onclick=()=>{camera.position.set(3,5,8.5);orbit.target.set(3.1,.9,.3);orbit.update();render();};$('focus').onclick=()=>{const x=reach.columns_x[+$('column').value]+reach.config.width/2,y=+$('height').value/1000,z=reach.config.front+reach.config.depth/2;camera.position.set(x+.8,y+1.0,z-1.25);orbit.target.set(x,y+.10,z);orbit.update();render();};$('move').onclick=()=>{gizmo.setMode('translate');gizmo.attach(target);};$('rotate').onclick=()=>{gizmo.setMode('rotate');gizmo.attach(target);};$('hide').onclick=()=>{gizmo.detach();render();};$('jaw').oninput=()=>{state.jaw=+$('jaw').value;draw();};$('drawer').oninput=()=>{for(const m of trayMeshes){m.position.copy(m.userData.closed);m.position.z+=+$('drawer').value;}for(const [k,g]of Object.entries(pickGroups)){g.position.copy(g.userData.closed);g.position.z=g.userData.closedZ+(k==='Box'?0:+$('drawer').value);}render();};
$('pick').onclick=()=>{playing=false;lastTime=0;const k=$('product').value;if(k==='Box'||k==='Cola'){showGrip(k);return;}const p=poses[k+'_pick'];current={source:true,key:k,sequence:sources.results.find(r=>r.key===k+'_pick').path};state={q:p.q,rail:p.rail,jaw:p.jaw};$('drawer').value=.7;const d={Dough:'CEK_K1_lahm_1',Cola:'CEK_K5_ic1_1',Dessert:'CEK_K6_tatli_1'}[k];for(const m of trayMeshes){m.position.copy(m.userData.closed);if(d&&m.name.startsWith(d+'__')&&m.name.includes('CEKMECE'))m.position.z+=m.name.includes('CEKMECE_ARA')?.35:.7;}for(const [key,g]of Object.entries(pickGroups)){g.position.copy(g.userData.closed);g.position.z=g.userData.closedZ+(key===k&&key!=='Box'?.7:0);}draw();$('status').textContent='Kaynak alma pozu · '+k+' · sabit stok dizilimi';};$('place').onclick=select;
$('high').onclick=()=>{if(!high?.empty)return;current=null;qr.visible=false;orders.visible=false;state=structuredClone(high.empty.state);draw();const p=high.empty.wrist_m;camera.position.set(p[0]+4,p[1]+1,p[2]+6);orbit.target.set(p[0],.9,p[2]);orbit.update();$('status').textContent='Boş kol · bilek merkezi '+high.empty.height_mm.toFixed(1)+' mm · makine ve kendi gövdesiyle kesişim yok. Raf/ürün bırakma doğrulaması değildir.';$('result').textContent='1640 mm raf: sipariş geçmedi. Bu gösterim yalnız boş kolun 1644,7 mm bilek pozudur; QR gizlendi.';render();};
new ResizeObserver(()=>{renderer.setSize($('view').clientWidth,$('view').clientHeight);camera.aspect=$('view').clientWidth/$('view').clientHeight;camera.updateProjectionMatrix();render();}).observe($('view'));
async function init(){const [r,p,l,h,model,hr,src]=await Promise.all([fetch(A+'rig.json').then(r=>r.json()),fetch(A+'poses_v12.json').then(r=>r.json()),fetch(A+'light_scene_v14.json').then(r=>r.json()),fetch(A+'qr_grid_v13.json').then(r=>r.json()),new GLTFLoader().loadAsync(A+'ur10e_short.glb'),fetch(A+'high_reach_v6.json').then(r=>r.json()),fetch(A+'source_dense_v12.json').then(r=>r.json())]);sources=src;rig=new Rig(r,{mountForward:.1,railForward:h.rail_shift_mm/1000});poses=p;data=l;reach=h;high=hr;robot=model.scene;robot.rotation.x=-Math.PI/2;scene.add(robot);for(const [body,name] of Object.entries(r.body_nodes))bodies[body]=robot.getObjectByName(name);for(const p of l.meshes){const m=new T.Mesh(geometry(p),mat(/hamur|old_product/.test(p.name)?0xe2d5ad:/icecek/.test(p.name)?0xad4141:0xafc1ca));m.name=p.name;new T.Matrix4().fromArray(p.matrix).decompose(m.position,m.quaternion,m.scale);m.userData.closed=m.position.clone();stock.add(m);if(p.name.startsWith('CEK_'))trayMeshes.push(m);}for(const [k,p] of Object.entries(l.stockProducts||{})){const g=new T.Group();for(const a of p.parts)g.add(new T.Mesh(geometry(a),mat(k==='Dough'?0xe2d5ad:k==='Cola'?0xad4141:0xc6b69c)));g.position.set(...p.centre);g.userData.closedZ=g.position.z;g.userData.closed=g.position.clone();stock.add(g);pickGroups[k]=g;}const sourceBox=new T.Mesh(new T.BoxGeometry(.32,.045,.32),mat(0xc4a26a)),bp=p.Box_pick.product;sourceBox.position.set(bp[0][3],bp[2][3],-bp[1][3]);sourceBox.userData.closedZ=sourceBox.position.z;sourceBox.userData.closed=sourceBox.position.clone();pickGroups.Box=sourceBox;stock.add(sourceBox);for(const b of l.limits){const g=new T.EdgesGeometry(new T.BoxGeometry(...b.max.map((v,i)=>v-b.min[i]))),line=new T.LineSegments(g,new T.LineDashedMaterial({color:b.name.includes('TEZGAH')?0xc47b3b:0x647683,dashSize:.04,gapSize:.04}));line.position.set(...b.min.map((v,i)=>(v+b.max[i])/2));line.computeLineDistances();scene.add(line);}
rigRail=rect([.936,.04,.24+h.rail_shift_mm/1000],[5.1,.075,.48+h.rail_shift_mm/1000],0x788893);railCable=rect([.936,.012,.495+h.rail_shift_mm/1000],[5.1,.055,.565+h.rail_shift_mm/1000],0x546673);$('height').innerHTML=h.floors_mm.map(mm=>`<option value="${mm}">${mm} mm · ${h.results.filter(v=>v.floor_mm===mm).length===h.columns_x.length&&h.results.filter(v=>v.floor_mm===mm).every(v=>v.passed)?'geçti':'eksik denetim'}</option>`).join('');$('height').value=Math.max(...h.results.filter(r=>r.column===2).map(r=>r.floor_mm));$('product').value='Box';state={q:p.Cola_place.q,rail:p.Cola_place.rail,jaw:p.Cola_place.jaw};$('summary').textContent='Makine: 4494 × 909 mm; açıcı 700 mm. Kesikli istasyon sınırları düzeltildi; yeni istasyon yok. QR sağda, makinenin sağ ucuna hizalı. 3 sütun × 4 raf = 12 sipariş gözü; dolap genişliği 1473 mm (487 mm daraldı). Raf tabanları '+h.floors_mm.join(' / ')+' mm; net göz yüksekliği 250 mm, dolap üstü '+h.top_mm+' mm. QR yüzü–makine önü '+h.machine_front_to_qr_face_mm+' mm. Yeni alt raf 588 mm: insan erişim rahatlığı ayrıca değerlendirilmeli. Ray mesafesi değişmedi. Kaynak alma ve QR giriş/çıkışları ayrı denetlendi; tam sipariş yolu henüz birleştirilmedi. İdeal tutuş; örneklenmiş çarpışma kontrolü.';$('stats').textContent=l.stats.retained_meshes+'/'+l.stats.original_meshes+' makine ağı · gölgeler kapalı · yalnız değişiklikte çizim';select();document.querySelectorAll('button,input,select').forEach(e=>e.disabled=false);$('high').disabled=true;$('high').textContent='Eski boş kol pozu · bu yerleşimde kapalı';$('loading').remove();await loadGripDemo(); await loadRailAnimation();}
init().catch(e=>$('loading').textContent='Yükleme hatası: '+e.message);

function railFrame(index){const f=railRecord.trajectory[index];state=structuredClone(f.state);$('drawer').value=f.drawers.CEK_K1_lahm_1||0;current=null;gizmo.detach();qr.visible=true;orders.visible=false;railOrders.visible=true;for(const m of trayMeshes){m.position.copy(m.userData.closed);const d=m.name.match(/^(CEK_K\d+_[^_]+_\d+)__/);if(d)m.position.z+=(f.drawers[d[1]]||0)*(m.name.includes('CEKMECE_ARA')?.5:1);}for(const [k,g]of Object.entries(pickGroups)){g.position.copy(g.userData.closed);g.quaternion.identity();const d={Dough:'CEK_K1_lahm_1',Cola:'CEK_K5_ic1_1',Dessert:'CEK_K6_tatli_1'}[k];g.position.z+=(f.drawers[d]||0);if(f.placed[k])g.position.set(...f.placed[k]);if(f.carrying===k&&f.product){g.position.set(...f.product);if(k==='Box'){const m=C.clone().multiply(new T.Matrix4().set(...rig.tcp(state.q,state.rail,state.jaw)));g.rotation.y=Math.atan2(m.elements[8],m.elements[10]);}}}draw();$('rail-time').value=Math.round(index/(railRecord.trajectory.length-1)*1000);$('rail-stage').textContent=f.stage+' · araba X'+Math.round(state.rail*1000)+' mm · '+f.time_s.toFixed(1)+' s';if(railRecord.events){const events=railRecord.events.filter(e=>e.time_s!==null&&e.time_s<=f.time_s);$('machine-state').textContent=railRecord.recipe.name+' · '+(events.at(-1)?.name||'Sipariş alındı');const consumed=railRecord.events.find(e=>e.name.startsWith('AÇICI'));pickGroups.Dough.visible=!(f.placed.Dough&&consumed&&f.time_s>consumed.time_s+4);pickGroups.Box.visible=f.carrying==='Box'||!!f.placed.Box||(railRecord.summary.machine_ready_s!==null&&f.time_s>=railRecord.summary.machine_ready_s);}$('status').textContent=f.stage;}
async function loadRailAnimation(){const fresh=await fetch(A+'qr_delivery_v15.json').then(r=>r.json());reach.results=reach.results.map(r=>r.column===2&&r.floor_mm===850?{...r,...fresh.result}:r);baseRecord=await fetch(A+'order_v16.json').then(r=>r.json());workflowConfig=await fetch(A+'workflow_v16.json').then(r=>r.json());const errors=validateMotionContract(baseRecord,workflowConfig);if(errors.length)throw Error(errors.join(', '));$('recipe').innerHTML=workflowConfig.recipes.map(r=>'<option value="'+r.id+'">'+r.name+(r.ready==='modelled'?'':' · hazır sinyali')+'</option>').join('');railRecord=compileOrder(baseRecord,workflowConfig.recipes[0]);$('recipe').onchange=compileSelected;compileSelected();const d=railRecord.summary;$('rail-measure').textContent='Bir sipariş · '+d.completed.map(k=>({Dough:'Hamur',Cola:'Kola',Dessert:'Tatlı',Box:'Kutu'}[k])).join(' / ')+' tamamlandı. İdeal tutuş ve rijit ürünler; tam makine, robot gövdesi ve sabit QR ile örneklenmiş çarpışma kontrolü. Gerçek kavrama/kuvvet testi değildir.';
const keys=d.completed,labels={Cola:'Kola → QR',Dessert:'Tatlı → QR',Box:'Kutu → QR',Dough:'Hamur → tabla'};
const options=document.getElementById('order-task');options.innerHTML='<option value="all">Bir sipariş · hepsi</option>'+keys.map(k=>'<option value="'+k+'">'+labels[k]+'</option>').join('');
options.onchange=()=>{playing=false;lastTime=0;const k=options.value;let i=0;if(k!=='all')i=railRecord.trajectory.findIndex(f=>({Cola:/^(Cola|İçecek)/,Dessert:/^(Dessert|Tatlı)/,Box:/^(Box|Kutu)/,Dough:/^(Dough|Hamur|En sol hamur)/}[k]).test(f.stage));i=Math.max(0,i);clipStart=i;clipEnd=null;if(k!=='all'){const re={Cola:/^(Cola|İçecek)/,Dessert:/^(Dessert|Tatlı)/,Box:/^(Box|Kutu)/,Dough:/^(Dough|Hamur|En sol hamur)/},next=railRecord.trajectory.findIndex((f,j)=>j>i&&Object.entries(re).some(([other,r])=>other!==k&&r.test(f.stage)));if(next>i)clipEnd=next-1;}playTime=railRecord.trajectory[i].time_s;railFrame(i);};
$('summary').textContent='Makine ve tabla sabit. 12 gözlü QR sağda. Bu sipariş sağ sütunun 850 mm rafına bırakılıyor: kola arkada, tatlı önde, kutu solda. Kutu, alt parmağın çıkabilmesi için raf üzerinde 25 mm yüksekte açılıp ideal olarak rafa oturtuluyor.';
railFrame(0);$('height').value='850';$('all').click();compileSelected();}
function tickRail(now){if(!playing)return;if(lastTime)playTime+=(now-lastTime)/1000*Number($('playback-speed').value);lastTime=now;const end=clipEnd??railRecord.trajectory.length-1;if(railRecord.gate&&playTime>=railRecord.gate.time_s){playTime=railRecord.gate.time_s;playing=false;lastTime=0;railFrame(railRecord.gate.index);$('status').textContent='Makine hazır sinyali bekleniyor · tarif süresi henüz doğrulanmadı';$('machine-ready').disabled=false;return;}playTime=Math.min(playTime,railRecord.trajectory[end].time_s);const sample=frameAt(railRecord,playTime),index=sample.index;railFrame(index);const a=railRecord.trajectory[index],b=railRecord.trajectory[sample.next],t=sample.mix;state={q:a.state.q.map((q,k)=>q+Math.atan2(Math.sin(b.state.q[k]-q),Math.cos(b.state.q[k]-q))*t),rail:a.state.rail+(b.state.rail-a.state.rail)*t,jaw:a.state.jaw+(b.state.jaw-a.state.jaw)*t};if(a.carrying&&a.carrying===b.carrying&&a.product&&b.product)pickGroups[a.carrying].position.set(...a.product.map((v,k)=>v+(b.product[k]-v)*t));if(a.carrying==='Box'){const m=C.clone().multiply(new T.Matrix4().set(...rig.tcp(state.q,state.rail,state.jaw)));pickGroups.Box.rotation.y=Math.atan2(m.elements[8],m.elements[10]);}draw();if(index===(clipEnd??railRecord.trajectory.length-1)){playing=false;lastTime=0;return;}requestAnimationFrame(tickRail);}
$('rail-play').onclick=()=>{if(!railRecord||playing)return;if(playTime>=railRecord.trajectory[clipEnd??railRecord.trajectory.length-1].time_s)playTime=railRecord.trajectory[clipStart].time_s;playing=true;lastTime=0;requestAnimationFrame(tickRail);};$('rail-pause').onclick=()=>{playing=false;lastTime=0;};$('rail-restart').onclick=()=>{playing=false;lastTime=0;playTime=railRecord.trajectory[clipStart].time_s;railFrame(clipStart);};$('rail-time').oninput=()=>{playing=false;lastTime=0;const i=Math.round(+$('rail-time').value/1000*(railRecord.trajectory.length-1));playTime=railRecord.trajectory[i].time_s;railFrame(i);};


let gripDemo,gripActive;
async function loadGripDemo(){gripDemo=await fetch(A+'grasp_v14.json').then(r=>r.json());$('grip-box').onclick=()=>showGrip('Box');$('grip-cola').onclick=()=>showGrip('Cola');$('grip-open').onclick=()=>gripStep(false);$('grip-close').onclick=()=>gripStep(true);showGrip('Box');}
function showGrip(key){playing=false;lastTime=0;gizmo.detach();current=null;gripActive=gripDemo.results.find(r=>r.key===key);orders.visible=false;railOrders.visible=false;qr.visible=false;state=structuredClone(gripActive.state);$('drawer').value=key==='Cola'?.7:0;for(const m of trayMeshes){m.position.copy(m.userData.closed);if(key==='Cola'&&m.name.startsWith('CEK_K5_ic1_1__')&&m.name.includes('CEKMECE'))m.position.z+=m.name.includes('CEKMECE_ARA')?.35:.7;}for(const [k,g]of Object.entries(pickGroups)){g.position.copy(g.userData.closed);g.quaternion.identity();g.position.z=g.userData.closedZ+(k==='Cola'&&key==='Cola'?.7:0);}for(const m of trayMeshes){if(m.name.includes('on_seffaf')){m.material.transparent=true;m.material.opacity=.12;m.material.depthWrite=false;}}pickGroups[key].position.set(...gripActive.product);const p=gripActive.product;camera.position.set(p[0]+.44,p[1]+(key==="Cola"?.85:.42),p[2]+.60);orbit.target.set(p[0],p[1]+.06,p[2]+.04);orbit.update();draw();$('status').textContent=key==='Box'?'Kutu: ön kenarı üst ve alt pedler kavrıyor · alt parmak için yatakta 80 mm erişim çentiği':'Kola: dik yaklaşım · pedler üst gövdenin iki yanında';$('result').textContent='Kaynak kavrama geometrisi. Sipariş oynatma düğmeleriyle taşıma ve bırakma hareketini inceleyebilirsin. İdeal tutuş; gerçek kuvvet testi yok.';}
function gripStep(closed){if(!gripActive)return;state=structuredClone(closed?gripActive.state:gripActive.path[0]);draw();$('status').textContent=(gripActive.key==='Box'?'Kutu':'Kola')+(closed?' · kavrama pozu':' · parmaklar açık');}




// Snapshot buttons use the same audited motion as playback, including the held/released product.
function orderPose(place){if(!railRecord)return;playing=false;lastTime=0;const k=$('product').value,i=railRecord.trajectory.findIndex(f=>place?f.placed[k]:f.carrying===k);if(i<0)return;$('order-task').value=k;$('order-task').onchange();playTime=railRecord.trajectory[i].time_s;railFrame(i);const p=place?railRecord.trajectory[i].placed[k]:railRecord.trajectory[i].product;camera.position.set(p[0]+.65,p[1]+.65,p[2]+.95);orbit.target.set(p[0],p[1]+.06,p[2]);orbit.update();$('status').textContent=(place?'Bırakma':'Alma')+' pozu · '+k+' · aynı sipariş kaydı';render();}
$('pick').onclick=()=>orderPose(false);$('place').onclick=()=>orderPose(true);

function compileSelected(){if(!baseRecord)return;playing=false;lastTime=0;const recipe=workflowConfig.recipes.find(r=>r.id===$('recipe').value);railRecord=compileOrder(baseRecord,recipe);clipStart=0;clipEnd=null;playTime=0;$('machine-ready').disabled=true;$('order-task').value='all';railFrame(0);$('rail-measure').textContent='UR10e sınırlarıyla zamanlanmış '+baseRecord.summary.duration_s.toFixed(1)+' s robot hareketi; '+(recipe.processing_after_dough_s===null?'toplam süre makine hazır sinyalini bekliyor':('makineyle birlikte '+railRecord.summary.duration_s.toFixed(1)+' s'))+'. Yaklaşma ≤0,12 m/s; açık koridor çalışma sınırı 1 m/s. Ray 0,5 m/s ve ivmeler deneme ayarıdır. '+(recipe.id==='lahmacun'?'İkinci hamur çevrimi bu 3B klipte henüz yok; iki çevrim makine zamanlaması yük planında mevcut.':'')+(recipe.processing_after_dough_s===null?'Yeni tarifin hazır sinyali elle veya gelecekte makineden gelir.':'');$('summary').textContent='Tek sipariş 3B yolu: sağ sütun, 850 mm sabit raf. Hamur mevcut tablaya; içecek sağ arkaya, tatlı sağ öne, kutu sola. İdeal tutuş. Diğer gözlere ait tam hareketler bu klipte doğrulanmadı.';}
$('machine-ready').onclick=()=>{if(!railRecord.gate)return;const t=playTime,recipe=workflowConfig.recipes.find(r=>r.id===$('recipe').value),handoff=railRecord.events.find(e=>e.name==='table.robot_clear').time_s;railRecord=compileOrder(baseRecord,recipe,{machineReadyAfter:Math.max(0,t-handoff)});$('machine-ready').disabled=true;$('status').textContent='machine.box_ready alındı; Oynat ile devam et.';};
$('load-plan').onclick=()=>{const arrivals=scenarioOrders({...defaultDemand,scenario:$('demand-profile').value,seed:Number($('demand-seed').value)}).map((o,i)=>({...o,cola:((i+1)*37)%100<50,dessert:((i+1)*19)%100<25}));const result=planDemand(arrivals,workflowConfig,baseRecord);window.lastDemandPlan=result;$('plan-result').textContent=result.summary.orders+' sipariş / '+result.summary.units+' ürün · en uzun tahmini bekleme '+(result.summary.max_wait_s/60).toFixed(1)+' dk · robot doluluğu %'+(result.summary.robot_utilization*100).toFixed(0)+'. Arşiv geliş modeli; tatlı oranı %25 deneme varsayımıdır. Bu bir kaynak/zaman planıdır; 12 göz ve çok kutulu sipariş için 3B yol sertifikası değildir.';};
$('export-isaac').onclick=()=>{const bundle={schema:'autokitch.robot.workflow/1',workflow:workflowConfig,motion:railRecord,demand:window.lastDemandPlan||null,instructions:'SI/radians, native joint order, Z-up transform defined in workflow. Use articulation targets and sensor handshakes; physical grip/release must be validated separately.'};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(bundle)],{type:'application/json'}));a.download='robot-isaac-v16.json';a.click();URL.revokeObjectURL(a.href);};
