// Precomputed collision-sampled kinematic order. Ideal grasp, no force physics.
export function installScenario(api){
 const {T,scene,machineMeshes,rig,poses,setDrawer,setQR,setQRTrays,gizmo,readState,writeState,checkCollision,contact}=api;
 const $=id=>document.getElementById(id),note=$('demo-status'),clone=x=>JSON.parse(JSON.stringify(x));
 const items=[['Dough','Hamur','CEK_K1_lahm_1'],['Cola','İçecek','CEK_K5_ic1_1'],['Dessert','Tatlı','CEK_K6_tatli_1'],['Box','Pide kutusu',null]];
 const centre=p=>new T.Vector3(p[0][3],p[2][3],-p[1][3]);
 const tcp=s=>{const m=rig.tcp(s.q,s.rail,s.jaw);return new T.Vector3(m[3],m[11],-m[7]);};
 let frames=[],products={},originals=[],running=false,planning=false,index=0,last=0,report=[],raf=0,lastSafeFrame=-1;
 const controls=[...document.querySelectorAll('#joints input,#rail,#jaw,#drawer-open,#drawer,#item,#tcp,#move,#rotate,#home,#undo,#pick,#place,#save,#import,#export,#doors,#qr,#qr-shelf,#qr-slide')];
 function lock(on){controls.forEach(e=>e.disabled=on);if(on)gizmo.detach();} function subset(g,ids){const h=new T.BufferGeometry();for(const [name,a] of Object.entries(g.attributes)){const b=new Float32Array(ids.length*a.itemSize);for(let j=0;j<ids.length;j++)for(let k=0;k<a.itemSize;k++)b[j*a.itemSize+k]=a[['getX','getY','getZ','getW'][k]](ids[j]);h.setAttribute(name,new T.BufferAttribute(b,a.itemSize));}h.computeBoundingBox();return h;}
 function extract(mesh,closed,group){
  const g=mesh.geometry,idx=g.index?Array.from(g.index.array):Array.from({length:g.attributes.position.count},(_,i)=>i),parent=Array.from({length:g.attributes.position.count},(_,i)=>i),v=new T.Vector3();
  const find=i=>{while(parent[i]!==i){parent[i]=parent[parent[i]];i=parent[i];}return i;},join=(a,b)=>{a=find(a);b=find(b);if(a!==b)parent[b]=a;};
  const weld=new Map();for(const i of new Set(idx)){v.fromBufferAttribute(g.attributes.position,i);const k=[v.x,v.y,v.z].map(x=>Math.round(x*1e6)).join(',');if(weld.has(k))join(i,weld.get(k));else weld.set(k,i);}for(let i=0;i<idx.length;i+=3){join(idx[i],idx[i+1]);join(idx[i],idx[i+2]);}
  const boxes=new Map();for(const i of new Set(idx)){const root=find(i);v.fromBufferAttribute(g.attributes.position,i).applyMatrix4(mesh.matrixWorld);if(!boxes.has(root))boxes.set(root,new T.Box3());boxes.get(root).expandByPoint(v);}
  const chosen=new Set();for(const [root,b] of boxes){const c=b.getCenter(new T.Vector3()),size=b.getSize(new T.Vector3());if(Math.hypot(c.x-closed.x,c.z-closed.z)<.025&&Math.abs(c.y-closed.y)<.085&&size.x<.15&&size.z<.15)chosen.add(root);}
  if(!chosen.size)return 0;console.info('ORDER_STOCK',JSON.stringify({mesh:mesh.name,components:boxes.size,selected:chosen.size}));const take=[],keep=[];for(let i=0;i<idx.length;i+=3)(chosen.has(find(idx[i]))?take:keep).push(idx[i],idx[i+1],idx[i+2]);originals.push({mesh,geometry:g});mesh.geometry=subset(g,keep);
  const part=new T.Mesh(subset(g,take),mesh.material);part.geometry.applyMatrix4(mesh.matrixWorld);part.geometry.translate(-closed.x,-closed.y,-closed.z);part.geometry.computeBoundingBox();part.name='SIPARIS_'+group.name+'_'+mesh.name;group.add(part);machineMeshes.push(part);return take.length/3;
 }
 function initProducts(){if(Object.keys(products).length)return;for(const [, ,d] of items)if(d)setDrawer(d,0);scene.updateMatrixWorld(true);
  for(const [key,label,d] of items){const pick=poses[key+'_pick'],group=new T.Group();group.name=key;let closed=centre(pick.product);if(d)closed.z-=.7;group.position.copy(closed);scene.add(group);const selected=[];
   if(d){const matches=machineMeshes.filter(m=>m.name.startsWith(d+'__')&&m.name.includes('CEKMECE')&&/(?:__hamur|__kutu_icecek|__plastik)/.test(m.name));let tris=0;for(const m of matches)tris+=extract(m,closed,group);if(!tris)throw Error(label+' stoktan ayrılamadı');selected.push(...group.children);}
   else{const g=new T.BoxGeometry(.320,.045,.320);g.computeBoundingBox();const mesh=new T.Mesh(g,new T.MeshStandardMaterial({color:0xbca276,roughness:.8}));mesh.name='SIPARIS_DOLU_PIDE_KUTUSU';group.add(mesh);machineMeshes.push(mesh);selected.push(mesh);for(const mesh of machineMeshes.filter(m=>m.name.startsWith('E_KUTU__'))){originals.push({mesh,visible:mesh.visible});mesh.visible=false;}}
   products[key]={group,closed,selected,drawer:d,label};console.info('ORDER_PRODUCT',JSON.stringify({key,parts:selected.length,closed:closed.toArray()}));
  }
 }
 function resetProducts(){for(const p of Object.values(products)){p.group.position.copy(p.closed);p.group.quaternion.identity();}for(const [, ,d] of items)if(d)setDrawer(d,0);setQRTrays({});contact(null,false);}
 function apply(f){writeState(f.state);for(const [, ,d] of items)if(d)setDrawer(d,f.drawers[d]||0);setQRTrays(f.trays||{});for(const [key,p] of Object.entries(products)){p.group.position.copy(p.closed);p.group.rotation.set(0,key==='Box'&&f.placed.Box?(f.placed_box_yaw||Math.PI):0,0);if(p.drawer)p.group.position.z+=f.drawers[p.drawer]||0;if(f.placed[key])p.group.position.fromArray(f.placed[key]);}
 if(f.carrying){const p=products[f.carrying];p.group.position.copy(tcp(f.state)).add(new T.Vector3().fromArray(f.offset));if(f.carrying==='Box')p.group.rotation.y=f.carried_yaw||0;contact(p.selected,true);}else contact(f.touching?products[f.touching].selected:null,!!f.touching,f.touching&&!f.placed[f.touching]&&products[f.touching].drawer?products[f.touching].drawer+'__silikon__CEKMECE':null);scene.updateMatrixWorld(true);$('demo-scrub').value=index;$('demo-phase').textContent=f.stage;
 }
 async function prepare(){if(frames.length)return true;planning=true;lock(true);try{const record=await fetch('../hat3d/robot-main-v1/'+api.record).then(r=>{if(!r.ok)throw Error('Hareket kaydı hazır değil');return r.json();});if(record.version!==4||record.machine_base!==rig.data.machine_base_commit||record.tip_sha256!==rig.data.tip_sha256||record.trajectory.length!==record.frames)throw Error('Uyumsuz hareket kaydı');initProducts();frames=record.trajectory;$('demo-scrub').max=frames.length-1;console.info('ORDER_RECORD_LOADED',JSON.stringify({version:4,frames:frames.length,discrete_surface_checked:record.discrete_surface_checked}));return true;}catch(e){note.textContent=e.message;return false;}finally{planning=false;lock(false);}}
 function audit(f){const hits=checkCollision();if(hits.length){report.push({frame:index,stage:f.stage,hits});if(report.length<8)console.warn('ORDER_COLLISION',JSON.stringify(report.at(-1)));}return hits;}
 async function start(){api.observe(null);if(planning||running)return;if(!await prepare())return;resetProducts();report=[];index=0;lastSafeFrame=-1;running=true;lock(true);last=0;raf=requestAnimationFrame(tick);}
 function tick(t){if(!running)return;if(t-last<1000/30){raf=requestAnimationFrame(tick);return;}last=t;const f=frames[index];if(!f){running=false;lock(false);note.textContent=report.length?'Oynatma tamamlandı; çakışma uyarısı var.':'Sipariş tamamlandı · dört ürün yerinde. İdeal tutuşla hareket önizlemesi.';return;}apply(f);const hits=$('demo-strict').checked?audit(f):index%10===0?audit(f):[];if(hits.length&&$('demo-strict').checked){running=false;lock(false);if(lastSafeFrame>=0){index=lastSafeFrame;apply(frames[index]);checkCollision();}note.textContent='Çarpışmadan önce durdu: '+hits[0];return;}if(!hits.length)lastSafeFrame=index;note.textContent=f.stage+' · '+Math.round(index/frames.length*100)+'%';index++;raf=requestAnimationFrame(tick);}
 $('demo-start').onclick=start;$('demo-stop').onclick=()=>{running=false;cancelAnimationFrame(raf);lock(false);note.textContent='Duraklatıldı. Zaman çubuğuyla inceleyebilirsin.';};$('demo-reset').onclick=()=>{running=false;cancelAnimationFrame(raf);start();};
 $('demo-scrub').oninput=()=>{api.observe(null);if(!frames.length)return;running=false;cancelAnimationFrame(raf);lock(false);index=+$('demo-scrub').value;apply(frames[index]);const hits=audit(frames[index]);note.textContent=frames[index].stage+(hits.length?' · ÇARPIŞMA: '+hits[0]:' · yüzey kesişimi yok');};
 $('demo-audit').onclick=async()=>{api.observe(null);if(planning||!await prepare())return;running=false;cancelAnimationFrame(raf);planning=true;lock(true);report=[];for(index=0;index<frames.length;index++){apply(frames[index]);audit(frames[index]);if(index%20===0){note.textContent='Bütün kareler denetleniyor · '+Math.round(index/frames.length*100)+'%';await new Promise(r=>setTimeout(r,0));}}index=frames.length-1;apply(frames[index]);planning=false;lock(false);note.textContent=frames.length+' kare · '+report.length+' çakışmalı kare · ideal tutuş; sürekli süpürme/fizik onayı değildir.';console.info('ORDER_FULL_AUDIT',JSON.stringify({frames:frames.length,collision_frames:report.length,physics:false}));};
 $('demo-report').onclick=()=>{const data=JSON.stringify({version:4,physics:false,frames:frames.length,findings:report},null,2);$('demo-data').textContent=data;const blob=new Blob([data],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='robot-v4-denetimi.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};

 async function preset(mode){if(!await prepare())return;running=false;cancelAnimationFrame(raf);api.observe(null);lock(false);const key=$('item').value,label=items.find(a=>a[0]===key)[1];let n=mode==='pick'?frames.findLastIndex(f=>f.stage===label+' · kavra'):frames.findIndex(f=>f.placed[key]);if(n<0)return;index=n;const f=clone(frames[n]);const p=poses[key+'_'+mode];if(p.saved_in_editor)f.state={q:p.q,rail:p.rail,jaw:p.jaw};apply(f);api.setSlot(key+'_'+mode);const product=products[key],off=mode==='pick'?product.group.position.clone().sub(tcp(f.state)):product.group.position.clone().sub(tcp(f.state));contact(product.selected,true);api.observe(st=>{product.group.position.copy(tcp(st)).add(off);});if(api.target)gizmo.attach(api.target);checkCollision();note.textContent=label+' · '+(mode==='pick'?'kavrama pozu':'bırakma pozu')+' · gizmo ile düzenleyip Bu pozu kaydet düğmesine basabilirsin.';}
 $('pick').onclick=()=>preset('pick');$('place').onclick=()=>preset('place');
 window.ORDER_SCENARIO={get running(){return running;},get frames(){return frames.length;},get findings(){return clone(report);}};
}
