# -*- coding: utf-8 -*-
# hat_site_gen.py'ye eski ana sayfa (Yol C bloğu) içeriğini harmanlar: hâlâ geçerli bilgiler eklenir, eskiyenler güncel kararla değiştirilir/arşiv notu alır.
import io, re
P = r"C:\Users\Kemal\Desktop\Kemal\WEBSİTE\AUTOKITCH\arastirma\_uretec\hat_site_gen.py"
s = io.open(P, encoding='utf-8').read()
def cut(name):
    i = s.index("unit('%s'" % name)
    j = s.index("\nunit('", i+5) if "\nunit('" in s[i+5:] else s.index("\nprint('OK')", i)
    return i, j
def repl(name, new):
    global s
    i, j = cut(name); s = s[:i] + new + s[j:]

# ---------------- STORE ----------------
repl('store.html', '''unit('store.html','1 · STORE — soğuk depo','140 × 84 × 197',COL['store'],'Dükkânın 3 günlük tüm soğuk stoku tek kasada: hamur topları, içecek, tatlı ve donmuş TOPPING kapları. Hamur mahalle fırınından hazır gelir (220 g), yoğurma yok. Tam çekmeceli kapaksız kasa; robot çekmeceyi pençeyle çeker.',
 '<div class="card">'+steps(['<b>Tedarik:</b> fırıncı sabit takvimle 3 günde bir gelir (örn. Pzt + Per). Teslimat ≈ 240 top = 160 taze + 80 donmuş; teslimatçı dolu çukurlu tepsileri kızaklara sürer, boşları alır (tepsi takası — dükkânda dolum işi yok, ~10 dk).','<b>Üst bölüm +3 °C:</b> sol modül 4 içecek çekmecesi (7 kanal) + 1 L çekmecesi; sağ modül 8 taze hamur çekmecesi (20 top, çukurlu tepsi GN 2/1 53×65, çukur Ø12).','<b>Alt bant −18 °C:</b> sol modülde klapeli KASET KATI (4 donmuş TOPPING kabı 14×68×24, robot çatalla önden alır — v5 önerisi), altında 4 donmuş hamur çekmecesi (20 top). Donmuş top 3. günün deposu + sigortadır.','<b>Sipariş anı:</b> robot taze çekmeceyi 70 cm tam açar, pençeyle topu alır, PRESS'+AP+'e götürür. Kol dolabın içine hiç girmez, üstten alır.','<b>Gece:</b> min-max kuralı — dolaptaki hazır stok önümüzdeki ~20 saatin tahmini satışının altına inince kol boş anda donmuş parti indirir; inen top "çözülüyor" etiketi alır, 8–12 saat dolmadan prese gönderilmez (çözülme bekçisi).','<b>Eleman:</b> haftada 1 içecek/tatlı ve donmuş kapları sürer; teslimat günü kasaları tepsilere dizer.'])+'</div>',
 '<div class="card">'+kv([('Soğutma','2 grup: −18 (1/3 HP) ve +3 (1/4 HP), bölme 28, üstten servis'),('Çekmeceler','17 çekmece + 1 klapeli kaset katı; PU 60/80, ray 12,7, 70 cm tam açılım; kapak yok, raf başına tek 24 V itici (top başına motor/sensör yok)'),('Kaset katı (v5)','z 40–69 sol modül: 4 kap 14×68×24 yan yana (4×14 + 3×1 + 0,5 = 59,5 ✓), L raf, klape 6'),('Kapasite','taze 8 × 20 = 160 top (1.–2. gün) · donmuş 4 × 20 = 80 top (3. gün + sigorta) · içecek ≈ 110 kutu (kanal + yaylı market iticisi) + tatlı ≈ 16 + 1 L ×8'),('Hamur','220 g, Ø9–10 cm; fırıncıya tek şart az mayalı yoğurma'),('72 saat kuralı','taze top buzdolabında en fazla 72 saat (soğuk fermantasyonun tatlı noktası); donmuş top haftalarca — donma sayacı durdurur, çözülme kaldığı yerden devam eder'),('FIFO','takip birimi ÇUKUR: her çukurun adresi (A1, B3…) ve damga saati yazılımda; alma oku en eskiyi, koyma oku sıradaki boşu gösterir — fiziksel düzen = yaş düzeni'),('Envanter','göz sensörü YOK (~270 nokta = kablo + arıza): kayıt defteri (her hareket robotta damgalı) + alma anında bilek kamerası doğrular (0,2 sn)'),('Sipariş miktarı','son 3 günün ortalaması × 3 gün × 1,15 pay − eldeki stok; 4–6 haftada gün katsayıları oturur; öneriyi sistem verir, kararı insan onaylar'),('Süre bekçisi','60. saati geçen toplar → kioskta "günün pidesi" indirimi; 72. saat çöp + sayaç. Beklenen fire %3–5'),('İnsan işi','3–4 günde bir 10 dk kasa dizme + haftalık ikmal; günlük temizlik ayrı')])+'</div>',
 fig('ist1_store_detay_v4.png','STORE v4 — alt buzluk 6 çekmece, tam çekmeceli kasa (4 Eyl 2026)')+thumbs([('ist1_store_detay_v3.png','v3'),('ist1_store_detay_v2.png','v2')]),
 '<div class="card">'+sup([('İnoksan · Öztiryakiler · Frenox','2 kapılı kombine kasa 140×197×84 (60 mm PU, 0,8 paslanmaz)','≈ 90–150 bin TL'),('Çekmece / sürücü entegrasyonu','motorlu çekmece, itici, kızak','40–80 bin TL'),('Çukurlu silikon tepsi','GN 2/1 65×53, 20 çukur Ø12, tek parça yapışmaz','≈ 400–700 TL/adet (toptan)'),('Yaylı market iticisi','içecek kanalları (kutu formatı)','standart raf ürünü')])+'<p class="note">İçecekler KUTU formatında (kola · ayran · fanta · sprite · su); SKU ataması satışa göre BEYİN planogramı.</p></div>',
 '<div class="card">'+problems([('S1','Çekmece/raf motoru sıkışırsa robot bekler','ÖNERİ VAR','akım sensörü algılar, raf devre dışı, diğerinden devam + eleman uyarısı'),('S2','Kapak/servis açık kalırsa soğuk kaçar','ÇÖZÜLDÜ','kapak yok (çekmece); switch + 60 sn bekçisi, alarm'),('S3','Donmuş top zamanında çözülmezse','ÇÖZÜLDÜ','min-max + çözülme bekçisi 8–12 saat, BEYİN önden eritir'),('S4','Elektrik kesintisi — soğuk zincir','ÖNERİ VAR','kapalı kasa 2–3 saat soğuk tutar; 30 dk üstünde elemana bildirim (jeneratör gereksiz)'),('S5','Yanlış/boş çukurdan alma','ÇÖZÜLDÜ','kayıt defteri + bilek kamerası alma anında doğrular'),('①','v5 kaset katı onayı','ÖNERİ VAR','Kemal onayı bekliyor')])+'<p class="note">Eski turda "soğutma grupları en üstte olsun" önerisi vardı (Kemal, erişilebilirlik); STORE\\'da gruplar üstte kaldı, TOPPING\\'de dibe indi.</p></div>',
 ver(['v5 öneri (5 Eyl): −18 kaset katı üstte, klapeli, 4 kap sol modül','v4 (4 Eyl): alt buzluk, 19 çekmece, gerçek kalınlıklar, 70 cm tam açılım','v3 (Ağu): tam çekmeceli kapaksız kasa','v1–v2 (Ağu): üst buzluk, kapaklı denemeler; ılık raf konsepti (ısıtmalı presle kalktı)']))
''')

# ---------------- PRESS ----------------
repl('press.html', '''unit('press.html','2 · PRESS — hamur presi','70 × 84 × 197',COL['press'],'Fersah PZP-400 ısıtmalı pide/pizza presi: top tepsi içinde Ø29 ısıtmalı plakayla açılır. Isıtmalı olduğu için ılık bekleme rafı tamamen kalktı — top dolaptan doğrudan prese gider.',
 '<div class="card">'+steps(['Robot tepsiyi alt plakaya bırakır (tepsi Ø32 rafta bekler), pençeyle hamur topunu tepsinin içine koyar.','Üst plaka Ø29 ısıtmalı iner, birkaç saniye basar; taban tepsinin içinde şekillenir, hamur tepsi bordürüne (12 mm) çarpmaz. +3 °C\\'den gelen topu geri çektirmeden bastığı için fırın süresine reçeteden +15–30 sn eklenir.','Kol pençeyi bırakıp tepsiye kilitlenir; pide artık kutuya kadar tepsiden çıkmaz. Basılan taban bekletilmez.','Uç değiştirme: PRESS altındaki yatay yuvalarda pençe ve çatal; kolda tepsi eli.','Çöp: 30 L kapaksız poşetli kova (öne çekilir, huni yok — pençe bırakır); süresi dolan top buraya, gün sonunda sayaçtan fire raporu.'])+'</div>',
 '<div class="card">'+kv([('Makine','Fersah PZP-400 ISITMALI pres: 64×80×95, 170 kg, 3,5 kW 220 V, zeminde; 500–700 adet/saat, 100–750 g, 15–40 cm'),('Neden bu','ısıtmalı plaka soğuk topu geri çektirmez → ılık bekleme rafı gereksiz. CP-330 soğuk pres yarış dışı (ılık raf geri gerektirirdi)'),('Plaka','üst Ø29 ısıtmalı (fabrika Ø40 → Ø29 kesilecek), alt ısıtmalı, zeminden ~90'),('Üst bölge (v8)','sol yarı kova 30 L + 14 cm kol boşluğu; sağ yarı boş 35×59×84 (büyüme payı)'),('Alt bölge','uç yuvaları 14 (pençe · çatal 50 derinlemesine · boş) + tepsi rafı 8 (2 yan yana + 1 kolda)'),('Fire','beklenen %3–5; kova eleman tarafından her gün boşaltılır')])+'</div>',
 fig('ist2_pres_detay_v8.png','PRESS v8 — kova + kol boşluğu, uç yuvaları, tepsi rafı')+thumbs([('ist2_pres_detay_v6.png','v6'),('ist2_pres_detay_v5.png','v5')]),
 '<div class="card">'+sup([('Fersah PZP-400 (İstanbul)','ısıtmalı pide/pizza presi, PLC uyumlu','≈ 100–300 bin TL bandı; teklif ve otomasyon soruları iletildi (26 Ağu)'),('Fersah CP-330','soğuk pres, max 36 cm açar','yarış dışı (ılık raf gerektirir)'),('Fersah PZR-250','konveyör pres','reddedildi'),('Fersah — açık sorular','Ø29 plaka/kalıp · yapışmaz kaplama türü · Ø30 yuvarlak taban','cevap bekleniyor')])+'</div>',
 '<div class="card">'+problems([('P1','Top sıcak plakaya yapışırsa','ÖNERİ VAR','yapışmaz kaplama + sıcaklık/süre reçetesi; kaplama türü Fersah\\'a soruldu'),('P2','Top tablaya ortalanmadan bırakılırsa','ÖNERİ VAR','tepsi çukur merkezi + bilek kamerası'),('P3','Şekli bozuk çıkan taban','ÇÖZÜLDÜ','pres sonrası kamera → çöpe, yeni top otomatik'),('P4','Rezistans arızası (soğuk pres = geri çeken hamur)','ÖNERİ VAR','plaka sıcaklık sensörü eşik altında üretimi durdurur + uyarı'),('P5','Uç istasyonunda uç takılamazsa','AÇIK','yedek yuva + manuel müdahale'),('⑤','Ø29 plaka / tepsi bordürü uyumu, ısıtmalı plakanın tepsiyle temas süresi','AÇIK','Fersah + pilot'),('—','Çöp haznesi','ÇÖZÜLDÜ','30 L poşetli kova, motorsuz, eleman her gün boşaltır')])+'</div>',
 ver(['v8 (4 Eyl): sol kova + kol boşluğu, sağ boş, altta uç yuvaları ve tepsi rafı','v6 (4 Eyl): tepsi içinde basma kararı (Kemal), Ø29 plaka','v5 (Ağu): uç cepleri + çöp çekmecesi','v1–v4 (Ağu): Fersah yerleşimi, ılık raf (kalktı)']))
''')

# ---------------- TOPPING (ek: gramaj, malzeme formu, TR üretici, pilot, temizlik) ----------------
s = s.replace("""('Bant kuralı','ağız merkezi yan duvara ≥ 27 (tepsi 16 + spiral 11), arka duvara ≥ 31')])+'</div>',""",
"""('Bant kuralı','ağız merkezi yan duvara ≥ 27 (tepsi 16 + spiral 11), arka duvara ≥ 31'),('Gramaj / pide','kaşar ≈ 80 g · sucuk 8–10 küp · kıyma (kavurma) ≈ 60 g · kuşbaşı ≈ 60 g'),('Malzeme formu','hepsi KÜP/PARÇA gelir — sucuk kasaptan küp doğranmış (baton/dilim ve dilimleyici YOK), kaşar rende, kavurma granül, kuşbaşı SOTELİ/yarı pişmiş (çiğ et 3–4 dk fırında pişmez); çiğ harç makinede yok (su salar)'),('Tedarik ritmi','haftada 1: BEYİN gerçek tüketimi ölçer, "bu hafta kaşar 42 · sucuk 9 · kıyma 12 · kuşbaşı 8 kg al" der; eleman poşetten kaba doldurur, hiçbir şey kendi poşetinde durmaz'),('Saat kuralı','her kabın takılma saati BEYİN\\'de; süresi dolan kap dolu olsa da çıkar (kalan ≤ 1 kg). Donmuş kabın saati durur, çözülmede kaldığı yerden işler'),('Temizlik','helezon ve tarak tek bağlantıdan sökülür → bulaşık makinesi; kap değişiminde kap yıkanır; dozaj boşluğu (açık, soğutulmaz) günlük silinir — un/toz yok')])+'</div>',""")

s = s.replace("""'<div class="card">'+sup([('Picnic Works (referans)','otomatik topping istasyonu, helezon + tarak kapları','model referansı, satın alma yok'),('POM helezon','Ø70 hatve 50, işleme','yerli torna/CNC'),('PC gövde','5 mm polikarbonat, bükme/yapıştırma','yerli'),('Soğutma','1/12 HP yatay grup + evaporatör','entegratör')])+'</div>',""",
"""'<div class="card">'+sup([('Picnic Works (ABD, referans)','üstten dolan şeffaf hazne + helezon dozajı + çubuk tarak; firma 2026\\'da kapandı','model referansı, satın alma yok'),('POM helezon + mil','Ø70 hatve 50 boy 66, tırtıllı topuz','yerli torna/CNC'),('PC gövde','5 mm polikarbonat, bükme/yapıştırma, menteşeli kapak','yerli'),('Soğutma','1/12 HP yatay grup + evaporatör (dipte, plint ızgara)','entegratör'),('Forpack · Hipermak · Hipomak','kadehli/porsiyon dozaj ünitesi (mekanizma ailesi)','TR üretici — referans'),('Polimak · Saftek · Denge Proses · TMD','hücre tekeri, non-stick rotor, paslanmaz dozaj','TR üretici — büyütülmüş hâli yaptırılabilir')])+'<p class="note">Bu gramajda hazır cihaz yok: Chowbotics Sally üretimden kalktı, xPizza Cube B planı. Pilot yolu: küçük ölçekli akış testi (soğuk küp sucuk · kaşar · kavurma) → çalışan mekanizma paslanmaz büyütülmüş hâliyle Denge/TMD sınıfına yaptırılır.</p></div>',""")

s = s.replace("""('v27','Yayıcı plaka mı spiral süpürme mi · gramaj prototipi · PC çizilme · 2 soket mi tek motor mu','AÇIK','prototip')])+'</div>',""",
"""('v27','Yayıcı plaka mı spiral süpürme mi · gramaj prototipi (123 cm³/dev) · PC çizilme · kap başına 2 soket mi tek motor + kayış mı','AÇIK','prototip'),('—','Malzeme pide ortasında biterse','ÖNERİ VAR','sipariş başında yeterlilik teyidi — yarım pide hiç oluşmaz; yetersizse pide bekler, yedek kap takılır'),('—','Dozaj boşluğu açık ve soğutulmaz','ÖNERİ VAR','ağızda bekleyen malzeme az; pilotta 1 saat beklemiş doz tartılır')])+'</div>',""")

# ---------------- OVEN (ek: elektrik karşılaştırması, Gold Medal, 380 V, Cancan bıçak) ----------------
s = s.replace("""('Kapasite','tek kavite 12–15/saat, iki kavite 25–30')])+'</div>',""",
"""('Kapasite','tek kavite 12–15/saat, iki kavite 25–30 — günde 100 hedefi ve pik saat için yeterli; 150+/güne çıkarsa 3. kavite ya da konveyör (B planı)'),('Neden kapalı hazne','iki ucu açık konveyör tünelinde ısı sürekli kaçar (≈ 1.300–1.800 kWh/ay) — kapalı hazne + gece kapalı ≈ 500–800 kWh/ay; dikey istiflendiği için tek gövdede az yer tutar'),('Bıçak yıldızı','Cancan 1330 sınıfı yerli pizza dilimleme presinin paslanmaz çoklu bıçak yıldızı (4/6/8 dilim, yıkanabilir, yedeği bol); "birebir kesmesine gerek yok, bıçak izi yeter" → kuvvet düşük, 0,5 mm durdurucu tepsi kaplamasını çizmez'),('Altyapı','2 kat 4,8 kW — pano 380 V hazırlanır; gece kapalı + eko mod elektrik kaleminde ayda ≈ 2–4 bin TL tasarruf'),('Hijyen','bıçak kafası tek hamlede çıkar, günlük temizlikte yıkanır')])+'</div>',""")

s = s.replace("""('Gold Medal 2496 / Alibaba dispenser','hazır ısıtmalı yağ pompası','~1.300 $ / 185 $')])+'</div>',""",
"""('Gold Medal 2395 / 2496','sinema tereyağı dispenseri sınıfı hazır ünite (ısıtmalı tank + pompa)','≈ 1.300 $ + nozül uyarlaması'),('Alibaba ısıtmalı sos dispenseri','pompalı, ısıtmalı','≈ 185 $ (teyit gerek)'),('Cancan 1330','pizza dilimleme presi — bıçak yıldızı kaynağı','birkaç bin TL, yedek bıçak bol'),('Kesme + sprey ünitesi (entegratör)','24 V aktüatör + gövde + nozül + pompa','≈ 15–25 bin TL')])+'</div>',""")

# ---------------- PACK (ek: saçet, maliyet) ----------------
s = s.replace("""('Vantuz payı','dolu yığın 60 kg: gerek 257 N, vantuz 528 N → pilot 40 cm ile başlar')])+'</div>',""",
"""('Vantuz payı','dolu yığın 60 kg: gerek 257 N, vantuz 528 N → pilot 40 cm ile başlar'),('Saçet seti','peçete + ıslak mendil + pul biber: mekanizma SIFIR — eleman kutu demetlerini şarjöre sürerken setleri kutunun içine koyar; v2 opsiyonu otomatik düşürücü (friction feeder)'),('Maliyet','eksen + vakum + kalıp + kapak kolu gövdesi ≈ 40–60 bin TL (entegratör imalatı)')])+'</div>',""")

# ---------------- DOLAP (ek: süre politikası, tedarikçiler, vitrin) ----------------
s = s.replace("""('İç','PU 20 mm, çıkarılabilir taban tepsisi, IR sensör, Ø8 buhar deliği ×3; ısıtıcı yok (15 dk kuralı)')])+'</div>',""",
"""('İç','PU 20 mm, çıkarılabilir taban tepsisi, IR sensör, Ø8 buhar deliği ×3; ısıtıcı yok (15 dk kuralı)'),('Süre politikası','20 dk: "soğuyor" mesajı · 30 dk: hatırlatma · 45 dk: geç listesi · gün sonu eleman boşaltır (eski turdaki 60 °C ısıtmalı göz fikri, 15 dk alınma kuralıyla birlikte kaldırıldı)'),('Yazılım','sipariş no ↔ dolap eşleşmesi BEYİN\\'de; dolap durumu tablosu (boş / yükleniyor / dolu-bekliyor / geç) + robot için 12 sabit XYZ hedefi'),('Vitrin rolü','dolap cephenin kendisidir; yanındaki sipariş ekranı ve "camın arkasında robot" görünümü dükkânın reklam yüzü')])+'</div>',""")

s = s.replace("""('Öneri','kabin entegratörden + 12 × 12 V kilit + 16 kanal kilit kartı (KR-CU16) + IR','60–90 bin TL')])+'</div>',""",
"""('Öneri','kabin entegratörden + 12 × 12 V kilit + 16 kanal kilit kartı (KR-CU16) + IR','60–90 bin TL (tahmin, teklifle netleşir)'),('Kutu (kutu.tech) · Metasel','yerli akıllı teslimat dolabı üreticileri — motorlu kapak + API özelleştirmesi','≈ 150–400 bin TL bandı, sorulacak'),('Carter-Hoffmann · Hatco · Winnsen','ısıtmalı teslimat dolabı (ithal)','Winnsen\\'e mail atıldı, cevap bekleniyor')])+'</div>',""")

# ---------------- EKRAN (ek: POS bankaya, fiyat) ----------------
s = s.replace("""('İnnova · Kardo POS · Novem · PandaX · Menulux · Posgo · robotPOS','kiosk + yazılım','50–120 bin TL'),""",
"""('İnnova · Kardo POS · Novem · PandaX · Menulux · Posgo · robotPOS','kiosk + yazılım','≈ 40–120 bin TL (ekran + POS; POS kirası bankayla anlaşmaya bağlı)'),""")
s = s.replace("""('Fiş','perakende satışta ÖKC zorunlu; kağıtsız e-Arşiv seçeneği mali müşavire')])+'</div>',""",
"""('Fiş','perakende satışta ÖKC zorunlu; kağıtsız e-Arşiv seçeneği mali müşavire'),('Ödeme','para doğrudan bankaya gider (POS modülü); nakit yok — kioskta uyarı'),('Yönetim','menü ve fiyatlar servis panelinden yönetilir (dükkânda dokunmatik panel + telefonda aynı panel, kod yazmadan)')])+'</div>',""")

# ---------------- ROBOT (BEYİN üç katman, markalar, fiyat bantları, görev listesi) ----------------
s = s.replace("""('Güvenlik','kapalı koridor, kapı açılınca durur; müşteri hiçbir noktadan ulaşamaz')])+'</div>',""",
"""('Güvenlik','kapalı koridor, kapı açılınca durur; müşteri hiçbir noktadan ulaşamaz'),('Uç değiştirici','SMARTSHIFT / RSP CoboShift sınıfı: pim + burç + kilit, 2–3 sn, ±0,1 mm; yuvalar PRESS kabininin altında'),('Tepsi ucu','kulplu tepsi Ø32, kulp paslanmaz 6 cm = kilit pimi (350 °C tepsiyi silikon pençe tutamaz, metal-metal kilit şart); taban 3 mm delikli alüminyum + seramik yapışmaz kaplama, bordür 12 mm, 13 cm açık ön ağız, ≈ 0,8 kg'),('Pençe ucu','2 mafsallı adaptif pençe 0–140 mm (Robotiq 2F-140 sınıfı) + gıda silikonu soft parmak (mGrip / DoughGripper sınıfı); bilekte kamera'),('Kalkanlar','kürek yüzü, bilek çevirme, TOPPING tablası + kızak + 2 motor, PACK iticisi, pideye doğrudan temas, vakum — hepsi tasarımdan çıktı'),('Arıza planı','yedek pençe ve tepsiler uç yuvasında (robot kendisi takar); mekanik arızada "servis dışı" + entegratör servis sözleşmesi (SLA). Kol durunca hat durur — tek nokta riski bilinçli kabul')])+'</div>'+'<h3>BEYİN — üç katmanlı kontrol</h3><div class="card">'+kv([('Katman 1 · PLC (refleksler)','Siemens S7-1200 sınıfı endüstriyel kontrol kartı; motorlar, kapaklar, ısıtıcılar, sensörler buna bağlı. Robot kolun kendi kontrol kutusu kolla gelir, PLC ona iş verir'),('Katman 2 · mini endüstriyel PC (akıl)','fansız, avuç içi (≈ 10–30 bin TL): sipariş kuyruğu, reçeteler, FIFO ve süre bekçileri, kiosk/dolap ekranları, kamera işleme, platform entegrasyonları'),('Katman 3 · kiralık bulut (uzaktan göz)','ayda ≈ 300–1.000 TL sanal sunucu: telefondan canlı panel, satış kayıtları, uzaktan güncelleme, arıza bildirimi'),('Yer','oda yok, sunucu satın alma yok, laptop yok — hepsi PICKUP panosunun rafında, ayakkabı kutusu hacminde'),('İnternet koparsa','dükkân yerel beyinle çalışmaya devam eder; yalnız uzaktan izleme kesilir'),('Siparişin yolculuğu','kiosk / platform → mini PC reçeteyi kuyruğa yazar → adımlar tek tek PLC\\'ye → her adım sensör onayıyla ilerler → biten sipariş dolaba eşlenir, müşteriye kod')])+'</div>',""")

s = s.replace("""('Uç değiştirici','pnömatiksiz mekanik kilit','Schunk / yerli')])+'</div>',""",
"""('Uç değiştirici','SMARTSHIFT / RSP CoboShift sınıfı','80–160 bin TL (el + kamera dahil)'),('Robotiq 2F-140 + gıda silikonu parmak','adaptif pençe (mGrip / DoughGripper sınıfı)','uç setine dahil'),('Siemens S7-1200 + mini PC + yazılım','BEYİN katman 1–2','≈ 150–400 bin TL'),('Şasi · pano · montaj','entegratör','≈ 100–200 bin TL')])+'<p class="note">Kol bandı ≈ 600 bin – 1,8 mln TL, 3–4 m ray 150–300 bin TL. Toplam anahtar teslim entegrasyon 400–600 bin TL bandında konuşuluyor; teklifle netleşecek.</p></div>',""")

# ---------------- index: kurallar, monoblok hedefi, maliyet bandı ----------------
s = s.replace("""('Not','tezgah arkasında elemana 54 cm kalıyor (dar); ön zon 100 yapılırsa 11,8 m²')])+'</div>'),""",
"""('Not','tezgah arkasında elemana 54 cm kalıyor (dar); ön zon 100 yapılırsa 11,8 m²')])+'</div>'+'<div class="card"><h3>Kurallar (Yol C)</h3>'+kv([('Tek dükkân','her şey dükkânın içinde çözülür — merkez mutfak yok'),('Bir kişi','içeride bir eleman çalışır ve ona çok az iş düşer: haftalık ikmal, günlük kova + tepsi yıkama, 45 dk temizlik'),('Ürün','yuvarlak pide (pizza hattıyla aynı makineler)'),('Nihai hedef','istasyonların tamamı tek gövdeye — cam önlü, modüler monoblok AUTOKITCH ünitesine — giydirilir. Pilotta ayrı makinelerle doğrulanır, seri üretimde tek ürün olur'),('Defter','her istasyon kararlaştıkça bu sayfalara işlenir; eskiyen karar arşiv notuna düşer')])+'</div>'),""")

s = s.replace("""('Fanuc CRX-20iA/L · Doosan H2017 · TM20','kobot 16–20 kg, menzil 142–170','teklif alınacak')])+'</div>'),""",
"""('Fanuc CRX-20iA/L · Doosan H2017 · TM20','kobot 16–20 kg, menzil 142–170','kol 600 bin – 1,8 mln TL')])+'<h3>Maliyet bandı — kalem kalem (teklifle netleşecek)</h3>'+'<table><tr><th>Kalem</th><th>Kaynak / aday</th><th style="width:170px">Bant</th></tr>'+''.join('<tr><td>%s</td><td>%s</td><td><b>%s</b></td></tr>'%r for r in [('STORE kombine kasa','İnoksan · Öztiryakiler · Frenox','90–150 bin TL'),('Çekmece + sürücü entegrasyonu','entegratör','40–80 bin TL'),('PRESS','Fersah PZP-400','100–300 bin TL'),('TOPPING kapları + kabin','yerli imalat (POM + PC + paslanmaz)','80–150 bin TL'),('OVEN fırın','Omake FPZ01.E21','40 bin TL'),('OVEN kesme + sadeyağ ünitesi','entegratör','15–25 bin TL'),('PACK kutu açıcı','entegratör imalatı','40–60 bin TL'),('Robot kol','Fanuc · Doosan · Techman','600 bin – 1,8 mln TL'),('7. eksen ray 3–4 m','entegratör','150–300 bin TL'),('Uç değiştirici + 2 uç + kamera','SMARTSHIFT · Robotiq sınıfı','80–160 bin TL'),('BEYİN (PLC + mini PC + yazılım)','Siemens S7-1200 sınıfı','150–400 bin TL'),('Teslim dolabı','entegratör kabin + kilit kartı (yerli Kutu/Metasel bandı 150–400 bin)','60–400 bin TL'),('Sipariş kiosku + ÖKC POS','KioSelf · Onega · İnnova · Kardo','40–120 bin TL'),('Şasi · pano · montaj · devreye alma','entegratör','100–200 bin TL')])+'</table><p class="note">Bu bantlar araştırma notlarından ve alınan tekliflerden gelir; kesin fiyat teklif turunda netleşecek. Bulut paneli ayrıca ayda ≈ 300–1.000 TL.</p></div>'),""")

io.open(P,'w',encoding='utf-8').write(s)
print('patch yazildi, uzunluk', len(s))
