import * as T from 'three';
import {GLTFLoader} from './vendor/GLTFLoader.js';
import {OrbitControls} from './vendor/OrbitControls.js';
import {bendAngle,bendVertex} from './finger-bend.js';
const $=id=>document.getElementById(id),scene=new T.Scene();scene.background=new T.Color('#edf1ef');
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;$('view').append(renderer.domElement);
const camera=new T.PerspectiveCamera(38,1,.001,5),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=.06;controls.maxDistance=1.1;
scene.add(new T.HemisphereLight(0xffffff,0x747d83,2.5));for(const pos of [[.3,.5,.4],[-.3,.2,-.4]]){let l=new T.DirectionalLight(0xffffff,2);l.position.set(...pos);scene.add(l)}
const assembly=new T.Group();scene.add(assembly);let data,head,product,tips=[],current='Cola',revision=0;
const loader=new GLTFLoader(),cache={};const load=url=>loader.loadAsync(url+'?v=5');
function poseMatrix(R){return new T.Matrix4().set(R[0][0],R[0][1],R[0][2],0,R[1][0],R[1][1],R[1][2],0,R[2][0],R[2][1],R[2][2],0,0,0,0,1)}
function resize(){const w=$('view').clientWidth,h=$('view').clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe($('view'));
function bendOEM(){if(!data||!tips.length)return;const value=Number($('closure').value)/100,info=data.items[current];for(const t of tips){const angle=bendAngle(-11+(info.shifts[t.name]+11)*value),a=t.mesh.geometry.attributes.position;for(let i=0;i<a.count;i++)a.setXYZ(i,...bendVertex(t.original[i*3],t.original[i*3+1],t.original[i*3+2],angle));a.needsUpdate=true;t.mesh.geometry.computeVertexNormals();t.mesh.geometry.computeBoundingSphere()}$('state').textContent=value===0?'Open configuration':value===1?(current==='Dough'?'Dough: up to 1.1 mm geometric indentation required':(info.passed_hard_geometry?'Two geometric contacts; holding force not validated':'Grasp geometry not verified')):'Intermediate tip shape';$('view').dataset.state=JSON.stringify({item:current,closure:value,fingers:tips.length,fixedMount:true,shifts:info.shifts});}
function jawAngle(g){let lo=-.12,hi=.70;for(let k=0;k<50;k++){let a=(lo+hi)/2;let gap=2*(.048375-.00925/2*Math.cos(a)-.064*Math.sin(a))*1000;if(gap>g)lo=a;else hi=a}return(lo+hi)/2}
function bend(){if(!data||!tips.length)return;const value=Number($('closure').value)/100,info=data.items[current],g=info.open_gap_mm+(info.grip_gap_mm-info.open_gap_mm)*value,a=jawAngle(g);for(const t of tips){let sign=Number(t.name.split('_').at(-1)),c=Math.cos(a),s=Math.sin(-sign*a),p=t.mesh.geometry.attributes.position;for(let i=0;i<p.count;i++){let x=t.original[i*3]-sign*.048375,y=t.original[i*3+1],z=t.original[i*3+2]-.080;p.setXYZ(i,c*x+s*z+sign*.048375,y,-s*x+c*z+.080)}p.needsUpdate=true;t.mesh.geometry.computeVertexNormals();t.mesh.geometry.computeBoundingSphere()}$('state').textContent='Inner-tip gap G '+g.toFixed(1)+' mm | '+(value===1?'Geometric contact proposal; force unvalidated':'Illustrative opening');$('view').dataset.state=JSON.stringify({item:current,closure:value,fingers:tips.length,gap:g,fixedMount:true})}
function orient(view='top'){const R=data.items[current].tool_orientation,M=poseMatrix(R);controls.target.copy(new T.Vector3(0,0,.108).applyMatrix4(M));let offset=view==='top'?new T.Vector3(0,0,-.30).applyMatrix4(M):view==='side'?new T.Vector3(.29,0,0).applyMatrix4(M):new T.Vector3(.21,.14,.20);camera.up.copy(view==='top'?new T.Vector3(0,1,0).applyMatrix4(M):new T.Vector3(0,1,0));offset.multiplyScalar(Math.max(1,.8/camera.aspect));camera.position.copy(controls.target).add(offset);controls.update();}
async function select(item){const token=++revision;current=item;$('state').textContent='Loading model...';$('closure').disabled=true;try{if(!cache[item])cache[item]=(await load(item.toLowerCase()+'.glb')).scene;if(token!==revision)return;if(product)assembly.remove(product);product=cache[item];product.visible=$('show-product').checked;assembly.add(product);assembly.setRotationFromMatrix(poseMatrix(data.items[item].tool_orientation));$('closure').value=100;$('closure').disabled=false;for(const b of document.querySelectorAll('[data-item]'))b.setAttribute('aria-pressed',String(b.dataset.item===item));bend();orient();}catch(e){$('state').textContent='3D model could not load. Dimensioned drawings are available below.';console.error(e)}}
for(const b of document.querySelectorAll('[data-item]'))b.onclick=()=>select(b.dataset.item);for(const b of document.querySelectorAll('[data-camera]'))b.onclick=()=>orient(b.dataset.camera);$('closure').oninput=bend;
$('open').onclick=()=>{$('closure').value=0;bend()};$('close').onclick=()=>{$('closure').value=100;bend()};$('show-product').onchange=()=>{for(const m of Object.values(cache))m.visible=$('show-product').checked};
async function init(){data=await(await fetch('viewer-data.json?v=5')).json();head=(await load('fixed-fingers.glb')).scene;head.traverse(o=>{if(!o.isMesh)return;let p=o;while(p&&!p.name.startsWith('CATALOG_jaw_'))p=p.parent;if(!p)return;o.geometry=o.geometry.clone();tips.push({mesh:o,name:p.name,original:new Float32Array(o.geometry.attributes.position.array)})});assembly.add(head);const lines=[];for(const spec of data.roots){const m=spec.matrix;lines.push(0,0,.04,m[0][3],m[1][3],.067)}const guide=new T.LineSegments(new T.BufferGeometry().setAttribute('position',new T.Float32BufferAttribute(lines,3)),new T.LineBasicMaterial({color:0xc38a37}));assembly.add(guide);for(const spec of data.roots){const m=spec.matrix;const a=new T.ArrowHelper(new T.Vector3(-m[0][0],-m[1][0],0),new T.Vector3(m[0][3],m[1][3],.062),.022,0x16975b,.005,.003);assembly.add(a)}await select('Cola');resize();}
init().catch(e=>{$('state').textContent='3D view unavailable; see the drawings below.';console.error(e)});
renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera)});
