# -*- coding: utf-8 -*-
# otonom/index.html: TOPPING karti v7 (haftalik tedarik, 3 kaset tabani, gecis rafi, buzluk yok) + STORE notu + problem defterleri
import io
P = r"C:\Users\Kemal\Desktop\Kemal\WEBSİTE\AUTOKITCH\otonom\index.html"
t = io.open(P, encoding='utf-8').read()
def rep(o, n, c=1):
    global t
    assert t.count(o) == c, 'A(%d): %s' % (t.count(o), o[:80])
    t = t.replace(o, n)

# 1) giris paragrafi
rep("Konsept: <b>tüm malzeme küp/parça</b>, <b>4 kaset hazne</b> + her birinin altında <b>motorlu hücreli çark + kendi çıkışı</b> + <b>döner-kayar tabla</b> + altta <b>4 dolu yedek kaset</b>; tüm kabin +3 °C. Kabin 70 × 197 × 84.</p>",
    "Konsept: <b>tüm malzeme küp/parça</b>, <b>4 kaset hazne</b> (3 taban × tek yükseklik 25 cm — kaset boyu raf ömrüne göre) + her birinin altında <b>motorlu hücreli çark + kendi çıkışı</b> + <b>döner-kayar tabla</b> + altta <b>geçiş rafı</b> (robot kaset takası) ; tüm kabin +3 °C, <b>buzluk YOK</b>; <b>soğutma grubu + elektrik EN ÜSTTE</b> (Kemal: erişilebilirlik). <b>Tedarik HAFTADA BİR</b>, eleman haftada bir gelir. Kabin 70 × 192 × ~55.</p>")
# 2) gorsel
rep('<img src="img/ist3_topping_detay_v6.png" alt="TOPPING istasyonu detay v6"', '<img src="img/ist3_topping_detay_v7.png" alt="TOPPING istasyonu detay v7"')
# 3) kaset hazneler satiri
rep("Kaset hazneler ×4</td><td style=\"padding:8px 0;vertical-align:top;border-bottom:1px solid #d7e8dc\">2×2 dizilim, birbirine <b>sıfır boşluk</b> (35×42×35 cm ≈ 50 L). <b>Kaset = 3 günlük stok:</b> kaşar ~20 kg (6,4 kg/gün — her pidede var), küp sucuk / kavurma / kuşbaşı 4-5 kg; dolum fırıncı teslimatıyla aynı sabah, 3 günde bir, yan kulplu, <b>üstten kaldırılarak çıkar</b>; her kasetin altında kendi çarkı. Kaset = bulaşık makinesinde yıkanan basit paslanmaz kutu.</td>",
    "Kaset hazneler ×4 — 3 taban, tek yükseklik 25 cm (✔ Kemal)</td><td style=\"padding:8px 0;vertical-align:top;border-bottom:1px solid #d7e8dc\"><b>Kural: kaset boyu = o malzemenin +3'te güvenli günü × günlük tüketim</b> (80 pide/gün). <b>BÜYÜK 35×42×25</b> (37 L) kaşar 15 kg = 2,3 gün · <b>ORTA 35×21×25</b> (18 L) sucuk 10 kg = haftalık tek kaset · <b>KÜÇÜK 17×21×25</b> (9 L) kavurma ve kuşbaşı 3,5 kg = 2,3 gün. Üst kat <b>70×42 tam dolu, sıfır boşluk</b>: sol yarı kaşar, sağ ön sucuk, sağ arka kavurma + kuşbaşı. Kaşar 3 parçaya bölündü: 15 kg hafif taşınır, malzeme sütunu alçak → topaklanma azalır. Yan kulp = <b>robot tutamağı</b>, üstten kaldırılır; her kasetin altında kendi çarkı (kaşarınki büyük, 80 g/porsiyon). Toplam <b>14 kaset</b> (kaşar 4 · sucuk 2 · kavurma 4 · kuşbaşı 4) — <b>kaset sayısı = haftalık parça + 1</b> (o an çalışan). Kaset = bulaşık makinesinde yıkanan basit paslanmaz kutu.</td>")
# 4) yedek kasetler -> gecis rafi
rep("Yedek kasetler ×4 (✔ Kemal)</td><td style=\"padding:8px 0;vertical-align:top;border-bottom:1px solid #d7e8dc\">Tablanın altında <b>4 DOLU yedek kaset</b> (üsttekilerin birebir aynısı, malzemeli). Kaset boşalınca uyarı → eleman kulptan çıkarır, doluyu takar (30 sn, sıfır kesinti); boşu yıkar-doldurur, yedek yuvasına koyar.</td>",
    "Geçiş rafı — robot takası (✔ Kemal)</td><td style=\"padding:8px 0;vertical-align:top;border-bottom:1px solid #d7e8dc\">Tablanın altı \"yedek deposu\" değil <b>geçiş rafı</b>, 2 kat: kat A 2 büyük (kaşar B, C) · kat B 1 büyük (kaşar D) + 1 orta (sucuk yedeği) + 2 küçük <b>çözülme yuvası</b>. Kasette \"boş\" sensörü: boşalınca <b>robot</b> üstteki boşu çıkarır, raftaki doluyu takar, boşu boş yuvaya koyar — saat önemsiz (1 saatte de bitse). Donmuş kavurma/kuşbaşı kasetini bitişten 1 gün önce STORE buzluğundan alıp çözülme yuvasına indirir (+3, 24 saat). <b>Eleman üst kata hiç uzanmaz</b>; haftada bir boşları toplar. Kabinde ekstra boş kaset stoğu yok, 14 kaset sirkülasyonla döner.</td><tr><td style=\"padding:8px 12px 8px 0;vertical-align:top;width:27%;font-weight:700;color:#1d7a4f;border-bottom:1px solid #d7e8dc\">Haftalık döngü (tedarik haftada 1)</td><td style=\"padding:8px 0;vertical-align:top;border-bottom:1px solid #d7e8dc\"><b>Uygulama mesajı:</b> BEYİN gerçek tüketimi ölçer, \"bu hafta kaşar 42 · sucuk 9 · kavurma 12 · kuşbaşı 8 kg al\" der. <b>Eleman gelir:</b> boşları toplar, yıkar, <b>poşetten kasete doldurur</b> (hiçbir şey kendi poşetinde durmaz): kaşar 3 dolu + sucuk yedeği + kavurma/kuşbaşının 1'i → geçiş rafı; kavurma/kuşbaşının 2'şer kaseti → STORE buzluğu (−18, ≈36 L). <b>Saat kuralı:</b> her kasetin takılma saati BEYİN'de — kaşar 14 gün, sucuk 7, kavurma/kuşbaşı 3,5 (1 gün çözülme + 2,3 gün çalışma = 3,3 ≤ raf ömrü); süresi dolan kaset dolu olsa da çıkar (kalan ≤1 kg). <b>Donmuş kasetin saati durur</b>: yavaş satışta buzlukta haftaya devreder, eleman eksiği kadar getirir; hızlı satışta robot sıradakini erken çözer, stok biterse kiosk o çeşidi kapatır (hamur gibi).</td>")
# 5) sogutma (EN USTTE) + tabla/cikis satiri
rep("Soğutma</td><td style=\"padding:8px 0;vertical-align:top;border-bottom:1px solid #d7e8dc\">Kabinin altında <b>25 cm</b>lik soğutma grubu",
    "Soğutma — EN ÜSTTE (✔ Kemal)</td><td style=\"padding:8px 0;vertical-align:top;border-bottom:1px solid #d7e8dc\"><b>Kabinin EN ÜSTÜNDE</b> 25 cm'lik soğutma grubu + 14 cm elektrik bölmesi = teknik bölme; servis üstten, kabin ve soğuk bölge açılmadan (üstten motorlu dolap mantığı), sıcak hava yukarı atılır, kaset katı 40 cm aşağı indiği için robot ve eleman erişimi kolaylaşır. Grup:")
rep("<b>tüm kabin +3 °C</b>, hazneler, çarklar, yedekler. En altta <b>elektrik bölmesi</b> (PLC I/O, 4 step sürücü, 24 V güç, tabla sürücüleri).",
    "<b>tüm kabin +3 °C</b>, hazneler, çarklar, geçiş rafı. <b>Buzluk YOK</b> — ikinci soğutma devresi, izoleli bölme ve defrost derdi TOPPING'e girmez; donmuş kasetler STORE'un mevcut −18 kolonunda bekler. Elektrik bölmesi (PLC I/O, 4 step sürücü, 24 V güç, tabla sürücüleri) soğutmanın hemen altında, yine üstte.")
rep("Ø40 tabla iki motorlu: <b>dönme</b> + kızakta <b>ileri-geri kayma</b>. <b>Her haznenin KENDİ çıkışı</b> (4 ayrı ağız, kasetlerin iç köşesinde — ortak nozül/boru YOK: malzeme karışmaz, tıkanacak boru yok, çıkış çarkla birlikte sökülür). Tabla aktif çıkışın altına kayar, dönerken malzeme <b>spiral</b> yağar, dış halka da orta da dolar.",
    "Ø36 tabla iki motorlu: <b>dönme</b> + kızakta <b>ileri-geri kayma</b> (merkez 18 → 52 cm). <b>Her haznenin KENDİ çıkışı</b> — 4 ayrı ağız, hepsi <b>tablanın kayma ekseni üzerinde</b> (±3 cm; x = 30 · 39 · 45,5 · 53,5 cm): rotor kendi kasetinin altında, koni malzemeyi eksene çeker, ortak nozül/boru YOK. Kasetler farklı boyda olduğu için çıkışlar simetrik değil ama gerekmiyor: tabla o çıkışın altına kayar, dönerken kayma devam eder → çıkış pide üstünde <b>merkezden kenara spiral</b> çizer (r 0-3 → 14 cm), orta da dış halka da dolar. Kural: kızak tek eksenli olduğu için çıkışlar eksenden en fazla 3 cm sapabilir.")
# 6) TOPPING problem defteri
rep("<li style=\"margin:3px 0\"><b style=\"color:#1d7a4f\">✔ ÇÖZÜLDÜ</b> — Hazne gün içinde boşalırsa: sayaç + eşik uyarısı — eleman hep dükkânda, doldurur.</li>",
    "<li style=\"margin:3px 0\"><b style=\"color:#1d7a4f\">✔ ÇÖZÜLDÜ</b> — Hazne gün içinde boşalırsa: \"boş\" sensörü → ROBOT geçiş rafındaki doluyu takar (saat önemsiz); eleman haftada bir doldurur.</li><li style=\"margin:3px 0\"><b style=\"color:#1d7a4f\">✔ ÇÖZÜLDÜ</b> — Yedek kaset raf ömrünü aşıyordu (3 gün bekle + 3 gün çalış = 6 gün, kavurma/kuşbaşı 3-4 gün dayanır): kaset boyu raf ömrüne göre küçüldü (2,3 günlük), ikinci-üçüncü kasetler STORE buzluğunda donmuş bekler, 1 gün önce çözülür. Sucuk 7 gün dayandığı için tek haftalık kaset; kaşar 14 gün, +3'te bekler.</li><li style=\"margin:3px 0\"><b style=\"color:#1d7a4f\">✔ ÇÖZÜLDÜ</b> — TOPPING'e buzluk lazım mı? HAYIR: ikinci soğutma devresi + izoleli duvar + defrost yerine STORE'un hazır −18 kolonu (4 küçük kaset ≈ 36 L).</li><li style=\"margin:3px 0\"><b style=\"color:#1d7a4f\">✔ ÇÖZÜLDÜ</b> — Kavurma az satıldı, kaset 3,5 günde bitmedi: saat kuralı çıkarır (kalan ≤1 kg fire), BEYİN sonraki hafta miktarı kısar; donmuş kasetler bozulmaz, haftaya devreder. Çok satıldı: robot sıradakini erken çözer, hepsi biterse kiosk o çeşidi kapatır.</li><li style=\"margin:3px 0\"><b style=\"color:#9a6b1f\">◐ ÖNERİ</b> — Kaşar 15 kg'lık kasette kendi ağırlığıyla topaklanma: sütun 25 cm'e indi; yine de pilotta test, gerekirse çark miline köprü kırıcı kanat.</li><li style=\"margin:3px 0\"><b style=\"color:#1d7a4f\">✔ ÇÖZÜLDÜ</b> — Kasetler farklı boyda olunca çıkışlar pidenin üstüne simetrik gelmiyordu (Kemal): 4 çıkış tablanın kayma ekseni üzerine dizildi (±3 cm), tabla kayar+döner → merkez dahil spiral; simetri gerekmez.</li><li style=\"margin:3px 0\"><b style=\"color:#1d7a4f\">✔ ÇÖZÜLDÜ</b> — Soğutma grubuna/elektriğe erişim (Kemal): teknik bölme EN ÜSTE alındı, servis üstten, kaset katı aşağı indi.</li><li style=\"margin:3px 0\"><b style=\"color:#b3452b\">○ AÇIK</b> — Robot 15 kg kaset + tutucu taşıyacak: kobot yük sınıfı ≥12 kg (UR16e / Fanuc CRX-20 sınıfı), kaset kulpu robot tutamağı, TOPPING üst/alt kapak motorlu-sensörlü — robot istasyonu turunda.</li>")
# 7) STORE: rezerv dondurucu satiri + problem defteri
rep("Altındaki boş kızaklar = büyüme payı (+2-4 raf).</td>",
    "Altındaki boş kızaklar = büyüme payı (+2-4 raf) — <b>bunun bir rafı TOPPING'in donmuş kasetlerine</b>: kavurma + kuşbaşı 2'şer küçük kaset (17×21×25, ≈36 L), eleman haftada bir koyar, robot bitişten 1 gün önce alıp TOPPING çözülme yuvasına indirir. TOPPING'e ayrı buzluk gerekmez.</td>")
rep("<li style=\"margin:3px 0\"><b style=\"color:#1d7a4f\">✔ ÇÖZÜLDÜ</b> — PRESS — çöp: 30 L poşetli kova, üstte huni (robot bırakır-geçer), motorsuz; eleman HER GÜN boşaltır.</li></ul></div>",
    "<li style=\"margin:3px 0\"><b style=\"color:#1d7a4f\">✔ ÇÖZÜLDÜ</b> — PRESS — çöp: 30 L poşetli kova, üstte huni (robot bırakır-geçer), motorsuz; eleman HER GÜN boşaltır.</li><li style=\"margin:3px 0\"><b style=\"color:#1d7a4f\">✔ ÇÖZÜLDÜ</b> — STORE buzluğu TOPPING'in donmuş kavurma/kuşbaşı kasetlerini de taşır (≈36 L, boş büyüme rafı) — robot erişimi hamurla aynı kapıdan.</li><li style=\"margin:3px 0\"><b style=\"color:#9a6b1f\">◐ ÖNERİ</b> — Soğutma grupları EN ÜSTTE olsun (Kemal, erişilebilirlik): kombine kasaların üstten motorlu versiyonu standart ürün; STORE çiziminin bir sonraki turunda makine dairesi üste, kuru sarf bandı yeniden yerleşir.</li></ul></div>")
# 8) kalan acik isler
rep("robot istasyonu (uç istasyonunun kesin yeri) · yerleşim planı (istasyonlar bitince).",
    "robot istasyonu (uç istasyonunun kesin yeri + kaset takası için kobot yük sınıfı) · yerleşim planı (istasyonlar bitince).")
io.open(P, 'w', encoding='utf-8', newline='\n').write(t)
print('site ok · v7 ref:', t.count('ist3_topping_detay_v7.png'), '· problem kutusu:', t.count('PROBLEM DEFTERİ'))

# PROBLEMLER.md (3_TOPPING)
M = r"C:\Users\Kemal\Desktop\Kemal\WEBSİTE\AUTOKITCH\arastirma\3_TOPPING\PROBLEMLER.md"
m = io.open(M, encoding='utf-8').read()
m = m.replace("Güncelleme: 31 Ağu 2026", "Güncelleme: 3 Eyl 2026 (v7 — haftalık tedarik)")
m = m.replace("| T5 | Hazne boşalması gün içinde | ÇÖZÜLDÜ | Sayaç + minimum eşikte eleman uyarısı (eleman hep dükkânda); hazneler 2-3 günlük |",
              "| T5 | Hazne boşalması gün içinde | ÇÖZÜLDÜ | Kasette boş sensörü → ROBOT geçiş rafındaki doluyu takar (saat önemsiz); eleman haftada bir doldurur |")
m = m.replace("| T6 | Dozaj mekanizması seçimi | AÇIK → KARAR AŞAMASI | Araştırma bitti: xPizza Cube (hazır) vs özel üçlü (titreşim+dilimleyici+vida) — Kemal kararı bekleniyor |",
              "| T6 | Dozaj mekanizması seçimi | ÇÖZÜLDÜ | Küp/parça malzeme + kaset hazne + motorlu hücreli çark, her hazne kendi çıkışı (Kemal konsepti v3-v6) |\n"
              "| T7 | Kuşbaşı çiğ hâlde 2-3 dk fırında pişmez | ÖNERİ VAR | Soteli/yarı pişmiş kuşbaşı (kavurma gibi) veya kuşbaşılı pideye ayrı uzun reçete |\n"
              "| T8 | Yedek kaset raf ömrünü aşıyor (3+3 = 6 gün; kavurma/kuşbaşı 3-4 gün) | ÇÖZÜLDÜ (v7) | Kaset boyu = raf ömrü × tüketim: kaşar 35×42×25 (15 kg, 2,3 g) · sucuk 35×21×25 (10 kg haftalık) · kavurma/kuşbaşı 17×21×25 (3,5 kg, 2,3 g); 2.-3. kasetler STORE −18'de, 1 gün önce çözülür |\n"
              "| T9 | TOPPING'e buzluk gerekir mi? | ÇÖZÜLDÜ (v7) | HAYIR — STORE'un mevcut −18 kolonu (≈36 L); TOPPING tek +3, 25 cm grup |\n"
              "| T10 | Kavurma az/çok satıldı (kaset erken/geç bitti) | ÇÖZÜLDÜ (v7) | Saat kuralı (kavurma/kuşbaşı 3,5 g) dolan kaseti çıkarır (≤1 kg fire); donmuş kasetin saati durur, haftaya devreder; çok satışta robot erken çözer, biterse kiosk çeşidi kapatır |\n"
              "| T11 | Kaşar 15 kg kasette topaklanma | ÖNERİ VAR | Sütun 25 cm'e indi; pilot testi, gerekirse çark miline köprü kırıcı kanat |\n"
              "| T12 | Robot 15 kg kaset takası — kobot yükü, kulp, kapaklar | AÇIK | Kobot ≥12 kg sınıfı (UR16e / CRX-20), kaset kulpu = robot tutamağı, üst/alt kapak motorlu-sensörlü — robot turu |\n"
              "| T13 | Farklı boy kasetlerde çıkışlar pideye simetrik gelmiyor | ÇÖZÜLDÜ (v7) | 4 çıkış tabla kayma ekseni üzerinde (±3 cm, x 30·39·45,5·53,5); tabla Ø36 kayar+döner → merkezden kenara spiral |\n"
              "| T14 | Soğutma/elektrik erişimi | ÇÖZÜLDÜ (v7) | Teknik bölme EN ÜSTTE (soğutma 25 + elektrik 14), servis üstten; diğer istasyonlarda da (STORE) aynı ilke |")
io.open(M, 'w', encoding='utf-8', newline='\n').write(m)
print('problemler.md ok')
