import fs from 'node:fs';import{T,C,matrix,rig,root,read,box,hits,intersects,robot,solid,update}from './geometry.mjs';import{environment,obstacles,products,productAt,tcpScene}from './world.mjs';import{env}from './layout_v11.mjs';import{clipGripNotch}from '../../../otonom/hat/robot-main-v1/grip-notch.js';
rig.setRailForward(.5);const grid=read('qr_grid_v13.json'),src=read('source_dense_v12.json'),delivery=read('qr_delivery_v15.json'),clone=structuredClone;
for(const product of Object.values(products))for(const p of product.parts){const ids=Array.from(new Set(p.g.index.array)),map=new Map(ids.map((id,i)=>[id,i])),v=[];for(const id of ids)v.push(p.g.attributes.position.getX(id),p.g.attributes.position.getY(id),p.g.attributes.position.getZ(id));const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(v,3));g.setIndex(Array.from(p.g.index.array,id=>map.get(id)));g.computeBoundingBox();p.g=g;p.bvh=null;p.box=g.boundingBox.clone().applyMatrix4(p.m);}
for(const o of obstacles.filter(o=>o.name==='E_KALIP__sac__NEST')){clipGripNotch(T,o.g,o.m);o.bvh=null;update(o,o.m);}
const target=[.8889701068401337,.2333323061466217,-.1979999989271164],old=products.Dough.centre,shift=target.map((v,i)=>v-old[i]);
const ds=obstacles.find(s=>s.name.startsWith('CEK_K1_lahm_1__hamur__')),pos=ds.g.attributes.position,ind=ds.g.index.array,keep=[],v=new T.Vector3();for(let i=0;i<ind.length;i+=3){v.set(0,0,0);for(let j=0;j<3;j++)v.add(new T.Vector3().fromBufferAttribute(pos,ind[i+j]).applyMatrix4(ds.m));v.multiplyScalar(1/3);if(!(v.x<.94&&v.z>-.24&&v.z<-.155))keep.push(...ind.slice(i,i+3));}ds.g.setIndex(keep);ds.bvh=null;const originalBall=solid('CEK_K1_lahm_1__old_product__CEKMECE',products.Dough.parts[0].g.clone(),new T.Matrix4().makeTranslation(...old));originalBall.initial=originalBall.m.clone();obstacles.push(originalBall);products.Dough.centre=target;

const base=obstacles.filter(o=>!o.name.startsWith('QR_')),cab=env(grid,2,850);

const record=read('order_v16.json');let checks=0,placedChecks=0,drawers={},carrying=null,local=null;const worldTCP=s=>C.clone().multiply(matrix(rig.tcp(s.q,s.rail,s.jaw)));
let failures=[];for(let i=0;i<record.trajectory.length;i++){const f=record.trajectory[i],s=f.state;drawers=f.drawers;environment(drawers,{});const obs=[...base,...cab],h=hits(s,obs);checks++;if(h.length){failures.push({frame:i,stage:f.stage,hit:h});break;}
const active=f.carrying||(/^(Box|Kutu)/.test(f.stage)?'Box':/^(Dessert|Tatlı)/.test(f.stage)?'Dessert':/^(Cola|İçecek)/.test(f.stage)?'Cola':'Dough');
if(f.carrying){const m=worldTCP(s);productAt(f.carrying,f.product,f.carrying==='Box'?Math.atan2(m.elements[8],m.elements[10]):0);for(const a of products[f.carrying].parts){for(const b of robot)if(!b.body.includes('/Gripper/')&&intersects(a,b))failures.push({frame:i,hit:'carried>'+b.body});for(const b of obs)if(intersects(a,b))failures.push({frame:i,hit:'carried>'+b.name});}}
for(const[k,pos]of Object.entries(f.placed)){productAt(k,pos);for(const a of products[k].parts){for(const b of robot){if(k===active&&b.body.includes('/Gripper/'))continue;placedChecks++;if(intersects(a,b))failures.push({frame:i,hit:'placed '+k+'>'+b.body});}if(f.carrying&&k!==f.carrying)for(const b of products[f.carrying].parts){placedChecks++;if(intersects(a,b))failures.push({frame:i,hit:'placed '+k+'>carried'});}}}if(failures.length)break;
if(i%2000===0)console.log('AUDIT',i,checks,placedChecks);}
const result={passed:!failures.length,frames:record.trajectory.length,checks,placedChecks,failures,sampled:true,continuous:false};fs.writeFileSync(root+'audit_v16.json',JSON.stringify(result,null,2));console.log(result);if(failures.length)process.exitCode=1;else{record.summary.geometric_audit='PASS sampled native robot, self, full machine and deposited products';fs.writeFileSync(root+'order_v16.json',JSON.stringify(record));}
