import fs from 'node:fs';
import {T,rig,poses,robot,box,hits,intersects,root} from './geometry.mjs';
import {obstacles as base,products,productAt} from './world.mjs';
const prev=JSON.parse(fs.readFileSync(root+'fixed_qr_reach_v5.json')),seeds=[...prev.results.flatMap(r=>r.tasks.filter(t=>t.passed).map(t=>t.state.q)),...Object.values(poses).map(p=>p.q)];
const fixedBase=base.filter(s=>!s.name.startsWith('QR_'));
function qr(L,f){const{x,width:w,front:z,depth:d,opening:h,wall:t}=L;return [box('FIXED_QR_FLOOR',[x,f-t,z],[x+w,f,z+d]),box('FIXED_QR_LEFT',[x-t,f-t,z],[x,f+h,z+d]),box('FIXED_QR_RIGHT',[x+w,f-t,z],[x+w+t,f+h,z+d]),box('FIXED_QR_ROOF',[x-t,f+h,z],[x+w+t,f+h+t,z+d]),box('FIXED_QR_BACK',[x-t,f,z+d],[x+w+t,f+h,z+d+t])];}
const target=(p,r)=>[...r[0],p[0],...r[1],p[1],...r[2],p[2],0,0,0,1];
function checks(state,key,pos,obs){const h=hits(state,obs);if(h.length)return h;productAt(key,pos,key==='Box'?Math.PI:0);for(const a of products[key].parts){for(const r of robot)if(!r.body.includes('/Gripper/')&&intersects(a,r))return ['product/arm'];for(const b of obs)if(intersects(a,b))return ['product/'+b.name];}return [];}
export function solve(L,mm){const f=mm/1000,obs=fixedBase.filter(s=>!L.ignore_workbench||!s.name.includes('TEZGAH')).concat(L.cabinet_parts||qr(L,f)),tasks=[],gap=L.gap,steps=L.samples||20;for(const key of ['Dessert','Cola','Box']){const bx=L.x+.17,bz=L.front+(L.boxInset||.17),cx=L.x+.33+gap+.0475,cz=L.front+(L.canInset||.08);const pos=key==='Cola'?[cx,f+.0585,cz]:key==='Dessert'?[cx,f+.031,cz+.0805+gap]:[bx,f+.0235,bz];for(const t of tasks.filter(t=>t.passed)){productAt(t.key,t.product,0);for(const a of products[t.key].parts)if(!obs.includes(a))obs.push(a);}const rawRotation=poses[key+'_place'].rotation,yaw=(L.yaw_deg||0)*Math.PI/180,c=Math.cos(yaw),sn=Math.sin(yaw),initialRotation=key==='Box'?rawRotation:[rawRotation[0].map((v,i)=>c*v-sn*rawRotation[1][i]),rawRotation[0].map((v,i)=>sn*v+c*rawRotation[1][i]),rawRotation[2]],jaw=poses[key+'_pick'].jaw+(key==='Dessert'?3:0),p=[pos[0],-pos[2]+(key==='Box'?.1516:0),pos[1]+(key==='Box'?.012:.014)];let passed=null,last=['IK'],rotation=initialRotation;outer:for(const choice of (L.forced_yaws?.[key]!=null?[L.forced_yaws[key]]:L.search_yaws&&key!=='Box'?[0,45,-45,90,-90,180]:[0]))for(const rail of (L.task_rails?.[key]||[p[0],p[0]-.15,p[0]+.15,p[0]-.3,p[0]+.3,p[0]-.4,p[0]+.4,p[0]-.65,p[0]+.65,p[0]-.85,p[0]+.85]).map(x=>Math.max(1.176,Math.min(4.86,x))))for(const seed of (L.task_seeds?.[key]||L.extra_seeds||seeds.slice(0,18))){const yy=choice*Math.PI/180,cc=Math.cos(yy),ss=Math.sin(yy);rotation=choice?[rawRotation[0].map((v,i)=>cc*v-ss*rawRotation[1][i]),rawRotation[0].map((v,i)=>ss*v+cc*rawRotation[1][i]),rawRotation[2]]:initialRotation;const a=rig.solve(target(p,rotation),rail,jaw,seed);if(!a.valid)continue;const state={q:a.q,rail,jaw};last=checks(state,key,pos,obs);if(last.length)continue;let ok=true,sequence=[],exit=[],q=a.q;for(let i=0;i<=steps;i++){const t=i/steps,pt=[p[0],p[1]+(key==='Box'?.36:key==='Dessert'?.30:.20)*t,p[2]+(key==='Box'?(L.box_lift_m||.06):(L.lift_m||.13))*Math.min(t*4,1)],r=rig.solve(target(pt,rotation),rail,jaw,q),s={q:r.q,rail,jaw},tcp=rig.tcp(r.q,rail,jaw),position=[tcp[3],tcp[11]-(key==='Box'?.012:.014),-tcp[7]+(key==='Box'?.1516:0)];if(!r.valid?(last=['entry IK'],true):(last=checks(s,key,position,obs)).length){ok=false;break;}sequence.push({state:s,product:position});q=r.q;}if(!ok)continue;q=a.q;for(let i=0;i<=steps;i++){const t=i/steps,pt=[p[0],p[1]+(key==='Box'?.36:key==='Dessert'?.30:.20)*t,p[2]+(key==='Box'?(L.box_lift_m||.06):(L.lift_m||.13))*Math.min(t*4,1)],open=Math.max(0,jaw-5),r=rig.solve(target(pt,rotation),rail,open,q),s={q:r.q,rail,jaw:open};if(!r.valid?(last=['exit IK'],true):(last=checks(s,key,pos,obs)).length){ok=false;break;}if(i>steps*.2){productAt(key,pos,key==='Box'?Math.PI:0);last=hits(s,products[key].parts);if(last.length){ok=false;break;}}exit.push({state:s,product:pos});q=r.q;}if(ok){passed={state,product:pos,sequence,exit,yaw_deg:choice};break outer;}}
 tasks.push({key,passed:!!passed,last:passed?[]:last,...passed});if(!passed)break;}
return {floor_mm:mm,passed:tasks.length===3&&tasks.every(t=>t.passed),tasks};}
if(process.argv[1]?.endsWith('compact_qr_v5.mjs')){let chosen=null;const attempts=[];
// Smallest footprint first; heights bounded by hand clearance. Stop at first verified option.
for(const width of [.48,.49,.50]){for(const opening of [.18,.20,.22,.24,.26]){const L={version:5,x:3.82,width,front:.85,depth:.34,opening,wall:.012,min_floor:.85,gap:.01};const a=solve(L,1050);attempts.push({config:L,...a});console.log('COMPACT',width,opening,a.passed,a.tasks.map(t=>t.key+':'+t.passed+':'+t.last).join(' '));fs.writeFileSync(root+'compact_qr_attempts_v5.json',JSON.stringify(attempts,null,2));if(a.passed){chosen={config:L,result:a};break;}}if(chosen)break;}
if(chosen){const results=[solve(chosen.config,850),chosen.result];for(const mm of [1100,1150,1200,1250,1300,1350,1450]){const a=solve(chosen.config,mm);results.push(a);console.log('HEIGHT',mm,a.passed,a.tasks.map(t=>t.key+':'+t.passed).join(' '));}const high=results.filter(r=>r.passed).at(-1)?.floor_mm||1050;fs.writeFileSync(root+'fixed_qr_reach_v5.json',JSON.stringify({config:chosen.config,method:'Compact bay search; native whole robot, full machine and earlier order products; 21 loaded entry and 21 open-finger exit samples; ideal grasp; no continuous certification',maximum_tested_floor_mm:1450,highest_passing_floor_mm:high,results,compact_search:true},null,2));console.log('CHOSEN',chosen.config);}else console.log('NO COMPACT PASS; retained previous verified bay');

}
