import fs from 'node:fs';import{T,C,matrix,rig,root,read,box,hits,intersects,robot,solid,update}from './geometry.mjs';import{environment,obstacles,products,productAt,tcpScene}from './world.mjs';import{env}from './layout_v11.mjs';rig.setRailForward(.5);
const target=[.8889701068401337,.2333323061466217,-.1979999989271164],old=products.Dough.centre,shift=target.map((v,i)=>v-old[i]);
const ds=obstacles.find(s=>s.name.startsWith('CEK_K1_lahm_1__hamur__')),pos=ds.g.attributes.position,ind=ds.g.index.array,keep=[],v=new T.Vector3();for(let i=0;i<ind.length;i+=3){v.set(0,0,0);for(let j=0;j<3;j++)v.add(new T.Vector3().fromBufferAttribute(pos,ind[i+j]).applyMatrix4(ds.m));v.multiplyScalar(1/3);if(!(v.x<.94&&v.z>-.24&&v.z<-.155))keep.push(...ind.slice(i,i+3));}ds.g.setIndex(keep);ds.bvh=null;const originalBall=solid('CEK_K1_lahm_1__old_product__CEKMECE',products.Dough.parts[0].g.clone(),new T.Matrix4().makeTranslation(...old));originalBall.initial=originalBall.m.clone();obstacles.push(originalBall);products.Dough.centre=target;

const grid=read('qr_grid_v13.json'),cab=env(grid,2,850),base=obstacles.filter(s=>!s.name.startsWith('QR_')),oldRecord=read('rail_animation_v12.json');
const stop=oldRecord.trajectory.findIndex(f=>f.stage.startsWith('Sağ kutu'));
const path=oldRecord.trajectory.slice(0,stop),fail=[];let checks=0;
for(const f of path){environment(f.drawers,{});const obs=[...base,...cab],h=hits(f.state,obs);checks++;if(h.length){fail.push({stage:f.stage,h});break;}if(f.carrying==='Dough'){productAt('Dough',f.product);for(const p of products.Dough.parts){for(const r of robot)if(!r.body.includes('/Gripper/')&&intersects(p,r))fail.push({stage:f.stage,h:['product/arm']});for(const o of obs)if(intersects(p,o))fail.push({stage:f.stage,h:['product/'+o.name]});}if(fail.length)break;}}
const result={version:15,passed:!fail.length,checks,rigid_dough:true,stock_count_unchanged:42,table_m:path.at(-1)?.placed.Dough,fail};fs.writeFileSync(root+'dough_v15.json',JSON.stringify({summary:result,trajectory:!fail.length?path:[] }));console.log(result);if(fail.length)process.exitCode=1;
