import fs from 'node:fs';
import {T,C,rig,poses,robot,machine,box,hits,intersects,update,root} from './geometry.mjs';
import {obstacles as base,products,productAt} from './world.mjs';
const config={version:5,x:3.78,width:.68,front:.85,depth:.50,opening:.46,wall:.012,min_floor:.85,step:.05};
export function parts(f){const {x,width:w,front:z,depth:d,opening:h,wall:t}=config;return [box('FIXED_QR_FLOOR',[x,f-t,z],[x+w,f,z+d]),box('FIXED_QR_LEFT',[x-t,f-t,z],[x,f+h,z+d]),box('FIXED_QR_RIGHT',[x+w,f-t,z],[x+w+t,f+h,z+d]),box('FIXED_QR_ROOF',[x-t,f+h,z],[x+w+t,f+h+t,z+d]),box('FIXED_QR_BACK',[x-t,f,z+d],[x+w+t,f+h,z+d+t])];}
const fixedBase=base.filter(s=>!s.name.startsWith('QR_'));
const seeds=[...Object.values(poses).map(p=>p.q),[-Math.PI,-1,-1.5,0,-.3,Math.PI/2]];
const target=(p,r)=>[...r[0],p[0],...r[1],p[1],...r[2],p[2],0,0,0,1];
function checks(state,key,pos,obs){const hit=hits(state,obs);if(hit.length)return hit;productAt(key,pos,key==='Box'?Math.PI:0);for(const p of products[key].parts){for(const r of robot)if(!r.body.includes('/Gripper/')&&intersects(p,r))return ['product/arm'];for(const b of obs)if(intersects(p,b))return ['product/'+b.name];}return [];}
const report=[];
// All three products share one stationary bay. Can and dessert behind the horizontal box.
for(const mm of [850,1050,1100,1150,1200,1250,1300,1450]){const f=mm/1000,obs=fixedBase.concat(parts(f)),tasks=[];for(const key of ['Dessert','Cola','Box']){const pos=key==='Cola'?[4.36,f+.060,.98]:key==='Dessert'?[4.36,f+.033,1.17]:[3.99,f+.025,1.075];for(const t of tasks.filter(t=>t.passed)){productAt(t.key,t.product,t.key==='Box'?Math.PI:0);for(const a of products[t.key].parts)if(!obs.includes(a))obs.push(a);}const r=poses[key+'_place'].rotation,jaw=key==='Dessert'?poses[key+'_pick'].jaw+3:poses[key+'_pick'].jaw,p=[pos[0],-pos[2]+(key==='Box'?.1516:0),pos[1]+(key==='Box'?.012:.014)];let passed=null,last='IK';outer:for(const rail of [p[0]-.85,p[0]-.65,p[0]-.4,p[0]+.4,p[0]+.65,p[0]+.85].map(v=>Math.min(4.86,Math.max(1.176,v))))for(const seed of seeds){const s=rig.solve(target(p,r),rail,jaw,seed);if(!s.valid)continue;const state={q:s.q,rail,jaw};last=checks(state,key,pos,obs);if(last.length)continue;let prev=s.q,sequence=[],ok=true;const offset=key==='Box'?[0,-.012,.1516]:[0,-.014,0];for(let i=0;i<=24;i++){const t=i/24,pt=[p[0],p[1]+(key==='Box'?.40:key==='Dessert'?.40:.25)*t,p[2]+(key==='Box'?.06:.13)*Math.min(t*4,1)],a=rig.solve(target(pt,r),rail,jaw,prev);if(!a.valid){ok=false;last=['entry IK'];break;}const ns={q:a.q,rail,jaw},tcp=rig.tcp(ns.q,rail,jaw),position=[tcp[3]+offset[0],tcp[11]+offset[1],-tcp[7]+offset[2]];last=checks(ns,key,position,obs);if(last.length){ok=false;break;}sequence.push({state:ns,product:position});prev=a.q;}if(ok){let exit=[],prevExit=state.q;for(let i=0;i<=24;i++){const t=i/24,pt=[p[0],p[1]+(key==='Box'?.40:key==='Dessert'?.40:.25)*t,p[2]+(key==='Box'?.06:.13)*Math.min(t*4,1)],open=Math.max(0,jaw-5),a=rig.solve(target(pt,r),rail,open,prevExit),ns={q:a.q,rail,jaw:open};if(!a.valid||checks(ns,key,pos,obs).length){ok=false;break;}if(i>4){productAt(key,pos,key==='Box'?Math.PI:0);if(hits(ns,products[key].parts).length){ok=false;break;}}exit.push({state:ns,product:pos});prevExit=a.q;}if(ok){passed={state,product:pos,sequence,exit};break outer;}}}
 tasks.push({key,passed:!!passed,last:passed?[]:last,...passed});}report.push({floor_mm:mm,passed:tasks.every(t=>t.passed),tasks});console.log(mm,tasks.map(t=>t.key+':'+t.passed+':'+JSON.stringify(t.last)).join(' '));}
const valid=report.filter(r=>r.passed),best=valid.at(-1)||null;fs.writeFileSync(root+'fixed_qr_reach_v5.json',JSON.stringify({config,method:'Coarse sweep plus 50 mm refinement; stationary shelf; native whole robot + full machine limits + already placed order products; 25 loaded entry and 25 open-gripper exit samples; ideal grasp; not continuous certification',maximum_tested_floor_mm:1450,highest_passing_floor_mm:best?.floor_mm||null,results:report},null,2));
// Export only real interaction surfaces. Everything else becomes dashed station envelopes.
const wanted=n=>/^(CEK_K1_lahm_1|CEK_K5_ic1_1|CEK_K6_tatli_1)__/.test(n)&&/CEKMECE/.test(n)||/BANTLI_TABLA|TABLA_BANT|__TABLA$|__NEST$/.test(n);
const selected=base.filter(s=>wanted(s.name));const limits=[];for(const prefix of ['A_','TOPPING','F_','K_','E_']){const ss=base.filter(s=>s.name.startsWith(prefix));if(ss.length){const bb=new T.Box3();for(const s of ss)bb.union(s.box);limits.push({name:prefix,min:bb.min.toArray(),max:bb.max.toArray()});}}
function compact(g){const ids=[...new Set(g.index.array)],map=new Map(ids.map((v,i)=>[v,i])),p=g.attributes.position;return {positions:ids.flatMap(i=>[p.getX(i),p.getY(i),p.getZ(i)]),indices:Array.from(g.index.array,v=>map.get(v))};}const meshes=selected.map(s=>({name:s.name,...compact(s.g),matrix:s.m.toArray()}));const stockProducts=Object.fromEntries(Object.entries(products).filter(([k])=>k!=='Box').map(([k,v])=>[k,{centre:v.centre,drawer:v.drawer,parts:v.parts.map(s=>({positions:Array.from(s.g.attributes.position.array),indices:Array.from(s.g.index.array)}))}]));fs.writeFileSync(root+'light_scene_v5.json',JSON.stringify({meshes,limits,stockProducts,stats:{retained_meshes:meshes.length,original_meshes:machine.length,robot_shell_bytes:fs.statSync(root+'ur10e_short.glb').size}}));console.log('LIGHT',meshes.length, 'BEST',best?.floor_mm);
