import fs from 'node:fs';
const js='otonom/hat/robot-main-v1/light-app.js',html='otonom/hat/makine_robot.html';
let s=fs.readFileSync(js,'utf8').replaceAll('light_scene_v12.json','light_scene_v14.json');
s=s.replace('await loadRailAnimation();','await loadRailAnimation(); await loadGripDemo();');
s+=`
let gripDemo,gripActive;
async function loadGripDemo(){gripDemo=await fetch(A+'grasp_v14.json').then(r=>r.json());$('grip-box').onclick=()=>showGrip('Box');$('grip-cola').onclick=()=>showGrip('Cola');$('grip-open').onclick=()=>gripStep(false);$('grip-close').onclick=()=>gripStep(true);showGrip('Box');}
function showGrip(key){playing=false;lastTime=0;gizmo.detach();current=null;gripActive=gripDemo.results.find(r=>r.key===key);orders.visible=false;railOrders.visible=false;qr.visible=false;state=structuredClone(gripActive.state);$('drawer').value=key==='Cola'?.7:0;for(const m of trayMeshes){m.position.copy(m.userData.closed);if(key==='Cola'&&m.name.startsWith('CEK_K5_ic1_1__')&&m.name.includes('CEKMECE'))m.position.z+=m.name.includes('CEKMECE_ARA')?.35:.7;}for(const [k,g]of Object.entries(pickGroups)){g.position.copy(g.userData.closed);g.quaternion.identity();g.position.z=g.userData.closedZ+(k==='Cola'&&key==='Cola'?.7:0);}pickGroups[key].position.set(...gripActive.product);const p=gripActive.product;camera.position.set(p[0]+.44,p[1]+.32,p[2]+.60);orbit.target.set(p[0],p[1]+.06,p[2]+.04);orbit.update();draw();$('status').textContent=key==='Box'?'Kutu: ön kenarı üst ve alt pedler kavrıyor · alt parmak için yatakta 80 mm erişim çentiği':'Kola: dik yaklaşım · pedler üst gövdenin iki yanında';$('result').textContent='İki tarafta ped/ürün teması var. Bu gösterim kavrama geometrisidir; gerçek tutma kuvveti veya yeni QR bırakma yolu doğrulanmadı.';}
function gripStep(closed){if(!gripActive)return;state=structuredClone(closed?gripActive.state:gripActive.path[0]);draw();$('status').textContent=(gripActive.key==='Box'?'Kutu':'Kola')+(closed?' · kavrama pozu':' · parmaklar açık');}
`;
s=s.replace('pickGroups[key].position.set(...gripActive.product);',"for(const m of trayMeshes){if(m.name.includes('on_seffaf')){m.material.transparent=true;m.material.opacity=.12;m.material.depthWrite=false;}}pickGroups[key].position.set(...gripActive.product);");
s=s.replace('camera.position.set(p[0]+.44,p[1]+.32,p[2]+.60)',"camera.position.set(p[0]+.44,p[1]+(key==='Cola'?.85:.42),p[2]+.60)");
fs.writeFileSync(js,s);
let h=fs.readFileSync(html,'utf8').replace('12 GÖZ · ALT RAF ERİŞİMİ','KUTU / KOLA · KAVRAMA').replace('light-app.js?v=13','light-app.js?v=14');
h=h.replace('<p id="rail-measure">','<button id="grip-box">Kutu tutuşu</button><button id="grip-cola">Kola tutuşu</button><button id="grip-open">Parmakları aç</button><button id="grip-close">Kavra</button><p>Önce doğru kavrama pozlarını incele. Aşağıdaki eski QR ve ray kayıtları düzeltilmiş kutu tutuşuyla henüz yeniden hesaplanmadı.</p><p id="rail-measure">');
fs.writeFileSync(html,h);
const a=JSON.parse(fs.readFileSync('otonom/hat3d/robot-main-v1/assembly.json'));a.version='v14';a.lightweight_scene='light_scene_v14.json';a.grip_geometry='grasp_v14.json';a.open.push('v14: corrected box source roll90deg, front edge upper/lower grip; both pads contactBox.80x105x33mm access notch in E nest under edge, preview only. Cola vertical source upper body contact both pads.21 sample opening/closing poses each source passed native environment/self; nonpad product collision0. Ideal pads/grasp; forces untested. Old QR12 and rail measurement paths remain historical and do not validate corrected box-grasp QR placement.');fs.writeFileSync('otonom/hat3d/robot-main-v1/assembly.json',JSON.stringify(a,null,2));
