import fs from 'node:fs';
const path='otonom/hat/robot-main-v1/light-app.js';let s=fs.readFileSync(path,'utf8');
s=s.replace("await loadRailAnimation(); await loadGripDemo();","await loadGripDemo(); await loadRailAnimation();");
s=s.replace("fetch(A+'rail_animation_v12.json')","fetch(A+'order_v15.json')");
const start=s.indexOf('for(const t of reach.results.find',s.indexOf('async function loadRailAnimation()'));
const end=s.indexOf('railFrame(0);}',start);
s=s.slice(0,start)+`$('rail-measure').textContent='Bir sipariş · '+d.completed.join(' / ')+' tamamlandı. İdeal tutuş ve rijit ürünler; tam makine, robot gövdesi ve sabit QR ile örneklenmiş çarpışma kontrolü. Gerçek kavrama/kuvvet testi değildir.';
const keys=d.completed,labels={Cola:'Kola → QR',Dessert:'Tatlı → QR',Box:'Kutu → QR',Dough:'Hamur → tabla'};
const options=document.getElementById('order-task');options.innerHTML='<option value="all">Bir sipariş · hepsi</option>'+keys.map(k=>'<option value="'+k+'">'+labels[k]+'</option>').join('');
options.onchange=()=>{playing=false;lastTime=0;const k=options.value;let i=0;if(k!=='all')i=railRecord.trajectory.findIndex(f=>({Cola:/^(Cola|İçecek)/,Dessert:/^(Dessert|Tatlı)/,Box:/^(Box|Kutu)/,Dough:/^(Dough|Hamur|En sol hamur)/}[k]).test(f.stage));i=Math.max(0,i);playTime=i/15;railFrame(i);};
$('summary').textContent='Makine ve tabla sabit. 12 gözlü QR sağda. Bu sipariş sağ sütunun 850 mm rafına bırakılıyor: kola arkada, tatlı önde, kutu solda. Kutu, alt parmağın çıkabilmesi için raf üzerinde 25 mm yüksekte açılıp ideal olarak rafa oturtuluyor.';
railFrame(0);}`+s.slice(end+'railFrame(0);}'.length);
s=s.replace('if(playTime*30>=railRecord.trajectory.length-1)','if(playTime*15>=railRecord.trajectory.length-1)');
s=s.replace("$('result').textContent='İki tarafta ped/ürün teması var. Bu gösterim kavrama geometrisidir; gerçek tutma kuvveti veya yeni QR bırakma yolu doğrulanmadı.';","$('result').textContent='Kaynak kavrama geometrisi. Sipariş oynatma düğmeleriyle taşıma ve bırakma hareketini inceleyebilirsin. İdeal tutuş; gerçek kuvvet testi yok.';");
fs.writeFileSync(path,s);
const html='otonom/hat/makine_robot.html';let h=fs.readFileSync(html,'utf8');
h=h.replace('KUTU / KOLA · KAVRAMA','BİR SİPARİŞ · ROBOT V15');
h=h.replace('Önce doğru kavrama pozlarını incele. Aşağıdaki eski QR ve ray kayıtları düzeltilmiş kutu tutuşuyla henüz yeniden hesaplanmadı.','Kola, tatlı ve kutu sırasıyla alınır ve aynı QR gözüne yerleştirilir. Hamur → tabla bölümü sıradaki çalışma. Serbest kamerayla inceleyebilirsin.');
h=h.replace('<p id="rail-measure">','<label>İzlemek istediğin görev</label><select id="order-task" aria-label="Sipariş görevi"></select><p id="rail-measure">');
h=h.replace('Hamur → tabla → pide → QR sağ göz','Sipariş hareket kaydı');
h=h.replace('Yerleştirme sırası: tatlı → içecek → kutu. Soluk ürünler sonraki adımın hedefidir. Boşluklar nominaldir; ürün ölçüsü değişimleri henüz eklenmedi.','Yerleştirme: kola arkaya, tatlı öne, kutu sola. Ürünler rijit ve ideal olarak tutuluyor. Tutuş hizası serbest koridorda ideal olarak ayarlanır; ürün kayması veya düşmesi simüle edilmiyor.');
h=h.replace('light-app.js?v=14','light-app.js?v=15');fs.writeFileSync(html,h);
