import fs from 'node:fs';import{T,C,matrix,rig,root,read,box,hits,intersects,robot,solid}from './geometry.mjs';import{environment,obstacles,products,productAt,tcpScene}from './world.mjs';import{env}from './layout_v11.mjs';
rig.setRailForward(.5);const grid=read('qr_grid_v11.json'),src=read('source_dense_v10.json'),clone=structuredClone;
const target=[.8889701068401337,.2333323061466217,-.1979999989271164],old=products.Dough.centre,shift=target.map((v,i)=>v-old[i]);
const ds=obstacles.find(s=>s.name.startsWith('CEK_K1_lahm_1__hamur__')),pos=ds.g.attributes.position,ind=ds.g.index.array,keep=[],v=new T.Vector3();for(let i=0;i<ind.length;i+=3){v.set(0,0,0);for(let j=0;j<3;j++)v.add(new T.Vector3().fromBufferAttribute(pos,ind[i+j]).applyMatrix4(ds.m));v.multiplyScalar(1/3);if(!(v.x<.94&&v.z>-.24&&v.z<-.155))keep.push(...ind.slice(i,i+3));}ds.g.setIndex(keep);ds.bvh=null;const originalBall=solid('CEK_K1_lahm_1__old_product__CEKMECE',products.Dough.parts[0].g.clone(),new T.Matrix4().makeTranslation(...old));originalBall.initial=originalBall.m.clone();obstacles.push(originalBall);products.Dough.centre=target;
let light=read('light_scene_v11.json');const lm=light.meshes.find(m=>m.name===ds.name);lm.indices=keep;const og=originalBall.g;light.meshes.push({name:originalBall.name,positions:Array.from(og.attributes.position.array),indices:Array.from(og.index.array),matrix:originalBall.m.toArray()});light.stockProducts.Dough.centre=target;light.version=12;light.stats.retained_meshes=light.meshes.length;fs.writeFileSync(root+'light_scene_v12.json',JSON.stringify(light));
const base=obstacles.filter(o=>!o.name.startsWith('QR_')),cab=env(grid,2,1374);for(const t of grid.results.find(r=>r.column===2&&r.floor_mm===1374).tasks.filter(t=>t.key!=='Box'))for(const a of products[t.key].parts)cab.push(solid('QR_ORDER_'+t.key,a.g.clone(),new T.Matrix4().makeTranslation(...t.product))); let checks=0,drawers={},carrying=null,local=null,placed={},frames=[],st=null;
const worldTCP=s=>C.clone().multiply(matrix(rig.tcp(s.q,s.rail,s.jaw))),point=s=>{if(!carrying)return null;return new T.Vector3(...local).applyMatrix4(worldTCP(s)).toArray();};
function check(s){checks++;environment(drawers,{});const obs=[...base,...cab],h=hits(s,obs);if(h.length)return h;if(carrying){const p=point(s);productAt(carrying,p,carrying==='Box'?Math.atan2(worldTCP(s).elements[8],worldTCP(s).elements[10]):0);for(const a of products[carrying].parts){for(const b of robot)if(!b.body.includes('/Gripper/')&&intersects(a,b))return ['PRODUCT>'+b.body];for(const b of obs)if(intersects(a,b))return ['PRODUCT>'+b.name];}}return [];}
const angle=x=>Math.atan2(Math.sin(x),Math.cos(x)),mix=(a,b,t)=>({q:a.q.map((q,i)=>q+angle(b.q[i]-q)*t),rail:a.rail+(b.rail-a.rail)*t,jaw:a.jaw+(b.jaw-a.jaw)*t});
function frame(s,label){st=clone(s);const h=check(st);if(h.length)throw Error(label+' '+h);frames.push({state:clone(st),stage:label,drawers:clone(drawers),carrying,product:point(st),placed:clone(placed)});}
function edge(a,b,d=.025){const n=Math.max(1,Math.ceil(Math.max(...a.q.map((q,i)=>Math.abs(angle(b.q[i]-q))))/d),Math.ceil(Math.abs(a.rail-b.rail)/.01));for(let i=0;i<=n;i++)if(check(mix(a,b,i/n)).length)return false;return true;}
function append(b,label){const a=clone(st),n=Math.max(24,Math.ceil(Math.max(...a.q.map((q,i)=>Math.abs(angle(b.q[i]-q))))/.04),Math.ceil(Math.abs(a.rail-b.rail)/.012));for(let i=1;i<=n;i++){const t=i/n;frame(mix(a,b,t*t*(3-2*t)),label);}}
function connect(b,label){console.log('CONNECT',label,'goal',check(b));if(edge(st,b)){append(b,label);return;}if(!process.argv.includes('--resume-box')){const qs=[[0,-1.4,1.4,-Math.PI/2,-Math.PI/2,0],[0,-1.8,1.8,-Math.PI/2,-Math.PI/2,0],[Math.PI,-1.4,1.4,-Math.PI/2,-Math.PI/2,0],[Math.PI,-1.8,1.8,-Math.PI/2,-Math.PI/2,0],[-Math.PI/2,-2,2.2,0,-Math.PI/2,0],[-Math.PI/2,-2,2.5,.5,-Math.PI/2,0],[Math.PI/2,-2,2.2,0,-Math.PI/2,0]];for(const q of qs){let a={q,rail:st.rail,jaw:st.jaw},c={q,rail:b.rail,jaw:b.jaw};if(!check(a).length&&!check(c).length&&edge(st,a)&&edge(a,c)&&edge(c,b)){append(a,label+' · kolu topla');append(c,label+' · rayda ilerle');append(b,label+' · yaklaş');return;}}if(carrying==='Box'){const begin=clone(st),m0=rig.tcp(begin.q,begin.rail,begin.jaw),m1=rig.tcp(b.q,b.rail,b.jaw);for(const z of [1.15,1.05,1.3])for(const y of [1.4,1.55,1.25])for(const x of [4.75,4.9,4.55]){let a,c;try{let ma=m0.slice(),mc=m1.slice();ma[3]=mc[3]=x;ma[7]=mc[7]=-z;ma[11]=mc[11]=y;a=solveTCP(ma,4.6,begin.jaw,begin.q);c=solveTCP(mc,4.6,b.jaw,b.q);}catch{continue;}if(!check(a).length&&!check(c).length&&edge(begin,a)&&edge(a,c)&&edge(c,b)){console.log('BOX_CORRIDOR',x,y,z);append(a,label+' · boş koridora çık');append(c,label+' · yatay yönlen');append(b,label+' · girişe yaklaş');return;}}}}const begin=clone(st);let random=73537,rand=()=>{random=(random*1664525+1013904223)>>>0;return random/4294967296;},trees=[[{s:begin,parent:-1}],[{s:b,parent:-1}]],side=0;const dist=(a,b)=>Math.hypot(...a.q.map((q,i)=>angle(b.q[i]-q)),2*(a.rail-b.rail));const extend=(tree,goal)=>{let ix=0,d=Infinity;tree.forEach((v,i)=>{const dd=dist(v.s,goal);if(dd<d){d=dd;ix=i;}});const next=mix(tree[ix].s,goal,Math.min(1,.45/d));if(!edge(tree[ix].s,next,.04))return null;tree.push({s:next,parent:ix});return tree.length-1;},chain=(tr,i)=>{let arr=[];while(i>=0){arr.push(tr[i].s);i=tr[i].parent;}return arr.reverse();};for(let n=0;n<1500;n++){let A=trees[side],B=trees[1-side],goal=n%4===0?B[0].s:{q:Array.from({length:6},()=>rand()*2*Math.PI-Math.PI),rail:4.2+rand()*.563,jaw:begin.jaw};let i=extend(A,goal);if(i!=null)for(let k=0;k<30;k++){let j=extend(B,A[i].s);if(j==null)break;if(dist(B[j].s,A[i].s)<1e-6){let route=side===0?[...chain(A,i),...chain(B,j).reverse()]:[...chain(B,j),...chain(A,i).reverse()];for(let u=0;u<40;u++){const x=Math.floor(rand()*(route.length-2)),y=x+2+Math.floor(rand()*(route.length-x-2));if(edge(route[x],route[y]))route.splice(x+1,y-x-1);}if(!route.every((v,i)=>!i||edge(route[i-1],v,.025)))break;console.log('RRT_FOUND',n,route.length);for(const s of route.slice(1))append(s,label+' · denetlenen geçiş');return;}}side=1-side;if(n%100===99)console.log('RRT',n,trees.map(t=>t.length));}throw Error('Transit not found '+label);}
function solveTCP(m,rail,jaw,seed){let a=rig.solve(m,rail,jaw,seed);if(!a.valid)for(const q of [...Object.values(read('poses_v10.json')).map(v=>v.q),[0,-1.8,1.8,-1.57,-1.57,0],[3.14,-1.8,1.8,-1.57,-1.57,0]]){a=rig.solve(m,rail,jaw,q);if(a.valid)break;}if(!a.valid)throw Error('IK');return{q:a.q,rail,jaw};}
function attach(key,p){carrying=key;local=new T.Vector3(...p).applyMatrix4(worldTCP(st).invert()).toArray();}
function retargetDoughPick(){const r=src.results.find(r=>r.key==='Dough_pick');let last=[];for(const dr of [-.539,-.45,-.35,-.25,0,.15]){let path=[],q=r.path[0].state.q,okay=true;for(const f of r.path){drawers=f.drawers;let m=rig.tcp(f.state.q,f.state.rail,f.state.jaw).slice();m[3]+=shift[0];m[7]-=shift[2];let s;try{s=solveTCP(m,f.state.rail+dr,Math.max(16.8,f.state.jaw),q);}catch{last=['IK'];console.log('PICK_FAIL',dr,f.stage,m[3],m[7],m[11]);okay=false;break;}const h=check(s);if(h.length){last=h;console.log('PICK_HIT',dr,f.stage,h);okay=false;break;}path.push({...f,state:s});q=s.q;}if(okay){console.log('FAR_DOUGH_PICK',dr,path.length);return path;}}throw Error('Far dough '+last);}
if(process.argv.includes('--finalize')){const d=read('rail_animation_v12.json'),initial=d.trajectory[0];if(initial.stage==='Hamur çekmecesini otomatik aç')process.exit(0);for(let i=0;i<=25;i++){drawers={'CEK_K1_lahm_1':.7*i/25};frame(initial.state,'Hamur çekmecesini otomatik aç');}d.trajectory=[...frames,...d.trajectory];d.summary.frames=d.trajectory.length;d.summary.checks+=checks;d.summary.rear_rows_not_audited=true;fs.writeFileSync(root+'rail_animation_v12.json',JSON.stringify(d));process.exit(0);}
try{
const saved=process.argv.includes('--resume-box')&&fs.existsSync(root+'rail_animation_v12.partial.json')?read('rail_animation_v12.partial.json'):null;if(saved){({drawers,carrying,local,placed,frames,st}=saved);}else {
const pick=retargetDoughPick();carrying=null;for(let i=0;i<=25;i++){drawers={'CEK_K1_lahm_1':.7*i/25};frame(pick[0].state,'Hamur çekmecesini otomatik aç');}for(const f of pick){drawers=f.drawers;if(f.carrying&&!carrying){st=f.state;attach('Dough',tcpScene(st).map((v,i)=>v+f.offset[i]));}frame(f.state,'En sol hamur · '+f.stage);}
// Close only after withdrawal, then fixed ideal grasp is preserved throughout.
for(let i=1;i<=25;i++){drawers={'CEK_K1_lahm_1':.7*(1-i/25)};frame(st,'Hamur çekmecesini kapat');}
const place=src.results.find(r=>r.key==='Dough_place'),path=place.path;
drawers={};connect(path[0].state,'Hamuru soldaki tablaya taşı');const newLocal=new T.Vector3(...tcpScene(st).map((v,i)=>v+path[0].offset[i])).applyMatrix4(worldTCP(st).invert()).toArray(),prior=local;for(let i=1;i<=20;i++){local=prior.map((v,k)=>v+(newLocal[k]-v)*i/20);frame(st,'Tabla yaklaşımında ideal tutuş hizası');}for(const f of path){if(!f.carrying&&carrying){placed.Dough=point(st);carrying=null;}frame(f.state,f.stage);}
const boxpath=src.results.find(r=>r.key==='Box_pick').path;connect(boxpath[0].state,'Sağ kutu alma yerine git');for(const f of boxpath){if(f.carrying&&!carrying){st=f.state;const p=tcpScene(st).map((v,i)=>v+f.offset[i]);attach('Box',p);}frame(f.state,f.stage);}
fs.writeFileSync(root+'rail_animation_v12.partial.json',JSON.stringify({drawers,carrying,local,placed,frames,st}));}
const qr=grid.results.find(r=>r.column===2&&r.floor_mm===1374).tasks.find(t=>t.key==='Box'),delivery=[...qr.sequence].reverse();
connect(delivery[0].state,'Pide kutusunu QR sağ üst göze taşı');const boxLocal=new T.Vector3(...delivery[0].product).applyMatrix4(worldTCP(st).invert()).toArray(),prevLocal=local;for(let i=1;i<=20;i++){local=prevLocal.map((v,k)=>v+(boxLocal[k]-v)*i/20);frame(st,'QR yaklaşımında ideal kutu hizası');}for(const f of delivery)frame(f.state,'QR sağ üst · kutuyu yerleştir');placed.Box=point(st);carrying=null;for(const f of qr.exit)frame(f.state,'QR sağ üst · parmakları aç ve geri çık');
let min=Math.min(...frames.map(f=>f.state.rail)),max=Math.max(...frames.map(f=>f.state.rail));const summary={version:12,passed:true,ideal_grasp:true,continuous_collision_certified:false,frames:frames.length,checks,carriage_min_mm:Math.floor(min*1000),carriage_max_mm:Math.ceil(max*1000),required_stroke_mm:Math.ceil((max-min)*1000),end_allowance_each_mm:240,geometric_rail_length_mm:Math.ceil((max-min)*1000)+480,recommended_extra_stop_margin_each_mm:50,recommended_rail_length_mm:Math.ceil((max-min)*1000)+580,rail_start_m:min-.24,rail_end_m:max+.24,dough_left_column_m:target,table_m:placed.Dough,box_qr_m:placed.Box,method:'Collision sampled native robot/full fixed machine+QR; ideal grasp with explicit small grip alignment adjustment in free corridor. Feasible animated path envelope, not global minimum or hardware end-stop design.'};fs.writeFileSync(root+'rail_animation_v12.json',JSON.stringify({summary,trajectory:frames}));console.log('COMPLETE',summary);
}catch(e){console.error(e.stack);fs.writeFileSync(root+'rail_animation_v12_error.json',JSON.stringify({error:e.message,frames:frames.length,last:frames.at(-1),checks},null,2));process.exitCode=1;}
