import fs from 'node:fs';
import {Rig} from '../../../otonom/hat/robot-main-v1/rig.js';
import {rig,poses,root,read,hits,robot,intersects} from './geometry.mjs';
import {obstacles,environment,products,productAt} from './world.mjs';
const original=new Rig(read('rig.json'),{mountForward:.1}),record=read('order_trajectory_v4.json');
const labels={Dough_pick:'Hamur',Cola_pick:'İçecek',Dessert_pick:'Tatlı',Box_pick:'Pide kutusu',Dough_place:'Hamur'};
const blocks={};for(const [k,label]of Object.entries(labels)){const relevant=record.trajectory.filter(f=>f.stage.startsWith(label+' · ')&&(k.endsWith('place')?/hedefe yaklaş$|bırak$|elini geri çek$/.test(f.stage):/ · yaklaş$| · kavra$| · kaldır$| · çekmeceden uzaklaş$| · önden yatay çıkar$/.test(f.stage)));const step=Math.max(1,Math.floor(relevant.length/30));blocks[k]=relevant.filter((f,i)=>i%step===0||i===relevant.length-1);}
const obs=obstacles.filter(s=>!s.name.startsWith('QR_')&&!s.name.includes('TEZGAH'));
function check(s,f){const h=hits(s,obs);if(h.length)return h;if(f.carrying){const key=f.carrying,m=original.tcp(f.state.q,f.state.rail,f.state.jaw),pos=[m[3]+f.offset[0],m[11]+f.offset[1],-m[7]+f.offset[2]];productAt(key,pos,f.carried_yaw||0);for(const p of products[key].parts){for(const b of robot)if(!b.body.includes('/Gripper/')&&intersects(p,b))return ['product/robot'];for(const b of obs)if(intersects(p,b))return ['product/'+b.name];}}return [];}
export function sourceTest(delta,samples=30){rig.setRailForward(delta/1000);let results=[];for(const [key,all]of Object.entries(blocks)){const frames=samples>=100?record.trajectory.filter(f=>f.stage.startsWith(labels[key]+' · ')&&(key.endsWith('place')?/hedefe yaklaş$|bırak$|elini geri çek$/.test(f.stage):/ · yaklaş$| · kavra$| · kaldır$| · çekmeceden uzaklaş$| · önden yatay çıkar$/.test(f.stage))):all;let found=null,last=['IK'];outer:for(const shift of [0,-.2,.2,-.4,.4,-.6,.6]){let q=frames[0].state.q,path=[];for(const f of frames){environment(f.drawers,{});const p=original.tcp(f.state.q,f.state.rail,f.state.jaw),rail=Math.max(1.176,Math.min(4.86,f.state.rail+shift));let a=rig.solve(p,rail,f.state.jaw,q);if(!a.valid)a=rig.solve(p,rail,f.state.jaw,f.state.q);if(!a.valid){last=['IK',f.stage,a.position,a.angle];continue outer;}const state={q:a.q,rail,jaw:f.state.jaw};last=check(state,f);if(last.length){if(delta===0&&shift===0)console.log('BASELINE_HIT',key,f.stage,last);continue outer;}path.push({state,stage:f.stage,drawers:f.drawers,carrying:f.carrying,offset:f.offset,placed:f.placed});q=a.q;}found={key,passed:true,path,samples:path.length,pose:path.find(f=>f.stage.endsWith('kavra'))?.state||path.find(f=>f.stage.endsWith('bırak'))?.state||path[0].state};break;}results.push(found||{key,passed:false,last});if(!found)break;}environment({},{});return {rail_shift_mm:delta,passed:results.length===5&&results.every(r=>r.passed),results,method:'Retargeted recorded local source approaches/lifts and dough table delivery/retreat; fixed machine/product/native-self sampled checks. Transit between tasks not yet replanned.'};}
