import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';import{compileOrder,frameAt,planDemand,validateMotionContract,durations}from'../../../otonom/hat/robot-main-v1/workflow-v16.js';import{scenarioOrders,defaultDemand}from'../../../otonom/hat/robot-main-v1/demand-v16.js';
const root='otonom/hat3d/robot-main-v1/',read=n=>JSON.parse(fs.readFileSync(root+n)),r=read('order_v16.json'),c=read('workflow_v16.json'),audit=read('audit_v16.json');assert(audit.passed);assert.equal(audit.frames,r.trajectory.length);assert.deepEqual(validateMotionContract(r,c),[]);
const stages=r.trajectory.map(f=>f.stage),geometry=r.trajectory.map(({time_s,tcp_cap_m_s,...f})=>f),hash=crypto.createHash('sha256').update(JSON.stringify(geometry)).digest('hex');
r.summary.geometric_audit='PASS: new cubic pose samples checked against native full machine, self and deposited products; subsequent changes alter timestamps only';r.summary.geometry_sha256=hash;fs.writeFileSync(root+'order_v16.json',JSON.stringify(r));
const results=[];
for(const scenario of ['tek','uc','aksam','cmt','surekli']){const a=scenarioOrders({...defaultDemand,scenario}),b=scenarioOrders({...defaultDemand,scenario});assert.deepEqual(a,b);const plan=planDemand(a,c,r),robot=plan.events.filter(e=>e.resource==='robot');for(let i=1;i<robot.length;i++)assert(robot[i].start_s>=robot[i-1].end_s-1e-8);assert.equal(plan.jobs.length,a.length);assert(plan.jobs.every(j=>j.complete_s>=j.arrival_s));for(let bay=0;bay<12;bay++){const jobs=plan.jobs.filter(j=>j.bay===bay);for(let i=1;i<jobs.length;i++)assert(jobs[i].admitted_s>=jobs[i-1].complete_s+150-1e-8);}results.push({scenario,...plan.summary});}
assert.equal(results.find(r=>r.scenario==='aksam').orders,53);assert.equal(results.find(r=>r.scenario==='cmt').orders,74);
for(const recipe of c.recipes){const o=compileOrder(r,recipe),events=o.events.filter(e=>e.time_s!==null);for(let i=1;i<events.length;i++)assert(events[i].time_s>=events[i-1].time_s);if(recipe.processing_after_dough_s===null){assert(o.gate);assert.equal(o.gate.event,'machine.box_ready');}else{assert.equal(o.gate,null);assert(o.summary.machine_ready_s<=o.trajectory.find(f=>f.stage==='Kutu · ön kenara yaklaş').time_s+1e-8);}}
for(const f of r.trajectory){const s=frameAt(r,f.time_s);assert(Math.abs(r.trajectory[s.index].time_s-f.time_s)<1e-8);}
assert(r.summary.speed_audit.speed<=1);assert(r.summary.speed_audit.acc<=1);
const toIsaac=p=>[p[0],-p[2],p[1]],handoff={schema:'autokitch.isaac.handoff/1',motion_file:'order_v16.json',geometry_sha256:hash,workflow_file:'workflow_v16.json',joint_order:c.phase_schema.joint_order,units:{joint:'rad',rail:'m',time:'s',jaw:'deg'},coordinates:'Isaac Z-up SI; q native USD axes',trajectory_actor_coordinates:'Product/placed positions are web Y-up metres: convert [x,y,z] to [x,-z,y] for Isaac',controller_interpolation:'Dense desired joint samples, finite-difference velocity/acceleration audit; actual actuator interpolation and torque not certified',mount:{rail_forward_m:.5,mount_forward_m:.1},targets_isaac_m:{table:toIsaac(c.targets.table),qr:Object.fromEntries(Object.entries(c.targets.qr.products).map(([k,p])=>[k,toIsaac(p)]))},phases:r.phases.map(p=>({name:p.stage,start_s:p.start_s,end_s:p.start_s+p.duration_s,frame_start:p.frame_start,frame_end:p.frame_end,tcp_cap_m_s:p.tcp_cap_m_s})),events:c.phase_schema.checkpoints,ideal_contact:true,physics_tasks_remaining:['rebuild grip friction/compliance','validate actual object attachment via contact, not world transforms','verify grasp and release sensor acknowledgements','verify controller velocity/acceleration and collision during interpolation'],integration:'Transform named fixtures to completed Claude machine coordinate frame; rerun collision audit if any fixture moves; do not infer new grasps from this visual demonstration.',limits:c.limits,load_profiles:results};fs.writeFileSync(root+'isaac_handoff_v16.json',JSON.stringify(handoff,null,2));fs.writeFileSync(root+'workflow_audit_v16.json',JSON.stringify({passed:true,geometry_hash:hash,speed:r.summary.speed_audit,profiles:results,checks:['deterministic arrivals','53/74 archived profiles','single robot no overlap','QR occupancy release','machine readiness gate','SI joint contract','monotonic time and binary seeking']},null,2));console.log('PASS',r.summary.duration_s,'s',results.map(r=>[r.scenario,r.orders]));
