import * as T from 'three';
import {GLTFLoader} from './vendor/GLTFLoader.js';
import {OrbitControls} from './vendor/OrbitControls.js';
import {Rig,mul,flat} from './rig.js';
const $=x=>document.getElementById(x),base='../../../hat3d/rochu-sabit-v2/';
const scene=new T.Scene();scene.background=new T.Color('#e3e7df');
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;$('view').prepend(renderer.domElement);
const camera=new T.PerspectiveCamera(37,1,.003,80),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=.05;controls.maxDistance=16;
scene.add(new T.HemisphereLight(0xfafff0,0x616950,2.1));for(const [col,pos] of [[0xfff5dd,[3,6,4]],[0xe2ecff,[-2,2,-3]]]){let l=new T.DirectionalLight(col,2.4);l.position.set(...pos);scene.add(l);}
let floor=new T.Mesh(new T.PlaneGeometry(14,10),new T.MeshStandardMaterial({color:0xd3d9cb}));floor.rotation.x=-Math.PI/2;floor.position.set(3,-.035,1);scene.add(floor);
const target=new T.Mesh(new T.TorusGeometry(.013,.0007,8,40),new T.MeshBasicMaterial({color:0xf26744}));target.rotation.x=Math.PI/2;scene.add(target);
const cutLines=new T.Group();scene.add(cutLines);
const C=[1,0,0,0,0,0,1,0,0,-1,0,0,0,0,0,1],mat=a=>new T.Matrix4().set(...a.flat());
let model,head,original,rig,review,definition,manifest,item='Dough',mode='place',variant='edge',time=0,playing=false,view='close',ready=false,lastStamp=0,lastIndex=-1,followPoint=null;
const nodes=new Map(),tips=[],changed=[],originalColours=new WeakMap();
async function glb(name){let r=await fetch(base+name+'.glb.gz',{cache:'no-store'});if(!r.ok)throw Error(name+': '+r.status);let b=await new Response(r.body.pipeThrough(new DecompressionStream('gzip'))).arrayBuffer();return (await new GLTFLoader().parseAsync(b,location.href)).scene;}
function soften(shift){for(const t of tips){const a=t.mesh.geometry.attributes.position;for(let i=0;i<a.count;i++){let w=T.MathUtils.clamp((t.v[i*3+2]+.073-.085)/.0202,0,1);w=w*w*(3-2*w);a.setXYZ(i,t.v[i*3]-shift*.001*w,t.v[i*3+1],t.v[i*3+2]);}a.needsUpdate=true;t.mesh.geometry.computeVertexNormals();t.mesh.geometry.computeBoundingSphere();}}
function sequence(){return review.sequences[item==='Box'?'Box_'+variant:item+'_'+mode];}
function frameAt(t){let s=sequence(),x=t*(s.frames.length-1),i=Math.min(Math.floor(x),s.frames.length-1),j=Math.min(i+1,s.frames.length-1),u=x-i;return {s,a:s.frames[i],b:s.frames[j],u,i};}
function cameraView(kind){view=kind;if(!ready)return;let f=frameAt(time).a,c=followPoint?followPoint.clone():new T.Vector3(...f.pose.contact),aim=c.clone().add(new T.Vector3(0,.07,0)),eye;
 if(kind==='shop'){aim.set(2.8,.8,.7);eye=new T.Vector3(7.5,4.8,6.8);}else if(kind==='hand')eye=aim.clone().add(new T.Vector3(.23,.14,.23));else eye=aim.clone().add(new T.Vector3(.65,.43,.63));camera.position.copy(eye);controls.target.copy(aim);camera.lookAt(aim);controls.update();}
function translucency(){if(!model)return;model.traverse(o=>{if(!o.isMesh)return;let g=o.parent;while(g&&g.parent!==model)g=g.parent;if(g?.name.startsWith('UR10E')||g?.name.startsWith('Product_'))return;for(let m of [].concat(o.material)){m.transparent=$('ghost').checked;m.opacity=$('ghost').checked?.22:1;m.depthWrite=!$('ghost').checked;m.needsUpdate=true;}});}
function highlight(f){let hits=[...(f.check?.tool_hits||[]),...(f.check?.product_hits||[])],names=new Set(hits.flatMap(h=>[h.part,h.moving]));if(item==='Box'&&!$('slots').checked)names.clear();const paint=(o,bad)=>{if(!o?.isMesh)return;for(let m of [].concat(o.material)){if(!originalColours.has(m))originalColours.set(m,m.color.getHex());m.color.setHex(bad?0xe54b3d:originalColours.get(m));}};for(let x of manifest)paint(nodes.get(x.node),names.has(x.source));head.traverse(o=>{if(o.isMesh&&!o.userData.reviewMaterial){o.material=Array.isArray(o.material)?o.material.map(m=>m.clone()):o.material.clone();o.userData.reviewMaterial=true;}paint(o,names.has(o.name));});}
function info(f,s){const p=f.pose,a=f.check||{},hits=(a.tool_hits||[]).length+(a.product_hits||[]).length,comparison=item==='Box'&&!$('slots').checked;let bad=!p.valid||hits>0;let label=s.warning||'';if(!p.valid)label='Robot bu hedefe ulaşmıyor. '+label;else if(hits)label='Bu adımda '+hits+' kesişme adayı var. '+label;if(comparison)label='Orijinal taşıyıcı gösteriliyor; kesilmiş taşıyıcının denetimi bu görünüm için geçerli değil. '+label;$('status').textContent=comparison?'Orijinal destek · karşılaştırma':bad?'Bu adım temiz değil':s.grasp_verified?'Örnek poz temiz':'Yerel poz temiz · kavrama onaysız';$('status').classList.toggle('good',!bad&&!comparison);$('finding').textContent=f.label;$('description').textContent=s.description;$('measure').textContent=item==='Box'?s.contact_summary:(s.measure||'—');$('measureLabel').textContent=item==='Box'?'Son pozda dış temas adayı / dört parmak':s.measure_label||'Ölçülen deneme';$('notice').textContent=label;$('notice').classList.toggle('hidden',!label);$('phase').textContent=f.label;target.position.set(...p.contact);target.visible=!p.valid;}
function draw(){if(!ready)return;let {s,a,b,u,i}=frameAt(time),q=a.pose.q.map((v,k)=>v+(b.pose.q[k]-v)*u),rail=T.MathUtils.lerp(a.pose.rail,b.pose.rail,u),world=rig.matrices(q,rail,0);for(let [path,name] of Object.entries(rig.data.body_nodes)){let n=nodes.get(name.replace('body','UR10E_body'));if(n&&world[path]){n.matrix.copy(mat(mul(C,world[path])));n.matrixAutoUpdate=false;}}
 const actualTip=new T.Vector3(0,0,definition.tcp_from_wrist_mm/1000).applyMatrix4(mat(mul(C,world['/World/RailSystem/Arm/wrist_3_link'])));if(view!=='shop'&&followPoint){const delta=actualTip.clone().sub(followPoint);camera.position.add(delta);controls.target.add(delta);}followPoint=actualTip;
 const shift=T.MathUtils.lerp(a.pose.tip_shift_mm,b.pose.tip_shift_mm,u);soften(shift);
 for(let [n,o] of nodes){if(n.startsWith('Drawer_'))o.position.z=n==='Drawer_'+item&&mode==='pick'?a.pose.drawer_open_m||0:0;if(n.startsWith('Product_'))o.visible=n==='Product_'+item;}
 const product=nodes.get('Product_'+item);let pm;if(a.held&&b.held){pm=mat(mul(mul(C,world['/World/RailSystem/Arm/wrist_3_link']),s.grasp_relative));}else{let A=mat(a.product_matrix),B=mat(b.product_matrix),pa=new T.Vector3(),pb=new T.Vector3(),qa=new T.Quaternion(),qb=new T.Quaternion(),sa=new T.Vector3(),sb=new T.Vector3();A.decompose(pa,qa,sa);B.decompose(pb,qb,sb);pm=new T.Matrix4().compose(pa.lerp(pb,u),qa.slerp(qb,u),sa.lerp(sb,u));}product.matrix.copy(pm);product.matrixAutoUpdate=false;
 if(item==='Dessert'&&mode==='place'){const cola=nodes.get('Product_Cola'),frames=review.sequences.Cola_place.frames;cola.visible=true;cola.matrix.copy(mat(frames[frames.length-1].product_matrix));cola.matrixAutoUpdate=false;}
 if(i!==lastIndex){info(a,s);highlight(a);lastIndex=i;}$('progress').value=time;$('view').dataset.review=JSON.stringify({sequence:s.key,frame:i,rootHash:definition.root_hash,moduleCount:4,productMatrix:pm.toArray(),ikValid:a.pose.valid,hits:(a.check?.tool_hits||[]).length,held:a.held});
 for(let n of changed)n.visible=$('slots').checked;original.visible=!$('slots').checked;cutLines.visible=item==='Box'&&$('cutOutline').checked&&$('slots').checked;
}
function select(){if(!ready)return;playing=false;$('play').textContent='Oynat';time=0;lastIndex=-1;for(let id of ['play','prev','next','progress'])$(id).disabled=sequence().frames.length<2;$('boxControls').classList.toggle('hidden',item!=='Box');$('viewTitle').textContent={Dough:'Hamur',Cola:'İçecek',Dessert:'Tatlı',Box:'Kutu'}[item]+' · '+(item==='Box'?'alma denemesi':mode==='pick'?'alma':'bırakma');for(let b of document.querySelectorAll('[data-item]'))b.classList.toggle('active',b.dataset.item===item);for(let b of document.querySelectorAll('[data-mode]')){b.classList.toggle('active',b.dataset.mode===mode);b.disabled=item==='Box';}for(let b of document.querySelectorAll('[data-variant]'))b.classList.toggle('active',b.dataset.variant===variant);draw();cameraView(view);}
try{let data;[review,definition,manifest,data]=await Promise.all(['review.json','head_definition.json','focus_manifest.json','rig.json'].map(n=>fetch(base+n,{cache:'no-store'}).then(r=>r.json())));rig=new Rig(data,{mountForward:.1,railForward:.5});[model,head,original]=await Promise.all([glb('focus'),glb('fixed_head'),glb('e_original')]);scene.add(model,original);original.visible=false;model.traverse(o=>{nodes.set(o.name,o);if(o.isMesh)o.material=Array.isArray(o.material)?o.material.map(m=>m.clone()):o.material.clone();});let wrist=nodes.get('UR10E_body_06');if(!wrist)throw Error('Robot bileği bulunamadı');wrist.add(head);head.traverse(o=>{if(o.isMesh&&o.name.startsWith('OEM_DAC_')){o.geometry=o.geometry.clone();tips.push({mesh:o,v:o.geometry.attributes.position.array.slice()});}});if(tips.length!==4)throw Error('Dört uç bulunamadı');changed.push(...manifest.filter(x=>['E_KALIP__sac__NEST','E_KALIP__sac'].includes(x.source)).map(x=>nodes.get(x.node)).filter(Boolean));for(let slot of review.box_support.slots){let lo=new T.Vector3(...slot.bounds_m[0]),hi=new T.Vector3(...slot.bounds_m[1]),geometry=new T.EdgesGeometry(new T.BoxGeometry(...hi.clone().sub(lo).toArray())),line=new T.LineSegments(geometry,new T.LineBasicMaterial({color:0x0caa82}));line.position.copy(lo.add(hi).multiplyScalar(.5));cutLines.add(line);}ready=true;translucency();select();$('loading').classList.add('hidden');}catch(e){$('loading').textContent='V2 açılamadı: '+e.message;console.error(e);}
document.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>{item=b.dataset.item;mode=item==='Box'?'pick':mode;select();});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;select();});document.querySelectorAll('[data-variant]').forEach(b=>b.onclick=()=>{variant=b.dataset.variant;select();});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>cameraView(b.dataset.view));$('ghost').onchange=translucency;$('slots').onchange=()=>{lastIndex=-1;draw();};$('cutOutline').onchange=draw;$('reset').onclick=select;$('play').onclick=()=>{if(time>=1)time=0;playing=!playing;$('play').textContent=playing?'Durdur':'Oynat';};$('prev').onclick=()=>{playing=false;time=Math.max(0,time-1/(sequence().frames.length-1));lastIndex=-1;draw();};$('next').onclick=()=>{playing=false;time=Math.min(1,time+1/(sequence().frames.length-1));lastIndex=-1;draw();};$('progress').oninput=()=>{playing=false;time=+$('progress').value;lastIndex=-1;draw();};
new ResizeObserver(()=>{let el=$('view');renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();}).observe($('view'));renderer.setAnimationLoop(stamp=>{if(playing&&ready){time=Math.min(1,time+Math.min((stamp-lastStamp)/1000,.05)/(sequence().duration_s||6));if(time>=1){playing=false;$('play').textContent='Oynat';}draw();}lastStamp=stamp;controls.update();renderer.render(scene,camera);});
