import * as T from 'three';
import {GLTFLoader} from './vendor/GLTFLoader.js';
import {OrbitControls} from './vendor/OrbitControls.js';
const $=x=>document.getElementById(x),base='../../../hat3d/rochu-sabit-v1/';
const scene=new T.Scene();scene.background=new T.Color('#e3e7df');
const renderer=new T.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;$('view').prepend(renderer.domElement);
const camera=new T.PerspectiveCamera(37,1,.003,80),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=.05;controls.maxDistance=16;
scene.add(new T.HemisphereLight(0xfafff0,0x616950,2.1));const sun=new T.DirectionalLight(0xfff5dd,2.7);sun.position.set(3,6,4);scene.add(sun);const fill=new T.DirectionalLight(0xe2ecff,1.8);fill.position.set(-2,2,-3);scene.add(fill);
const floor=new T.Mesh(new T.PlaneGeometry(14,10),new T.MeshStandardMaterial({color:0xd3d9cb,roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.set(3,-.035,1);scene.add(floor);const grid=new T.GridHelper(12,24,0xa6b2a0,0xc0c8b8);grid.position.set(3,-.032,1);scene.add(grid);
let model,head,poses,audit,def,manifest,item='Dough',mode='pick',tilt=0,view='close',current,shift=0,loaded=false;
const originals=new Map(),byName=new Map(),tips=[],standGroup=new T.Group();scene.add(standGroup);
const marker=new T.Mesh(new T.SphereGeometry(.004,20,12),new T.MeshBasicMaterial({color:0xf26744}));scene.add(marker);const targetRing=new T.Mesh(new T.TorusGeometry(.013,.0007,8,40),new T.MeshBasicMaterial({color:0xf26744}));targetRing.rotation.x=Math.PI/2;scene.add(targetRing);
const fmt=(n,d=1)=>Number(n).toLocaleString('tr-TR',{maximumFractionDigits:d,minimumFractionDigits:d});
function matrix(a){return new T.Matrix4().set(...a.flat());}
async function glb(name){const res=await fetch(base+name+'.glb.gz',{cache:'no-store'});if(!res.ok)throw Error(name+': '+res.status);const b=await new Response(res.body.pipeThrough(new DecompressionStream('gzip'))).arrayBuffer();return (await new GLTFLoader().parseAsync(b,location.href)).scene;}
function soften(v){shift=v;$('view').dataset.tipShiftMm=v;$('shift').value=v;$('shiftLabel').textContent=(v>0?'+':'')+fmt(v)+' mm';for(const t of tips){const a=t.mesh.geometry.attributes.position;for(let i=0;i<a.count;i++){const z=t.v[i*3+2]+.073;let w=T.MathUtils.clamp((z-.085)/.0202,0,1);w=w*w*(3-2*w);a.setXYZ(i,t.v[i*3]-v*.001*w,t.v[i*3+1],t.v[i*3+2]);}a.needsUpdate=true;t.mesh.geometry.computeVertexNormals();t.mesh.geometry.computeBoundingSphere();}}
function cameraView(kind){view=kind;if(!current)return;const p=new T.Vector3(...current.product),c=new T.Vector3(...current.contact);let aim=c.clone().add(new T.Vector3(0,.05,0)),eye;
 if(kind==='shop'){aim.set(2.8,.8,.7);eye=new T.Vector3(7.5,4.8,6.8);controls.minDistance=.2;}
 else if(kind==='hand'){aim=c.clone().add(new T.Vector3(0,.035,0));eye=aim.clone().add(item==='Box'?new T.Vector3(.20,.10,mode==='pick'?.25:-.25):new T.Vector3(.20,.14,.19));controls.minDistance=.045;}
 else{aim=c.clone().add(new T.Vector3(0,.11,0));eye=aim.clone().add(item==='Box'?new T.Vector3(.55,.30,mode==='pick'?.62:-.62):new T.Vector3(.54,.42,.56));controls.minDistance=.12;}
 camera.position.copy(eye);controls.target.copy(aim);camera.lookAt(aim);controls.update();for(const b of document.querySelectorAll('[data-view]'))b.classList.toggle('active',b.dataset.view===kind);}
function makeStand(p){standGroup.clear();if(item!=='Box'||mode!=='place'||!$('stand').checked)return;const c=current.product,bottom=c[1]-.0225,sign=mode==='pick'?1:-1;const mat=new T.MeshStandardMaterial({color:0x29aa98,roughness:.65});function box(size,pos){const m=new T.Mesh(new T.BoxGeometry(...size),mat);m.position.set(...pos);standGroup.add(m);}const w=.3224,length=.3232,depth=.08,bay=.11,h=.020;box([w,h,length-depth],[c[0],bottom-h/2,c[2]-sign*depth/2]);for(const s of [-1,1])box([(w-bay)/2,h,depth],[c[0]+s*(bay/2+(w-bay)/4),bottom-h/2,c[2]+sign*(length/2-depth/2)]);}
function select(){if(!loaded)return;const key=item+(item==='Dough'?(tilt?'_tilt':$('clear').checked?'_clear':''):item==='Box'&&mode==='place'&&!$('stand').checked?'_no_stand':'')+'_'+mode;current=poses[key];const p=current,entry=audit.poses[key];for(const [n,o]of byName){if(n.startsWith('UR10E_body_')&&p.worlds[n]){o.matrix.copy(matrix(p.worlds[n]));o.matrixAutoUpdate=false;}if(n.startsWith('Drawer_'))o.position.z=n==='Drawer_'+item?p.drawer_open_m:0;if(n.startsWith('Product_')){o.visible=n==='Product_'+item;if(o.visible){o.position.set(...p.product);}}}
 const lift=+$('lift').value;byName.get('Opener').position.y=lift/1000;makeStand(p);soften(p.tip_shift_mm);marker.position.set(...p.contact);targetRing.position.copy(marker.position);targetRing.visible=!p.valid;marker.visible=!p.valid;
 $('dough').classList.toggle('hidden',item!=='Dough');$('clearWrap').classList.toggle('hidden',tilt!==0);$('liftWrap').classList.toggle('hidden',item!=='Dough'||mode!=='place');$('standWrap').classList.toggle('hidden',item!=='Box'||mode!=='place');
 const names={Dough:'Hamur',Cola:'İçecek',Dessert:'Tatlı',Box:'Kutu'};$('viewTitle').textContent=names[item]+' · '+(mode==='pick'?'alma':'bırakma')+' noktası'+(item==='Dough'&&tilt?' / aynı 45°':'');let finding,description,status,measure,label,notice='';
 if(item==='Dough'){
  if(tilt){status='Bu açı testi geçmiyor';finding=mode==='pick'?'Erişiyor; çekmeceye ve komşu hamura giriyor.':'Erişiyor; alt uçlar tablaya giriyor.';description='Alma ve bırakma açısı aynı. Dört ucun bu eğimde korunması alt tarafta boşluk istiyor.';measure=mode==='place'?fmt(1000-entry.actual_head_bottom_y_mm)+' mm':fmt(210.5-entry.actual_head_bottom_y_mm)+' mm';label=mode==='place'?'Tabla düzleminin altına inme':'Hamur alt seviyesinin altına inme';notice='Robot ulaşsa da bu kavrama yerleşimi uygun değil. Açıcıyı yükseltmek, alt uçların tabla/çekmece çarpışmasını kaldırmaz.';}
  else if(mode==='place'){status='Erişim testi geçmiyor';finding='Mevcut raydan dik bırakma pozuna ulaşamadı.';description='Kırmızı halka hedefi gösteriyor. Robot en yakın çözüme yerleşti; bu bir bırakma pozu değil.';measure=fmt(entry.position_error_mm)+' mm';label='Hedef konuma kalan hata';notice='Bu dik poz geçerli değil. Açıcı için kullanılabilir en düşük yükseklik, çarpışmasız bir bırakma pozu bulunmadan belirlenemez.';}
  else{status='Yerel boşluk sorunu';finding='Alt şişkin bölgeye iniyor; çekmece silikonuna temas ediyor.';description='Kaynak hamurun en geniş kısmı alt 10 mm’de. Hedef, tabanın 6,5 mm üstünde; uç tabandan 2 mm uzakta.';measure='2,0 mm';label='Hedefteki alt uç / hamur tabanı';notice='Dik alma denemesinde komşu hamura giriş bulunmadı; çekmecenin diğer parçalarıyla boşluk sorunu var. 42 adet stok yerleşimi korunuyor.';}
 }else if(item==='Cola'){status='Kuvvet doğrulaması gerekli';finding='Düz kavrama yüzleri gövdeye içe bakıyor.';description='Dört bağlantı aynı yerde. 65,5 mm çap için kapanma yaklaşık 10 mm; katalogdaki yaklaşık 11 mm sınırına yakın.';measure=fmt(11+entry.tip_shift_mm)+' mm';label='Yaklaşık kapanma payı';}
 else if(item==='Dessert'){status='Giriş açıklığı dar';finding='94,3 mm gövdede çok az açılma payı kalıyor.';description='Üst gövde kenarı hedefleniyor; gerçek kapak geometrisi ayrıca gerekir. Tek ayarın en büyük çapı yaklaşık 95,6 mm; 95 mm ürün için toplam yalnız 0,6 mm fark var.';measure='0,6 mm';label='95 mm ürünün giriş çapı farkı';}
 else{status='Sınırda; dört temas onaylanmadı';finding=mode==='place'?'Alt uçlara açık ağızlı stand boşluğu açılıyor.':'E çıkışındaki kutu kenarı hedefleniyor.';description='Uç kökleri değişmiyor. 45 mm kalınlık için yaklaşık kapanma sınırındayız; karton ve kapak yük altında denenmeli.';measure=mode==='place'?'20 mm':'45 mm';label=mode==='place'?'Önerilen QR standı yüksekliği':'Kaynak kutu kalınlığı';notice=mode==='place'?'Yeşil stand öneridir: 110 × 80 mm açık ağız. Dört çapraz yüzün kartona teması firmaya doğrulatılmalı.':'Bu nokta E’nin kaynak kutu konumudur; kalıp ve robot pozları birlikte denetlenir.';}
 if(!p.valid&&item!=='Dough'){status='Erişim testi geçmiyor';finding='Bu hedef konuma ulaşamadı.';description='Kırmızı halka hedefi gösterir; görünür robot en yakın çözümdedir. Bu bir başarılı bırakma pozu değildir.';notice='Pozun erişim ve boşluk testi geçmedi.';}if(entry.local_environment_hits?.length){status='Yerel çakışma var';const qr=entry.local_environment_hits.some(x=>x.part.startsWith('QR62_'));if(qr){finding='Robot bileği QR dolabının üst rafına giriyor.';description='Bu bırakma pozu mevcut raf boşluğuna sığmıyor. Uç montajı sabit; kavrama ve yerleştirme ayrı sorunlar.';notice='Üst rafla çakışma bulundu. İçecek/tatlı için bu yerleşim tamamlanmış çözüm sayılmaz.';}else if(item==='Cola'){finding='Çekmecenin ön şeffaf parçasına temas var.';description='İçeceğin üst gövde bölgesi hedefleniyor; bu alma pozu ön parça için boşluk bırakmıyor. Kapanma payı da yaklaşık 1 mm.';}else if(item==='Box'){finding='E’nin kalıp parçalarıyla çakışma var.';description='Kaynak kutu konumunda alma takımı kalıba giriyor. Bu noktada stand eklenmedi; mevcut E çıkışı bu takımla temiz değil.';}}if(item==='Dough'&&tilt&&mode==='place')notice='Bu pozda yalnız açıcı gövdesini temizlemek için tarama yaklaşık +160 mm yükseltme öneriyor. Ancak alt uçlar tablaya '+fmt(1000-entry.actual_head_bottom_y_mm)+' mm giriyor; yükseltme tek başına çözüm değil.';
 if(item==='Dough'&&!tilt&&$('clear').checked&&mode==='pick'){status='Silikon teması sürüyor';finding='5 mm yükseltmek teması tamamen kaldırmıyor.';description='Hacim hesabı sıfır gösterse de gerçek üçgen yüzeyler kesişiyor. Uç tabandan 7 mm uzakta; alt şişkin bölgeyle temas derinliği de azalıyor.';measure='7 mm';label='Uç / hamur tabanı';notice='Bu poz temiz sayılmadı. Çekmece silikonundaki kesişme ve dik bırakmanın erişim sorunu sürüyor.';}
 if(item==='Box'&&mode==='place'&&!$('stand').checked){status='Standsız karşılaştırma';finding=mode==='place'?'Alt takım QR rafının altına iniyor.':'Kaynak E alma konumu; kalıp engeli var.';description='Stand kapalı: robot ve ürün bu yüksekliğe birlikte yerleşir. Stand geometrisi görünmez.';measure='0 mm';label='Stand kapalı';notice='Standsız poz karşılaştırmasıdır; geçerli ve güvenli kavrama sonucu değildir.';}
 if(!p.valid&&item!=='Dough')notice+=' Erişim hesabı da geçmedi: konum hatası '+fmt(p.position_error_mm)+' mm.';head.updateMatrixWorld(true);$('view').dataset.review=JSON.stringify({key,rootHash:p.root_hash,moduleCount:4,stockCount:audit.stock_count,ikValid:p.valid,localHits:entry.local_environment_hits?.length||0,confirmedSurfaceHits:entry.confirmed_native_surface_hits?.length||0,renderedRoots:[0,1,2,3].map(i=>head.getObjectByName('Finger_'+i).matrix.toArray()),productCentre:byName.get('Product_'+item).position.toArray()});
 $('status').textContent=status;$('finding').textContent=finding;$('description').textContent=description;$('measure').textContent=measure;$('measureLabel').textContent=label;$('notice').textContent=notice;$('notice').classList.toggle('hidden',!notice);
 for(const b of document.querySelectorAll('[data-item]'))b.classList.toggle('active',b.dataset.item===item);for(const b of document.querySelectorAll('[data-mode]'))b.classList.toggle('active',b.dataset.mode===mode);for(const b of document.querySelectorAll('[data-tilt]'))b.classList.toggle('active',+b.dataset.tilt===tilt);cameraView(view);window.reviewState={key,rootHash:p.root_hash,moduleCount:def.module_count,ikValid:p.valid,positionErrorMm:p.position_error_mm,angleErrorDeg:p.angle_error_deg,tipShiftMm:shift,stockCount:audit.stock_count,stand:$('stand').checked,openerLiftMm:lift};}
function translucency(){const ghost=$('ghost').checked;model.traverse(o=>{if(!o.isMesh)return;let group=o.parent;while(group&&group.parent!==model)group=group.parent;const native=!(group?.name.startsWith('UR10E')||group?.name.startsWith('Product_'));if(!native)return;for(const mat of [].concat(o.material)){mat.transparent=ghost;mat.opacity=ghost?.22:1;mat.depthWrite=!ghost;mat.needsUpdate=true;}});}
try{
 [poses,audit,def,manifest]=await Promise.all(['poses.json','audit.json','head_definition.json','focus_manifest.json'].map(n=>fetch(base+n,{cache:'no-store'}).then(r=>r.json())));[model,head]=await Promise.all([glb('focus'),glb('fixed_head')]);scene.add(model);model.traverse(o=>{byName.set(o.name,o);originals.set(o.name,o.matrix.clone());if(o.isMesh){o.material=Array.isArray(o.material)?o.material.map(m=>m.clone()):o.material.clone();o.castShadow=false;o.receiveShadow=false;}});const wrist=byName.get('UR10E_body_06');if(!wrist)throw Error('Robot bileği bulunamadı: '+model.children.map(n=>n.name).join(', '));wrist.add(head);head.traverse(o=>{if(o.isMesh&&o.name.startsWith('OEM_DAC_')){o.geometry=o.geometry.clone();tips.push({mesh:o,v:o.geometry.attributes.position.array.slice()});}});if(tips.length!==4)throw Error('Dört OEM uç doğrulanamadı: '+tips.length);
 if(Object.values(poses).some(p=>p.root_hash!==def.root_hash)||Object.values(audit.poses).some(p=>p.root_hash!==def.root_hash))throw Error('Denetim kaydı güncelleniyor; tekrar açın.');loaded=true;select();translucency();$('loading').classList.add('hidden');window.reviewReady=true;
}catch(e){$('loading').textContent='Sahne açılamadı: '+e.message;console.error(e);window.reviewError=e.message;}
document.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>{item=b.dataset.item;view='close';select();});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;select();});document.querySelectorAll('[data-tilt]').forEach(b=>b.onclick=()=>{tilt=+b.dataset.tilt;select();});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>cameraView(b.dataset.view));$('shift').oninput=()=>{soften(+$('shift').value);if(window.reviewState)window.reviewState.tipShiftMm=shift;};$('contact').onclick=()=>soften(current.tip_shift_mm);$('lift').oninput=()=>{byName.get('Opener').position.y=+$('lift').value/1000;$('liftLabel').textContent=$('lift').value+' mm';if(window.reviewState)window.reviewState.openerLiftMm=+$('lift').value;};$('stand').onchange=select;$('clear').onchange=select;$('ghost').onchange=translucency;
new ResizeObserver(()=>{const el=$('view');renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();}).observe($('view'));
renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera);});
