// Exact native USD joint-frame FK. Row-major matrices, metres, Isaac Z-up.
export const I=()=>[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];
export const flat=m=>m.flat();
export function mul(a,b){const r=Array(16).fill(0);for(let i=0;i<4;i++)for(let j=0;j<4;j++)for(let k=0;k<4;k++)r[4*i+j]+=a[4*i+k]*b[4*k+j];return r;}
export function inv(a){const r=I();for(let i=0;i<3;i++){for(let j=0;j<3;j++)r[4*i+j]=a[4*j+i];r[4*i+3]=-r[4*i]*a[3]-r[4*i+1]*a[7]-r[4*i+2]*a[11];}return r;}
export function point(a,p){return [0,1,2].map(i=>a[4*i]*p[0]+a[4*i+1]*p[1]+a[4*i+2]*p[2]+a[4*i+3]);}
function turn(axis,t){const m=I(),c=Math.cos(t),s=Math.sin(t),a=axis==='X'?[1,2]:axis==='Y'?[2,0]:[0,1];m[4*a[0]+a[0]]=c;m[4*a[1]+a[1]]=c;m[4*a[0]+a[1]]=-s;m[4*a[1]+a[0]]=s;return m;}
const WR='/World/RailSystem/Arm/wrist_3_link',GP='/World/RailSystem/Gripper/';
export class Rig{
 constructor(data,options={}){this.data=data;this.mountForward=options.mountForward||0;this.anchorCache=new Map();this.railForward=0;this.edges=data.edges.map(e=>({...e,a:flat(e.a),bi:inv(flat(e.b))}));if(this.mountForward){const mount=this.edges.find(e=>e.name==='RobotMountJoint');mount.a[7]-=this.mountForward;}this.groundAnchor=this.edges.find(e=>e.name==='GroundMountJoint');this.originalGroundY=this.groundAnchor.a[7];this.setRailForward(options.railForward||0);this.adjacent=new Set(data.edges.map(e=>[e.parent,e.child].sort().join('|')));}
 setRailForward(d){this.railForward=d;this.groundAnchor.a[7]=this.originalGroundY-d;this.anchorCache.clear();}
 matrices(q,rail,jaw){const angles=Object.fromEntries(this.data.arm_joints.map((a,i)=>[a,q[i]])),j=jaw*Math.PI/180;Object.assign(angles,{finger_joint:j,right_outer_knuckle_joint:j,left_inner_knuckle_joint:j,right_inner_knuckle_joint:-j,left_inner_finger_joint:-j,right_inner_finger_joint:-j});const out={},pending=[...this.edges];while(pending.length){let progress=false;for(const e of [...pending]){if(e.parent&&!out[e.parent])continue;let m=I();if(e.name==='RailJoint')m[3]=rail-this.data.rail_min;else if(e.type==='PhysicsRevoluteJoint')m=turn(e.axis,angles[e.name]||0);out[e.child]=mul(mul(mul(out[e.parent]||I(),e.a),m),e.bi);pending.splice(pending.indexOf(e),1);progress=true;}if(!progress)throw Error('Eklem zinciri kopuk');}return out;}
 anchor(jaw){if(this.anchorCache.has(jaw))return this.anchorCache.get(jaw);const w=this.matrices([0,0,0,0,0,0],this.data.rail_min,jaw),a=point(w[GP+'left_inner_finger'],[.1845,.062,0]),b=point(w[GP+'right_inner_finger'],[.1845,-.062,0]);const result=point(inv(w[WR]),a.map((x,i)=>(x+b[i])/2));this.anchorCache.set(jaw,result);return result;}
 tcp(q,rail,jaw){const m=[...this.matrices(q,rail,jaw)[WR]],p=point(m,this.anchor(jaw));m[3]=p[0];m[7]=p[1];m[11]=p[2];return m;}
 error(q,rail,jaw,target){const m=this.tcp(q,rail,jaw),r=mul(inv(target),m),c=Math.max(-1,Math.min(1,(r[0]+r[5]+r[10]-1)/2)),t=Math.acos(c);let axis=[r[9]-r[6],r[2]-r[8],r[4]-r[1]];if(t>3.13){axis=[Math.sqrt(Math.max(0,(r[0]+1)/2)),Math.sqrt(Math.max(0,(r[5]+1)/2)),Math.sqrt(Math.max(0,(r[10]+1)/2))];axis[1]*=r[1]<0?-1:1;axis[2]*=r[2]<0?-1:1;axis=axis.map(x=>x*t);}else axis=axis.map(x=>x*(t<1e-6?.5:t/(2*Math.sin(t))));return [m[3]-target[3],m[7]-target[7],m[11]-target[11],...axis.map(x=>x*.35)];}
 solve(target,rail,jaw,seed){let q=seed.map(v=>Math.atan2(Math.sin(v),Math.cos(v))),best=null;for(let n=0;n<80;n++){const e=this.error(q,rail,jaw,target),score=Math.hypot(...e);if(!best||score<best.score)best={q:[...q],score};if(Math.hypot(...e.slice(0,3))<.00001&&Math.hypot(...e.slice(3))<.00001)break;const J=Array.from({length:6},()=>Array(6));for(let j=0;j<6;j++){const v=[...q];v[j]+=.0001;const ev=this.error(v,rail,jaw,target);for(let i=0;i<6;i++)J[i][j]=(ev[i]-e[i])/.0001;}const a=Array.from({length:6},(_,i)=>Array.from({length:7},(_,j)=>j===6?-J.reduce((s,row,k)=>s+row[i]*e[k],0):J.reduce((s,row)=>s+row[i]*row[j],0)+(i===j?.00008:0)));for(let i=0;i<6;i++){let k=i;for(let z=i+1;z<6;z++)if(Math.abs(a[z][i])>Math.abs(a[k][i]))k=z;[a[k],a[i]]=[a[i],a[k]];const p=a[i][i];if(Math.abs(p)<1e-14)break;for(let j=i;j<7;j++)a[i][j]/=p;for(let z=0;z<6;z++)if(z!==i){const f=a[z][i];for(let j=i;j<7;j++)a[z][j]-=f*a[i][j];}}q=q.map((v,i)=>Math.max(-Math.PI*2,Math.min(Math.PI*2,v+Math.max(-.18,Math.min(.18,a[i][6])))));}q=best.q;const e=this.error(q,rail,jaw,target),position=Math.hypot(...e.slice(0,3)),angle=Math.hypot(...e.slice(3))/.35*180/Math.PI;return {q,position,angle,valid:position<.002&&angle<.5};}
}
